baru-baru ini , pada bulan Ogos 2004 , tuntutan mahkamah bernilai AS $ 543 juta telah difailkan terhadap Newmont Mining oleh Kementerian Alam Sekitar Indonesia dan penduduk setempat .
mereka mendakwa bahawa pencemaran yang disebabkan oleh aktiviti perlombongan syarikat itu telah menyebabkan penyakit yang serius dan masalah kesihatan yang lain , termasuk penyakit kulit , tumor , kecacatan kelahiran , dan penurunan dalam stok ikan dan makanan asas .
satu amalan perlombongan tertentu digunakan dengan kerap oleh Newmont Mining di Indonesia adalah sisa pelupusan kapal selam , kaedah pelupusan sisa bagi merkuri dan arsenik yang diharamkan di Amerika Syarikat .
sekurang-kurangnya enam pengurus Newmont Mining , termasuk seorang rakyat Amerika dan Australia , menghadapi sehingga 15 tahun hukuman penjara Jakarta untuk jenayah alam sekitar dan korporat dalam kes itu .
penduduk tempatan Peru meneruskan perjuangan mereka untuk amalan perlombongan selamat dan pampasan bagi kerosakan dan kecederaan yang sedia ada .
beribu-ribu penduduk bandar tempatan membantah terhadap perlombongan Yanacocha pada musim luruh lepas , menuntut perlindungan untuk bekalan air tempatan .
pegawai Newmont Mining telah menyalahkan tumpahan merkuri kepada kontraktor pada bulan Jun 2000 , dan telah kalah dalam perlawanan untuk memastikan kes itu berada di luar sistem mahkamah Amerika .
kerajaan Somalia menggesa masyarakat antarabangsa pada hari Sabtu untuk membantu membendung gelombang serangan lanun baru-baru ini di luar pantai mereka di Lautan Hindi .
Biro Maritim Antarabangsa ( IMB ) yang berpangkalan di London semalam melaporkan sebuah kapal dagang Thai dan 26 anak kapal telah dirampas oleh lanun Somalia di luar pantai mereka .
kebanyakannya kru kapal Thai telah diculik dan diacukan pistol , dan wang tebusan telah dituntut untuk pembebasan mereka .
kapal saudagar sedang dalam laluan dari Brazil ke Yaman dengan membawa muatan gula .
surat ke Somalia dari Bangsa-Bangsa Bersatu keselamatan majlis mengingatkan kerajaan itu .
Somalia sebahagian besarnya hancur ke dalam sistem feudal sejak bekas diktator Siad Barre digulingkan pada tahun 1991 .
hujung minggu lalu , sebuah kapal pesiar milik Amerika Syarikat telah diserang dengan bom tangan roket .
ia adalah kapal keempat yang diserang dalam ruang masa seminggu .
menurut IMB , terdapat 23 serangan lanun lain di perairan negara Afrika timur sejak 15 Mac lalu .
pentadbiran Obama telah menafikan wartawan Colombia Hollman Morris masuk ke Amerika Syarikat , memetik dari sumber sebagai satu pelanggaran undang-undang " aktiviti pengganas " dalam Akta Patriot Amerika Syarikat itu .
Morris telah cuba untuk mendapatkan visa untuk menghadiri Program Nieman Universiti Harvard , yang merupakan satu pertemuan persahabatan untuk wartawan .
wartawan itu telah menarik perhatian hubungan antara Presiden Colombia Alvaro Uribe , dan kumpulan militia sayap kanan di negara yang dilanda perang di Amerika Selatan itu .
aktivis hak asasi manusia telah membuat spekulasi bahawa Uribe mungkin ialah penyebab visa tidak diluluskan .
telefon Morris juga telah dirakam oleh DAS , agensi keselamatan negara Colombia , yang merupakan rakan sejawatan CIA Colombia .
alasan sebenar untuk Morris ' dinafikan visa ' tidak jelas , apabila Morris pergi ke lokasi untuk meliputi pembebasan empat anggota pasukan keselamatan Colombia oleh pemberontak FARC , Uribe memanggil wartawan sebagai " rakan jenayah keganasan . "
sekurang-kurangnya 11 spesies kehidupan baru telah ditemui di hutan hujan Wilayah Thua Thien-Hue di Vietnam di sebuah kawasan yang mempunyai hutan yang digambarkan sebagai " Koridor Hijau . "
penemuan itu dibuat oleh penyelidik daripada Kumpulan Dana Sedunia untuk Alam Semula Jadi ( WWF ) .
antara spesies baru ialah lima orkid dan sekurang-kurangnya tiga spesies lain tumbuh-tumbuhan , dua rama-rama dan seekor ular .
sekurang-kurangnya lebih sepuluh spesies tumbuhan dipercayai spesies baru tetapi masih dalam kajian .
" anda hanya menemui banyak spesies baru di tempat-tempat yang sangat istimewa , dan Koridor Hijau adalah salah satu daripadanya . "
" beberapa spesies mamalia besar telah ditemui pada tahun 1990-an di hutan yang sama , bermaksud penemuan terkini boleh menjadi hanya sebahagian kecil daripada bilangan itu , " kata seorang penasihat teknikal di Vietnam untuk WWF , Chris Dickinson .
spesies baru kehidupan adalah eksklusif untuk hutan hujan di Wilayah Thua Thien-Hue .
ular baru , yang boleh membesar sehingga 80 sentimeter panjang , telah diberikan nama whitle-lipped keelback kerana jalur kuning-putih di bahagian atas kepala dan membuat sarang yang berhampiran sungai kecil dan memakan haiwan kecil dan katak .
spesies baru rama-rama adalah salah satu subfamili daripada spesies Satyrinae dan spesies lain daripada rama-rama Skipper .
tanaman orkid , yang dianggap sangat jarang kerana mereka didapati tidak mempunyai sebarang daun pada tumbuhan , tumbuh di " benda " yang reput dan juga tidak mengandungi klorofil .
dua spesies baru tumbuhan adalah daripada Arum dan Aspidistra .
WWF bimbang bahawa ketamadunan mungkin bergerak lebih dekat ke dalam hutan hujan , memusnahkan habitat spesies baru , tetapi kerajaan Wilayah Thua Thien-Hue berkata ia komited untuk memastikan bahawa ianya dilindungi , bersama-sama dengan hutan hujan .
" kawasan ini adalah sangat penting untuk pemuliharaan dan wilayah ini mahu melindungi hutan dan alam sekitar mereka , serta menyumbang kepada pembangunan mampan , " kata Pengarah Jabatan Daerah Perlindungan Hutan bagi wilayah itu , Hoang Ngoc Khanh .
spesies itu ditemui di hutan hujan pada tahun 2005 dan 2006 .
taufan Paloma , di mana Pusat Taufan Kebangsaan Amerika Syarikat semalam melabelkan sebagai " amat merbahaya " , baru-baru ini melanda Cuba .
dalam persediaan ini , pada waktu 1500 UTC semalam , wilayah-wilayah Cuba di Granma dan Holguin telah dikeluarkan amaran taufan oleh kerajaan di negara ini .
oleh kerana ramalan telah dikemaskini , ia juga telah menarik balik amaran bagi wilayah Sancti Spiritus .
220,000 orang telah dipindahkan dari kawasan-kawasan rendah di wilayah Camaguey , manakala 170,000 dipindahkan dari wilayah Las Tunas .
taufan ini kini semakin lemah , bagaimanapun , NOAA menyatakan bahawa " kami meramalkan ianya semakin lemah dalam tempoh sehari dua ini , walaupun selepas Paloma bergerak dari luar pantai Cuba . "
NOAA juga telah menyatakan bahawa " Paloma dijangka menghasilkan jumlah hujan tambahan sebanyak 1 hingga 2 inci di timur Cuba . "
" pengumpulan hujan 5 hingga 10 inci mungkin berlaku di pusat Bahamas . "
taufan Paloma adalah bencana tropika ketujuh belas musim taufan Atlantik pada tahun 2008 .
Paloma dibangunkan daripada gangguan tropika yang kuat di luar pantai utara Honduras pada 5 November .
bencana itu kemudian menjadi ribut tropika dan kemudian menjadi taufan .
pasukan lelaki terakhir dalam gimnastik artistik berada dalam situasi tegang malam tadi di Sukan Olimpik di London .
Jepun mendapat pingat perak dengan 271.952 mata , dan Great Britain mendapat pingat gangsa dengan 271.711 mata .
Britain pada mulanya kelihatan akan menang pingat perak selepas gimnas Jepun Kohei Uchimura terjatuh daripada pommel horse .
Uchimura tidak menyangka jatuh dari pommel horse tetapi berjaya pulih dan mendarat dengan sempurna .
sebelum rayuan itu , skor Uchimura yang meletakkan Jepun di tempat keempat dengan Britain mengambil pingat perak dan Ukraine mengambil pingat gangsa dengan 271.526 mata .
hakim-hakim yang menerima rayuan Uchimura meningkatan skor akhir Jepun sebanyak 0.7 mata , hanya sedikit mendhului Great Britain dengan 0.241 mata .
gimnas British Louis Smith meraikan pingat gangsa Britain : " ia adalah hari yang indah untuk sukan ini dan untuk gimnastik British . "
Smith juga menjanjikan sesuatu yang hebat dari gimnas lelaki Britain , berjanji bahawa ahli-ahli pasukan Sam Oldham dan Max Whitlock akan memperbaiki prestasi untuk Sukan Olimpik yang akan datang di Rio .
Smith juga memuji skuad junior : " pemain muda kami akan datang - kami telah menjadi juara muda Eropah sejak enam tahun lalu - terdapat begitu banyak pemain pelapis . "
pasukan Amerika Syarikat , yang mendapat tempat pertama di pusingan kelayakan , mendapat tempat kelima di peringkat akhir yang menyebabkan John Orozco berlinangan air mata .
pasukan Amerika Syarikat berikrar untuk berjuang di dalam pertandingan individu .
Steve Penny dari Gimnastik Amerika Syarikat memberitahu pemberita : " mereka tahu bahawa mereka lebih baik daripada tempat kelima , dan mereka akan cuba untuk tunjukkan sehingga akhir pertandingan . "
sekurang-kurangnya 30 orang terbunuh dalam gempa bumi berkembar di Rwanda dan Republik Demokratik Congo .
Timbalan Ketua Polis Rwanda Mary Gahonzire bercakap kepada Reuters di Kigali , berkata gempa bumi yang melanda di sana bermagnitud 5.0 hingga 6.0 " Angka kematian [ di Rwanda ] kini telah meningkat kepada 25 daripada gempa bumi . "
" dua ratus orang mengalami kecederaan serius , " manakala Bernard Watunakanza , Pemangku Gabenor wilayah Selatan Kivu Bukavu berkata , " Sehingga kini , terdapat lima orang mati dan 149 cedera parah . "
ini menjadikan jumlah kematian semasa 30 dan jumlah kecederaan 350 .
Radio Rwanda melaporkan bahawa sepuluh daripada kematian Rwanda berlaku bersama-sama apabila sebuah gereja runtuh , membunuh mereka serta-merta .
AFP melaporkan perkhidmatan ambulans Rwanda tidak dapat menampung mangsa dan bas awam telah disediakan untuk membantu .
gempa bumi itu juga boleh dirasai berdekatan Burundi , tetapi tiada laporan kerosakan atau kecederaan di sana .
helikopter pemadam kebakaran Kamov-32 terhempas ketika cuba untuk mengisi tangki air , lapor Berita agensi Anatolia Turki .
sejak pertengahan bulan Ogos , kebakaran hutan telah melanda bahagian Selatan Turki termasuk destinasi pelancongan yang popular seperti Bodrum dan Antalya-Kas .
akhir-akhir ini Direktorat Perhutanan Umum telah menghantar teks mesej ringkas melalui pengusaha Turki untuk rakyat menyedari akan kebakaran hutan .
ketika amaran kebakaran yang lain bermula di Kas pada hujung minggu .
kebakaran terkini di Kas di bawah kawalan dengan bantuan dari helikopter pemadam api , di mana Kamof-32 jenis helikopter pemadam api Rusia telah terhempas semasa mengisi tangki dengan air berdekatan dengan Lake Gombe .
tiga rakyat Rusia bekerja dengan pasukan , seorang juruterbang Turki dan seorang jurutera Turki telah dilaporkan selamat dan dalam keadaan yang baik di Gombe Health Center .
Menteri Keadilan Iran Gholam-Hossein Elham telah meminta agar filem ahli politik Belanda Geert Wilders agar filem berasaskan Quran bernama Fitna diharamkan oleh kerajaan Belanda , agensi akhbar Iran IRNA melaporkan .
Elham menulis surat kepada rakan sejawatnya di Belanda Ernst Hirsch Ballin menyatakan bahawa : " anda boleh menghentikan perbuatan jahat dan pergerakan berkonspirasi ini berdasarkan Konvensyen Eropah mengenai Hak Asasi Manusia . "
kebebasan bersuara tidak boleh dijadikan sebab untuk membenarkan filem ini , kata mereka .
" kami juga menghormati kebebasan bersuara , tetapi menghina kesucian dan nilai etika sama sekali tidak boleh diterima , " Elham menulis .
" hak-hak umat Islam di seluruh dunia sedang dilanggar oleh filem yang mendorong kepada kekufuran ini . "
al-Quran adalah kitab suci untuk kira-kira 1.5 bilion umat Islam di seluruh dunia .
Wilders mengumumkan filem beliau yang " mengejutkan " ini akan siap pada Mac 2008 .
bangunan dewan bandar di Buffalo , New York telah dikosongkan selepas penggera kebakaran telah diaktifkan .
" pengesan asap berhenti berbunyi pada tingkat ke-13 dan ke-27 . "
" antara perkara lain ialah kami terputus komunikasi dengan luar bangunan tersebut . "
" ada sesuatu yang memutuskan komunikasi , ada sesuatu yang mencetuskan penggera dan memotong kuasa ke lif , " kata Mike Lombardo , Pesuruhjaya Bomba Buffalo .
polis dan anggota bomba tiba di tempat kejadian untuk menemui litar pintas di tingkat ke-27 yang memutuskan komunikasi di antara jabatan polis dan jabatan bomba di bandar itu selama hampir dua jam .
anggota bomba terpaksa menggunakan tangga kecemasan untuk memeriksa bangunan untuk kebakaran dan mangsa daripada bangunan 32 tingkat itu terpaksa menggunakan tangga kecemasan untuk meyelamatkan diri kerana lif di bangunan itu tidak berfungsi dengan baik .
menurut Lombardo , " ia kelihatan seperti kami tidak mengalami sebarang kebakaran [ di dalam bangunan ] " dan semua 2,800 pekerja telah dibenarkan kembali bekerja tidak lama selepas pukul 12 : 00 tengah hari .
" kami telah dapat menyelesaikan semula perkara ... kami berasa sangat yakin tiada masalah-masalah lain , " tambah Lombardo .
beribu-ribu orang telah berarak di jalan di Krakow bagi membantah rancangan untuk mengebumikan Presiden Poland , Lech Kaczynski , di Istana Wawel .
Kaczynski dan isterinya ditetapkan untuk dikebumikan pada hari Ahad .
ruang untuk dikebumikan di Istana Wawel biasanya dikhaskan untuk raja-raja Poland dan wira negara .
pengarah filem Poland Andrzej Wajda menyuarakan pendapatnya mengenai rancangan kawasan pengebumian mendiang presiden , mengatakan bahawa " Lech Kaczynski adalah seorang lelaki biasa dan baik , tetapi tidak ada sebab untuk beliau bersemadi di Wawel di kalangan raja-raja di Poland dan Marshal Józef Piłsudski [ pengasas zaman moden Poland ] . "
beliau terus mengulas , berkata keputusan itu " tidak kena pada tempatnya . "
beberapa pemimpin dan pembesar-pembesar di dunia akan menghadiri pengebumian presiden , termasuk Presiden Amerika Syarikat Barack Obama dan pemimpin Rusia Dmitry Medvedev .
ahli majlis British tempatan telah melaporkan bahawa mereka telah merampas ais krim yang dibuat daripada susu ibu manusia yang dijual di sebuah kedai di London , England , United Kingdom .
jurucakap Majlis Bandaraya Westminster menjelaskan bahawa dua aduan telah dibuat oleh orang ramai dan telah menerima balasan oleh Majlis .
The Icecreamists , syarikat pemasaran yang terlibat dengan pencuci mulut yang dikenali sebagai ' Baby Gaga ' , bekerjasama sepenuhnya dengan pegawai-pegawai yang menjalani ujian yang sedang dijalankan .
susu ibu yang disumbangkan oleh lima belas wanita yang telah menjawab iklan dalam talian yang terletak di forum yang mensasarkan golongan ibu .
menurut syarikat itu , semua susu telah ditapis bagi menghasilkan standard " paling tinggi dan paling selamat " sebelum dipasteur dan disediakan untuk penggunaan manusia .
ia kemudian dicampur dengan parutan kulit lemon dan benih vanila .
Matt O ' Connor , yang mengasaskan Icecreamists , menyatakan : " setakat pengetahuan kami tiada undang-undang yang melarang perniagaan menjual ais krim susu ibu . "
beliau mendakwa bahawa " jika ia cukup baik untuk anak-anak kita , ia adalah baik cukup untuk kita semua " dan " sesetengah orang akan mendengar mengenainya tidak akan menyukainya - tetapi sebenarnya ia adalah organik , diproses secara alami , dan benar-benar semula jadi . "
Brian Connell , ahli Parti Konservatif di UK , percaya bahawa " pihak berkuasa tempatan kami akan menyokong perniagaan kecil dan memuji idea-idea inovatif sebaik mungkin , tetapi perlu melindungi kesihatan pengguna . "
pada hari Isnin di Canberra , kerajaan Australia mengeluarkan bajet tahunan , sesuatu yang menjanjikan lebihan A $ 1.5 bilion untuk tahun ini , tetapi tidak banyak yag diperkatakan tentang potensi kesan bajet pada sukan Australia dalam tahun Olimpik apabila Australia dijangka untuk memperoleh pingat paling sedikit sejak 1996 Olimpik di Atlanta .
tidak ada kejutan yang ketara untuk sektor sukan di Australia dalam bajet ini .
bajet itu , yang boleh didapati dalam talian , mendakwa A $ 380 juta telah dibelanjakan untuk persediaan Sukan Olimpik tahun 2012 .
menurut Keith Lyons , Universiti Pengarah Canberra daripada Institut Pengajian Sukan , berkata sukan adalah satu bahagian penting dalam budaya Australia dan pembangunan sukan mendapat sokongan kedua-dua parti .
Sukan dalam " bajet boleh menyokong pembangunan infrastruktur dan mencerminkan pembaharuan pos tempat sukan Australia . "
" pelaburan Active After School mencerminkan komitmen untuk menyokong penyertaan dan penglibatan dalam aktiviti fizikal dan sukan . "
apabila Tony Naar Jawatankuasa Paralimpik Australia ditanya mengenai impak bajet terhadap usaha organisasinya , beliau berkata terdapat sedikit laporan kerana terdapat " sedikit inisiatif yang tidak diumumkan sebelum ini ... tahap keseluruhan pembiayaan program itu adalah sejajar dengan tahun akhir kitaran pembiayaan semasa . "
bajet ini menjamin untuk membangunkan kriket , khususnya Kriket Piala Dunia pada tahun 2015 dan bola sepak ( bola sepak ) Piala Asia 2015 dengan memperuntukkan dana untuk peningkatan kemudahan fasiliti .
A $ 50 juta akan dibelanjakan untuk membangunkan semula Sydney Cricket Ground , A $ 30 juta untuk membangunkan semula Adelaide Oval , dan A $ 15 juta untuk membangunkan semula Bellerive Oval di Hobart .
satu perkongsian antara kerajaan , Kerajaan New South Wales dan Sydney Cricket dan Sydney Cricket and Sports Ground Trust akan meliputi kos tambahan yang berkaitan dengan Sydney Cricket Ground dengan kerja dijangka siap pada 2014 .
infrastruktur sukan tempatan akan disokong dalam bajet dengan A $ 30 juta dikenal pasti untuk ini , A $ 10 juta khusus untuk peningkatan Olympic Park Presint Melbourne , A $ 5 juta untuk menyokong bola sepak di barat Sydney , dan A $ 3 juta untuk Bola Sepak New South Wales untuk membina ibu pejabat baru .
bajet ini menjanjikan bantuan kepada ibu bapa untuk membiayai kos aktiviti kurikulum anak-anak mereka termasuk sukan sebagai sebahagian daripada Bonus SchoolKid , yang akan menggantikan Bayaran Balik Cukai Pendidikan .
sokongan untuk sekolah berdasarkan sukan belia dengan A $ 39.2 juta diperuntukkan untuk komuniti Active After-School , sebuah program yang mencapai 190,000 kanak-kanak , yang menggalakkan mereka untuk mengambil bahagian dalam sukan sekolah .
dalam usaha untuk membendung kematian kanak-kanak disebabkan oleh lemas , satu inisiatif telah dilancarkan untuk meningkatkan keselamatan di air yang akan dijalankan melalui pusat-pusat awal kanak-kanak .
A $ 19.2 juta telah dipanjangkan kepada Suruhanjaya Sukan Australia untuk menjalankan program komuniti Active After-School pada 2012 / 2013 dengan pembiayaan yang sama untuk 2013 / 2014 .
2000 sekolah dan 1300 lepasan program sekolah akan mendapat manfaat daripada pembiayaan .
komuniti Street Soccer telah diperuntukkan A $ 1.0 juta untuk 2012 / 2013 dan A $ 1.6 juta untuk 2013 / 2014 .
tujuan ini adalah untuk membawa golongan gelandangan dan penganggur ke dalam masyarakat melalui penyertaan dalam bola sepak , Reclink Australia akan diberi dana untuk melaksanakan program ini .
A $ 4.8 juta telah diperuntukkan kepada Yayasan Clontarf di New South Wales untuk menyokong sukan tempatan dan digunakan di tempat lain mendorong gadis pribumi untuk mengambil bahagian dalam sukan di Australia Barat , Wilayah Utara , Victoria dan Queensland melalui Program Sporting Chance .
sambutan Centenary Canberra disebut dalam bajet Persekutuan , dengan A $ 2.6 juta diperuntukkan bagi 2011 / 2012 , A $ 2.0 juta diperuntukkan bagi 2012 / 2013 dan A $ 1.0 juta diperuntukkan bagi 2013 / 2014 .
sebahagian wang akan pergi ke bahagian sukan sebagai sebahagian daripada sambutan ini .
kerajaan Persekutuan melabur dalam Glenorchy , Tasmania , belanjawan A $ 8.7 juta dalam pembangunan semula stadium King George V dan komuniti presint , dengan wang yang diberikan kepada kerajaan tempatan .
tidak semua wang yang diperuntukkan untuk sukan , dengan sebahagian wang dibayar untuk pejabat khusus untuk Pusat Sumber Migrasi .
bajet yang diperuntukkan adalah kurang A $ 1,870,000 daripada apa yang telah dibelanjakan dalam bajet 2011 / 2012 ini .
kerajaan menjangkakan A $ 5.8 juta dalam simpanan dalam tempoh empat tahun akan datang kerana perubahan dalam ujian doping atlet .
dalam bajet tahun 2011 / 2012 , A $ 2,729,510 telah dibelanjakan untuk Wilayah Australia , Kerajaan Tempatan , Kesenian dan peruntukan khas sukan .
semua wang dalam kategori itu diperuntukkan selaras dengan Akta Kerajaan Tempatan ( Bantuan Kewangan ) 1995 .
dalam Akaun Sukan dan Rekreasi Khas di Jabatan Perdana Menteri dan peruntukan bajet kabinet , aliran tunai dan baki dibuka bagi bajet tahun ini dengan A $ 920,000 dan resit berjumlah A $ 317,000 .
di Jabatan Wilayah Australia , Kerajaan Tempatan , Kesenian dan pengagihan bajet Sukan , Sukan dan Akaun Rekreasi Khas mempunyai mempunyai baki pembukaan A $ 949,000 .
anggaran bagi resit 2012 / 2013 adalah A $ 537,000 , meningkat daripada A $ 220,000 dalam resit sebenar dalam bajet 2011 / 2012 ini .
Suruhanjaya Sukan Australia membelanjakan A $ 214,534,000 pada 2011 / 2012 dalam kategori bajet pertama mereka , dan mempunyai bajet yang lebih kecil berjumlah A $ 101,942,000 untuk 2012 / 2013 dalam kategori yang sama .
dalam kategori kedua bajet mereka , mereka membelanjakan A $ 54,159,000 pada 2011 / 2012 , dengan anggaran 2012 / 2013 meningkatkan belanjawan kepada A $ 166,201,000 .
untuk jumlah Peruntukan , kawasan pertama menurun sebanyak A $ 117,170,000 dan kawasan kedua menyaksikan peningkatan dalam A $ 114,353,000 .
haiwan kumpulan besar mungkin mempunyai keupayaan untuk mengesan medan magnet bumi , saintis di Jerman membuat kesimpulan pada laporan yang disiarkan dalam Prosiding minggu ini di Akademi Sains Kebangsaan selepas melakukan kajian lembu dan rusa meragut rumput dan corak tidur .
haiwan-haiwan cenderung untuk menghadap orientasi utara-selatan menuju ke arah kutub magnet bumi .
Hynek Burda dari Universiti Duisburg-Essen di Jerman mengetuai pasukan yang mengumumkan kajian yang belum disahkan itu .
Burda dan pasukannya mengumpulkan data lembu ternakan melalui analisis imej Google Earth .
pasukan itu asalnya berniat untuk menguji kesan kemungkinan medan magnet manusia dengan mengkaji orientasi beg tidur dalam orang yang berkhemah , tetapi ia terbukti sukar untuk mendapatkan data kerana manusia biasanya tidur di bawah khemah .
lembu lebih mudah untuk diperhatikan , dan 8510 ekor lembu di 308 lokasi menunjukkan kecenderungan yang kuat untuk menyelaraskan orientasi badan mengikut medan magnet bumi .
faktor-faktor lain yang mungkin seperti angin atau arah cahaya matahari tidak memberikan penjelasan yang lebih baik bagi tabiat ini .
untuk membandingkan terhadap spesies kedua besar , Burda dan pasukannya menganalisis data pada 2974 rusa yang dikaji melalui fotografi , pemerhatian langsung , dan tapak kaki di salji .
" saya rasa perkara yang benar-benar menakjubkan adalah apabila pemburu dan gembala dan petani tidak menyedarinya , " kata Burda menurut laporan Radio Awam Negara .
Peter August dari Universiti Rhode Island di Kingston , mengulas : " saya benar-benar kagum dengan keputusan yang konsisten dengan mereka yang terlibat dalam penemuan lembu dan rusa menghadap ke utara . "
masih tiada kajian bebas dapat mengesahkan penemuan pasukan Duisburg-Essen .
ini adalah kajian pertama yang menunjukkan pengesanan medan magnet dalam mamalia besar .
penyelidikan Burda sebelum ini melibatkan tikus , spesies mamalia kecil yang buta di mana tingkah laku menunjukkan adanya kompas magnet dalaman .
menurut laporan oleh Jeremy Hsu di MSNBC , " Kajian sebelum ini menunjukkan bahawa haiwan seperti burung , penyu dan salmon berhijrah menggunakan rasa arah magnet , dan mamalia kecil seperti tikus dan satu spesies kelawar juga mempunyai kompas magnet . "
pergerakan pelajar seluruh Eropah , bermula di ibu negara Austria Vienna , sedang membangun .
ianya bermula pada 28 Oktober 2009 dengan pertemuan dan perbincangan selepas Persidangan Menteri-Menteri Pendidikan dan Kebudayaan Negeri di Jerman pada 15 Oktober .
pada Selasa 17 November - pada ulang tahun ke-70 hari pelajar antarabangsa - mogok pendidikan di seluruh negara di Jerman telah diumumkan .
penceramah daripada pergerakan itu berkata , pelajar mengadu bahawa universiti-universiti kekurangan dana dan kekurangan kakitangan .
bantahan pelajar itu untuk melahirkan kebimbangan ke atas pembaharuan Bologna dan yuran pengajian .
pada hari Rabu 11 November kira-kira 600 pelajar di Universiti Percuma Berlin telah menduduki auditorium yang terbesar dari bangunan pusat kemanusiaan di pinggir bandar Dahlem .
selepas itu tindakan berlaku di Tubingen , Munich dan Basel , masing-masing dengan beratus-ratus peserta .
bangunan Potthoff , dewan kuliah Dresden TU telah diduduki sejak hari Isnin , 9 November .
tindakan juga berlaku di Utrecht , Turin , Rome , Lublin , London dan Birmingham .
dua lelaki telah didakwa dengan memulakan kebakaran di Zaca , kebakaran kedua terbesar dalam sejarah California .
api terus membakar melalui Hutan Negara Los Padres , dan telah memusnahkan sejumlah 240,000 ekar , bermula pada 4 Julai .
bagaimanapun , kebakaran itu kini terkawal , dan dijangka dapat dibendung pada 4 September .
Jose Yesus Cabrera Santa Ynez , 38 , Santiago Iniguez Cervantes Santa Maria , 46 , dan syarikat Rancho La Laguna , majikan kepada ketiga-tiganya , semuanya telah didakwa dengan enam pertuduhan jenayah berkenaan memulakan kebakaran .
tiga daripada dakwaan adalah " menyebabkan kebakaran besar yang menyebabkan kecederaan tubuh badan . "
dua pertuduhan dari hal ini iaitu kemalangan helikopter yang memadamkan kebakaran , dan juga kejadian berasingan apabila seorang ahli bomba ketiga cedera parah ketika melawan api .
tiga lagi pertuduhan adalah menyebabkan kebakaran struktur hutan secara melulu , kecuaian dengan bahan yang mudah terbakar dan kerana tidak mempunyai permit yang diperlukan untuk menggunakan peralatan yang mampu memulakan kebakaran .
kebakaran bermula apabila peralatan digunakan di saluran air yang tersekat memercikkan api .
58 anggota bomba cedera oleh kebakaran ini , walaupun tidak ada kecederaan yang mengancam nyawa direkodkan .
pada masa ini , 1,800 orang terlibat dalam usaha memadam kebakaran , yang telah menelan belanja sebanyak $ 114 juta .
seorang peguam berkata beliau merasakan pertuduhan itu berat apabila melihat keadaan yang berlaku .
" kami mempunyai beberapa lelaki yang bekerja keras yang berusaha untuk menjaga paip air atau lembu ternakan pada hari yang sangat panas pada empat Julai dan mereka mengambil langkah berjaga-jaga dan walaupun langkah berjaga-jaga diamalkan kemalangan tetap berlaku dan kebakaran bermula , " kata Peguam Robert Sanger .
jika sabit kesalahan , mereka boleh menghadapi hukuman sehingga sembilan tahun penjara .
terdapat juga kemungkinan denda dan tindakan untuk membayar ganti rugi kebakaran .
Larry Steven bertanding untuk Parti Libertarian di kawasan mengundi Ontario , di Kitchener-Conestoga .
Nick Moreau dari Wikinews menemu ramah beliau mengenai kualiti , pengalaman dan kempen beliau .
bersedia untuk temu ramah lanjut ; setiap calon daripada setiap parti adalah layak , dan akan dihubungi .
temu ramah dijangkakan dari Liberal , Progressive Conservatives , ahli parti Demokratik Baru , Ontario Greens , dan juga ahli dari gabungan keluarga , Freedom , Komunis , Libertarian dan parti-parti dari Konfederasi serantau , dan juga parti bebas .
untuk menggalakkan peningkatan prestasi atlit pekak , Keahlian Sukan untuk Orang Pekak Antarabangsa ( ICSD ) baru-baru ini mengumumkan 10 finalis terbaik bagi " Anugerah Atlit Lelaki dan Atlit Wanita Widex tahun 2007 . "
menurut icCoventry dari England dan ICSD , Bagga menunjukkan prestasi yang cemerlang dalam perlawanan badminton , tidak pernah kalah perlawanan penting dalam karier antarabangsanya , yang bermula pada tahun 1989 .
beliau dikenali sebagai atlit yang baik ; sentiasa menerima keputusan pengadil , tidak kira ketepatan yang dibuatnya .
dalam Kejohanan Badminton Dunia yang ke-2 baru-baru ini di Jerman , Bagga menawarkan pingat peraknya dalam acara perseorangan selepas berita tragis yang menimpa bekas ahli sepasukannya dari Lithuania , Andirus Jankus meninggal dunia dalam kemalangan jalan raya .
ini menyentuh hati banyak pihak , dari yang pekak dan juga cukup sifat .
atlit wanita terbaik , Deeva , terlibat dalam " Kejohanan Renang Dunia tahun 2007 " di Taiwan dan memecahkan 3 rekod dunia pada hari yang sama .
al-Qaeda menyebut dalam kenyataannya di laman web pada hari khamis bahawa mereka telah membunuh tentera berpangkat tinggi Mesir di Iraq , Ihab al-Sherif .
kumpulan pengganas islam itu menyiarkan video menunjukkan al-Sharif yang ditutup matanya , memperkenalkan dirinya , tetapi kumpulan itu tidak menunjukkan kematiannya .
Presiden Mesir , Hosni Mubarak mengesahkan laporan itu , tetapi tidak menyatakan bagaimana kerajaan boleh menentusahkan dakwaan yang dibuat oleh Al-Qaeda itu .
Encik Al-Sherif , 51 , telah bertugas di Baghdad sebagai ketua angkatan sejak dari awal Julai ; beliau diculik pada 3 Julai ketika membeli surat khabar , menurut saksi .
beliau tidak ditemani boleh mana-mana pengawal keselamatan ketika itu .
selepas cuaca buruk di Mexico dan kemusnahan habitat mereka , populasi rama-rama Monarch ( Danaus plexippus ) akan berkurangan sehingga 50 % ke 60 % tahun ini , menurut pakar .
kawasan berkumpul rama-rama itu yang terletak di barat laut Mexico City itu didorong oleh cuaca yang teruk pada musim sejuk ini , dimana ianya membunuh 50 orang di rantau ini .
menurut Lincoln Browner , pakar monarch dengan Sweet Briar College di Virginia berkata , " hal ini menjadi semakin teruk . "
migrasi ke selatan telah direkodkan sebagai yang terendah dalam sejarah , dan dengan kemusnahan yang disebabkan oleh musim sejuk , lebih separuh dari populasi spesis mungkin telah terbunuh .
" ini bermakna bilangan yang akan ke Texas akan berkurangan " , kata Chip Taylor , seorang profesor entomology dari University of Kansas-Lawrence .
beliau percaya bahawa ianya akan mengambil masa bertahun-tahun bagi Monarch untuk mempopulasi kembali .
Taylor juga berkata " Kita bercakap tentang pengurangan yang ketara di kawasan yang terlebih sejuk ; kehilangan habitat di Amerika Syarikat dan Kanada dan perubahan iklim di Mexico . "
" kita mengalami tiga ribut salji maut pada dekad ini dan kita tidak pernah mengalaminya sebelum ini . "
" kita berhadapan dengan sesuatu yang baru disini , dan ianya konsisten dengan perubahan iklim . "
Pembalakan haram di Mexico dan kekurangan milkweed di tengah barat Amerika Syarikat untuk rama-rama itu bertelur dan juga penyebab kepada populasi Monarch .
penyelidikan yang dikeluarkan oleh Journal Prosiding Akademi Sains Nasional ( PNAS ) mencadangkan hubungan antara seksualiti lelaki dan keadaan di dalam rahim .
penyelidikan awal dari Dr. Anthony F. Bogaert dan rakan sekerjanya di Universiti Brock , Ontario mendedahkan kemungkinan hubungan antara bilangan abang lelaki dan juga kemungkinan ianya menjadi gay homoseksual .
hubungan ini adalah antara semulajadi melalui kesan prenatal rahim atau penjagaan melalui kesan psikososial membesar dengan adik beradik yang lebih tua , masih lagi tidak dapat dijelaskan .
untuk penyelidikan lanjut Bogaert menyelidik 944 lelaki heteroseksual dan homoseksual .
lelaki itu sama ada abang secara " biologi " dan berkongsi ibu atau abang secara " bukan biologi " melalui anak angkat atau adik-beradik tiri .
Bogaert menjelaskan jika hubungan antara homoseksualiti dan abang adalah kerana kesan penjagaan dari persekitaran keluarga , ianya akan ditunjukkan tidak kira adanya hubungan biologi .
namun , penyeidikan ini menunjukkan hubungan itu hanya wujud hanya pada abang kandung .
jumlah individu itu meluangkan masa dibesarkan oleh abang-abangnya tidak mempunyai kesan terhadap orientasi seksualnya ; hubungan itu juga benar dalam abang yang dibesarkan jauh antara satu sama lain .
Bogaert menulis dalam PNAS bulan ini : " keputusan ini menyokong asal pranatal kepada perkembangan orientasi seksual dalam lelaki dan memberi isyarat bahawa kesan kelahiran fraternal mungkin hasil daripada ' memori ' dengan ibu untuk kehamilan atau kelahiran . "
beliau mencadangkan setiap fetus lelaki mengeluarkan reaksi imunisasi yang lebih kuat dalam badan ibunya .
antibodi yang dihasilkan oleh reaksi ini mungkin akan menjadi punca kepada perbezaan seksual dalam otak .
saintis dari Michigan State University menambah dalam artikel : " data ini menguatkan lagi penyataan yang biasa disebut antara adik-beradik abang kandung , ibunya , memberikan persekitaran pranatal yang mendorong homoseksualiti dalam anak lelaki mereka . "
" bukti yang sah semakin meningkat dan dilihat bahawa menjadi lelaki homoseksual ialah sesuatu yang ditentukan oleh genetik dan bukannya pilihan cara hidup . "
" ianya menjadi pengukur kepada persoalan di mana lesbian dan lelaki homoseksual seharusnya diberikan layanan sama rata dalam masyarakat dan tidak didiskriminasi sama seperti mewarisi warna kulit , " kata Andy Forrest , jurucakap kumpulan hak asasi lelaki homoseksual Stonewall .
bagaimanapun , penyelidikan Dr. Bogaert tidak mengulas mengenai asal-usul lesbianisma .
hanya 44.47 peratus pelajar sekolah menengah Romania lulus peperiksaan baccalaureate 2011 pada minggu lepas , menurut keputusan yang dikeluarkan oleh pihak berkuasa pendidikan Romania pada hari Ahad .
baccalaureate exam di Romania ialah ujian kelayakan sekolah menengah , dan lulus ujian itu membolehkan pelajar menamatkan pengajian di sekolah menengah dan mungkin akan dimasukkan ke universiti .
ini adalah perbezaan ketara dari 69.3 peratus tahun lepas dan 81.4 peratus tahun 2009 .
bilangan lulus pada hari Ahad adalah rekod yang paling teruk sejak peperiksaan diperkenalkan di Romania dan ianya selepas langkah-langkah anti-penipuan yang mengurangkan pelajar meniru .
ini termasuklah memasang kamera dalam pusat peperiksaan dan melarang pelajar untuk membayar guru mereka untuk mendapatkan markah yang lebih tinggi .
untuk peperiksaan kali ini , 665 pelajar sekolah memengah ditangkap meniru , dua kali ganda angka dari tahun lepas , dan satu sekolah menengah didapati jawapan peperiksaan telah diberikan kepada 111 murid sebelum peperiksaan bermula .
Caras Severin County mencatatkan jumlah graduan yang paling rendah sebanyak 24.82 peratus layak graduasi , dan Suceava melaporkan ianya mencatatakan angkat tertinggi dengan 65.03 peratus , menurun dari 87.39 peratus pada tahun 2010 .
di Bucharest , kadar adalah 42.03 peratus , jumlah paling rendar sejak revolusi 1989 .
keputusan yang dikeluarkan memulakan perdebatan mengenai kemungkinan sebab penurunan drastik dalam skor , daripada penyertaan dari ibu bapa , kurangnya gaji guru dan pengurangan gaji , kepada kurangnya minat pelajar dan kurang motivasi .
Pengkiritik mengatakan sistem pendidikan bergantung kepada pembelajaran hafalan dan pelajar tidak digalakkan untuk berfikir sendiri .
dalam sidang akhbar pada hari isnin , Menteri pendidikan Daniel Funeriu berkata , " Keputusan ini mencerminkan masyarakat kita . "
" Romania sekarang berada dalam persimpangan ... "
" negara perlu menggalakkan masyarakat yang berusaha lebih daripada mereka yang menipu . "
Cristian Alexandrescu , ketua inspektor pendidikan untuk Bucharest , berkata peperiksaan tidak diambil secara serius oleh pelajar dan hasilnya membuktikan pelajar tidak boleh memiliki diploma tanpa usaha .
" saat kebenaran teah tiba , " Liliana Romanciuc , inspektor sekolah di timur laut Romania , memberitahu Mediafax .
Sky TV mempunyai masalah awal dengan sesetengah penonton tidak dapat menukar ke saluran tertentu .
ia adalah disebabkan oleh isu penyelarasan yang tidak berkenaan dengan masalah satelit .
masalah itu menyebabkan saluran berikut tidak dapat dilihat : Sky Movies , J2 , Cartoon Network , Sky News , saluran filem bayar-setiap-tontonan , saluran radio termasuk ; National Radio , Concert FM dan George FM .
kebanyakan saluran percuma ke udara , bagaimanapun , boleh diikuti , bersama-sama dengan saluran sukan , beberapa saluran itu mengalami gambar berbintik-bintik .
pengarang British James Graham Ballard , yang dikenali sebagai JG Ballard telah meninggal dunia pada usia 78 tahun .
Ballard meninggal dunia pada hari Ahad selepas sekian lama menghidap kanser prostat .
menurut jurucakap , Ballard telah sakit " untuk beberapa tahun " dan ianya adalah " satu kesedihan yang besar " untuk membuat pengumuman kematiannya .
Ballard paling dikenali dengan penulisan novel Crash pada tahun 1973 dan Empire of the Sun pada tahun 1984 yang memenangi Hadiah Memorial James Tait Black .
" beliau telah dibesarkan di Shanghai dan mempunyai adab yang sangat baik . "
" beliau sangat murah hati dan sopan dan ianya mengambil masa yang lama sebelum beliau akan melakukan apa sahaja yang tidak begitu terkawal , " kata rakan penulis dan Iain Sinclair kepada The Times .
Ballard dilahirkan di Shanghai , China di Shanghai International Settlement pada tahun 1930 .
ketika beliau berusia 12 tahun , beliau dan keluarganya terpaksa hidup dalam kem yang dikendalikan oleh tentera Jepun semasa Perang Dunia II .
Ballard berkata bahawa dia tidak akan berkata perkara yang gembira tentang pengalamannya di perkemahan , tetapi juga tidak berkata perkara yang tidak menyenangkan .
dalam temu bual dengan BBC News , Ballard berkata , " Saya ingat banyak kekejaman dan pukul-memukul yang telah berlaku , tetapi pada masa yang sama , kami kanak-kanak bermain banyak permainan sepanjang masa . "
pada tahun 1946 beliau berpindah ke UK dengan kakak dan ibunya di mana beliau mula menulis .
dua puluh tahun kemudian , pada tahun 1960-an , dia yang bekerja sendiri sebagai penulis sepenuh masa .
beliau menghasilkan novel pertama beliau pada tahun 1961 bertajuk The Wind fromNowhere dan The Drowned World hanya setahun kemudian .
kerajaan Ireland merancang untuk menyuntik € 4 bilion ke dalam Bank of Ireland dan Allied Irish Bank .
skim insurans untuk menaja jamin hutang lapuk akan diwujudkan dan bank-bank akan cuba untuk mengumpul € 1 bilion daripada pemegang saham .
kedua-dua bank telah memerlukan permodalan semula untuk beberapa minggu .
perjanjian itu akan menyaksikan kerajaan mengambil sehingga 24 bilion € risiko daripada pinjaman hartanah spekulatif oleh bank .
kerajaan telah pun berpindah memiliknegarakan bank ketiga terbesar di negara ini , Anglo Irish .
India memenangi perlawanan akhir siri kriket baru-baru ini .
Yuvraj Singh membuat rekod tanpa kalah 107 ( 93B , 15x4 ) membantu India , mengejar 287 , dicapai dengan 19 penghantaran masih berada di atas padang dengan pukulan yang baik .
Mahendra Singh Dhoni ( 77 tidak keluar , 56b , 6x4 , 4x6 ) merupakan satu lagi penyumbang penting kepada Innings India .
hantaran Pakistan , selain persembahan dari paceman Rao Iftekar Anjum , telah dibuat kelihatan biasa .
apabila pada 64 , Yuvraj berlaku telah diredakan oleh penutup dari Shoaib Malik .
Tendulkar membawa minuman , mengatakan bahawa kumpulan berpengalaman dan muda india bersatu .
dalam ketiadaan Tendulkar , Rahul Dravid membuka innings dengan Gautam Gambhir .
Gambhir yang kidal bergemerlapan dengan beberapa pukulan ambilan pada sebelah ; ini juga menunjukkan pacemen Pakistan tidak menghantar pada garis yang betul .
Mohammed Asif tidak menjadi faktor besar dalam ODIs sejak penghantaran yang jauh akan adalah senjata yang lebih kecil dalam kepelbagaian permainan , terutama jika pasukan yang sedang bowling pada sebelah petang .
ia adalah pergerakan dua hala beliau yang menjadikan beliau begitu berbahaya dalam Tests .
Gambhir sekali lagi mensia-siakan permulaan , tetapi pasangan pembukaan itu yang penting , membangkitkan 69 .
Dravid ini 50 ( 6x4 ) mungkin telah mengambil 82 penghantaran , tetapi dia memastikan bahawa , dalam ketiadaan Sehwag dan Tendulkar , pasukan India mempunyai wickets yang cukup di tangan sebelum mereka memulakan serangan akhir .
Sreesanthlah yang mematahkan Pakistan pagi itu selepas Zaheer Khan dan Ajit Agarkar kongsi bola baru .
Kerala paceman , yang sedang belajar dengan cepat , mengurangkan kadar kelajuan beliau menyedari bahawa tidak ada terlalu banyak bantuan untuknya daripada wicket .
beliau menyerang tiga kali dan Pakistan , daripada 62 tanpa kalah , merosot kepada 77 selama tiga .
dalam konteks perlawanan , penampilan Sreesanth 5-1-25-3 adalah amat penting .
kedua-dua Imran Farhat dan Kamran Akmal , selepas meletakkan bersama-sama 62 , tidak dapat membuat pukulan , dan Shoaib Malik dikemudikan terus ke dalam tangan Suresh Raina di gully .
terdapat kefasihan tentang penampilan Sreesanth dan tindakan ini sukar untuk diabaikan , dan beliau menghayun bola dengan baik pada masa saat akhir , mengayun bola ke sebelah kanan .
dan di luar pemutar Ramesh Powar memenangi keputusan perlawanan sebelum ini menentang Inzamam dalam hayunan itu ; penghantaran hanyut ke sebelah kanan dari luar luar tunggul dan kemudian diluruskan .
penghantar , disokong oleh pemain agresif , telah menunjukkan prestasi kerja yang baik , di bawah syarat-syarat .
angin kencang dan hujan lebat telah meninggalkan 4 orang mati , dan banyak kawasan Seattle , Washington terputus kuasa elektrik .
beberapa pokok besar telah tumbang dan hujan lebat menyebabkan banjir kecil di kebanyakan kawasan di bandar .
menurut laporan awal sebanyak 1 juta orang dan beberapa pertubuhan besar seperti Microsoft tiada bekalan elektrik pada pagi ini .
banjir , ribut , dan angin yang kuat berlaku malam tadi sebagai satu sistem ribut petir jarang berlaku dimana ianya berpindah ke rantau Pasifik Barat Laut , melibatkan kawasan-kawasan dari Seattle ke Portland dengan angin kencang dan hujan lebat .
Interstate 5 hingga Seattle telah ditutup di persimpangan dengan Mercer Street kerana air yang bertakung .
jambatan terapung State Route 520 , saluran utama di seluruh Lake Washington kepada teknologi yang kaya di Eastside telah ditutup dan drawspannya telah dibuka untuk melindunginya daripada kerosakan ribut sehingga hari Jumaat .
jalan raya tempatan di seluruh rantau ini telah berselerak dengan serpihan , terutama dahan evergreen dan daun .
empat kematian dilaporkan berkaitan dengan ribut pada Jumaat .
seorang wanita di Seattle meninggal dunia di ruangan bawah tanah rumahnya kerana ditenggelami air menyebabkan pintu ruangan bawah tanah itu tertutup rapat .
dua lagi meninggal dunia di kawasan luar selepas dahan tinggi evergreen Northwest jatuh pada kenderaan mereka , dan seorang lelaki di Grays Harbor , berhampiran pantai Pasifik , meninggal dunia dalam tidur selepas pokok jatuh pada rumah bergeraknya .
KOMO berita melaporkan seorang pemanggil mengatakan evergreen setinggi 100 kaki telah jatuh ke dalam rumahnya .
pokok-pokok tumbang dan angin kencang juga merosakkan kuasa elektrik di sepanjang Western Washington .
Seattle City Light , utiliti elektrik perbandaran untuk bandar , melaporkan sebanyak 175,000 pelanggan tanpa kuasa elektrik , sebahagian besar di utara dan hujung selatan bandar , serta pinggir timur bandar dan kawasan Green Lake .
Puget Sound Energy , utiliti elektrik untuk kebanyakkan kawasan metro Seattle , melaporkan 700,000 pelanggan ( lebih 66 % ) tanpa kuasa elektrik , dengan kawasan di sekitar Seattle paling teruk terjejas .
PSE , yang sudah menyenaraikan pekerja tambahan kuasa elektrik daripada negara-negara jiran , tidak menghantar kakitangan keluar sehingga pagi pertengahan Jumaat kerana angin kencang berterusan .
anggaran untuk pemulihan kuasa adalah dari mana-mana sahaja dari beberapa hari hingga lebih seminggu .
Island County , di muara Puget Sound , tidak mempunyai kuasa elektrik sama sekali .
sekolah di Seattle dan di pinggir bandar ditutup pada hari Jumaat , kebanyakkannya disebabkan oleh gangguan kuasa .
bandar Mercer Island , dihubungkan dengan tanah besar hanya dengan Interstate 90 , dilaporkan tidak boleh diakses .
The Seattle Post-Intelligencer gagal untuk mencetak disebabkan oleh kegagalan kuasa di fasiliti percetakan , yang mempunyai suapan kuasa berlebihan dari kedua-dua utiliti Seattle serta PSE .
ini adalah kali pertama dalam 70 tahun bahawa akhbar itu tidak dicetak .
The Seattle Times , satu kertas di bawah perjanjian operasi bersama , boleh mencetak hanya 13,000 salinan edaran biasa yang kini melebihi 200,000 .
akhbar-akhbar itu mengenalpasti fasiliti lain untuk mencetak versi yang dikurangkan daripada edisi Sabtu mereka , dan isu Ahad bersama mereka juga dijangka dikurangkan .
di Lapangan Terbang Sea-Tac , tiga terminal telah ditutup semalaman kerana ribut .
Concourse A dan terminal Selatan Satelit kehilangan kuasa , dan tingkap yang ditiup angin menyebabkan Concourse C juga tutup .
semua terminal kembali dalam keadaan baik pada tengah hari jumaat .
begitu juga , di Oregon , Lapangan Terbang Antarabangsa Portland melaporkan sekurang-kurangnya 40 penerbangan dibatalkan .
di Seattle Boeing Field , angin menterbalikkan pesawat peribadi , berlanggar dengan pesawat lain .
permainan bola sepak The Seattle Seahawks vs San Francisco 49ers telah ditangguhkan 15 minit .
satu pra-permainan kuasa lonjakan sementara mengambil paparan video Qwest Field secara luar talian .
lapangan hijau telah dibelenggu oleh air bertakung , lalu pembesar suara stadium memainkan " Who ' ll Stop The Rain ? " sejurus sebelum sepak mula .
ribut pada hari Khamis malam datang selepas ribut serantau sebelum di Seattle pada awal minggu ini , di mana pokok-pokok jatuh ke jalan raya di beberapa pinggir bandar Seattle , tiang elektirik , dan dua bas sekolah .
dalam kejadian itu tidak ada yang tercedera , dan terdapat beberapa gangguan kuasa elektrik .
ini adalah ribut serius kedua yang melanda Barat Laut sejak hari Kesyukuran , Pada akhir November , rekod penurunan salji yang tertinggi mempunyai kesan melumpuhkan yang sama di rantau ini .
tabloid Britain The Daily Mirror hari ini mencadangkan bahawa pengebom London mungkin tidak merancang untuk membunuh diri , manakala jurucakap Scotland Yard berkata , mereka belum pasti mengesahkan bahawa keempat-empat lelaki bertujuan untuk mati apabila mereka melakukan serangan itu .
Daily Mirror mendakwa bahawa pengebom membeli tiket pulang balik kereta api ke Luton , dan mereka membeli dan memaparkan tiket letak kereta sebelum menaiki kereta api di Stesen Luton .
akhbar tabloid juga menyatakan bagaimana kesemua pengebom mempunyai barang-barang peribadi mereka pada masa serangan , seperti dompet , lesen memandu dan kad bank .
ia juga menyatakan bagaimana mereka membawa beg galas besar yang mudah dibuang , daripada membawa bahan letupan yang diikat pada badan mereka , seperti yang dijangkakan daripada pengebom berani mati .
ia juga menunjukkan bukti daripada keluarga pengebom , di mana dua daripada lelaki itu mempunyai isteri yang mengandung .
daripada bukti ini , akhbar membuat kesimpulan bahawa keempat-empat lelaki tidak diberitahu bom akan meletup serta-merta , dan mereka ini berfikir mereka akan dapat melarikan diri tanpa sebarang kecederaan .
ini mungkin dilakukan untuk melindungi identiti tuan mereka , akhbar-akhbar menjangkakan , kerana terdapat kebarangkalian yang tinggi pengebom akan ditangkap jika mereka masing hidup .
rentetan protes anti-kerajaan di Bangkok semalam menyebabkan sekurang-kurangnya satu kematian , banyak yang lain cedera , dan penutupan sementara beberapa kedutaan asing di Thailand .
Philip Crowley , seorang jurucakap Jabatan Negara Amerika Syarikat , mengumumkan awal pagi Khamis bahawa kedutaan Amerika Syarikat akan ditutup kepada orang ramai kerana lokasinya yang berdekatan dengan keganasan yang tercetus .
kedutaan itu akan beroperasi dengan kakitangan yang dikurangkan dan tidak akan menawarkan perkhidmatan rakyat Amerika sehingga konflik itu diselesaikan .
kedutaan British dan Belanda di Thailand juga menghentikan perkhidmatan mereka selepas kerajaan Thailand berkata ia akan menutup kawasan itu .
pemimpin protes adalah seroang yang diburu iaitu Mejar Jeneral Khattiya Sawasdipol , pemimpin radikal militan pergerakan Baju Merah .
sambil memberikan temu bual dengan wartawan asing , Sawasdipol nampak ditembak di kepala oleh penembak hendap .
dia kemudiannya dibawa ke hospital tempatan untuk rawatan kecemasan .
seorang lagi penunjuk perasaan , Chartchai Bualao , berusia 25 tahun , terbunuh dalam kejadian itu , tetapi ia masih tidak jelas mengenai siapa yang bertanggungjawab menembaknya .
angkatan tentera Thai bergerak dengan cepat untuk menindas penunjuk perasaan sejurus selepas berlakunya tembakan , yang bertujuan untuk melumpuhkan pergerakan pembangkang dan mengawal kawasan di mana mereka telah membuat kurungan mereka sejak awal bulan April .
kerajaan Thailand mengisytiharkan darurat di tujuh belas dari 76 wilayah di negara ini berikutan protes .
kejadian ini merupakan yang terbaru dalam siri keganasan berterusan antara penunjuk perasaan dan kerajaan Thailand .
keganasan itu adalah hasil daripada kepercayaan penunjuk perasaan bahawa Perdana Menteri Thailand , Abhisit Vejjajiva mengambil alih kuasa secara tidak sah dengan sokongan tentera Thai .
berikutan peningkatan siasatan St Stanislaus College di Bathurst , New South Wales , Australia , Wikinews telah mendapat satu kenyataan polis dari mangsa pada tahun 1997 terhadap paderi Brian Joseph Spillane .
dipercayai bahawa detektif Bathurst menubuhkan Strike Force Header selepas menerima aduan daripada seorang bekas pelajar St Stanislaus tahun lepas .
aduan itu disampaikan ke pihak polis selepas dia datang ke Bathurst menyampaikan kertas iklan yang mendokumenkan penyalahgunaan yang didakwa dilakukan di sekolah itu dan menyediakan pautan kepada laman web yang telah dia tubuhkan .
St Stanislaus College menghubungi polis dan meminta mereka untuk menyiasat .
polis menghubungi mangsa itu dan bertanya kepadanya jika dia ingin membuat aduan .
dalam satu kenyataan yang diperolehi oleh Wikinews , orang yang sama mengadu kepada detektif di Kalgoorlie , Australia Barat tentang penderaan yang dilakukan oleh Spillane di St Stanislaus .
dalam satu kenyataan bergrafik , dia menerangkan penyalahgunaan yang bermula selepas permainan poker bersama paderi di pertengahan dakwaan tersebut .
polis Bathurst enggan mengulas ketika dihubungi untuk kenyataan hari ini .
dua peguam tertuduh pengedar dadah Luiz Fernando da Costa ( juga dikenali sebagai Fernando Beira-Mar ) telah ditahan Ahad 14 November di sebuah restoran yang terletak di bandar Rio de Janeiro di Brazil .
mereka dituduh memberi rasuah kepada pegawai polis persekutuan Brazil .
Luiz Fernando da Costa , yang lebih dikenali sebagai Fernando Beira-Mar atau Fernandinho Beira-Mar , ialah salah seorang pengedar dadah terbesar Amerika Latin menurut polis .
Beira-Mar telah ditangkap oleh tentera Colombia pada April 20-21 , 2001 , di sebuah kem FARC yang terletak di hutan berhampiran Colombia dan Venezuela dan kemudian dipindahkan ke Brazil di mana beliau berada di penjara sehingga kini .
Raja Jordan , Raja Abdullah , membubarkan Parlimen negara itu , semalam , selepas separuh daripada tempoh empat tahun penggal , dan beliau mengadakan pilihan raya umum lebih awal , dua tahun lebih awal dari jadual .
kerajaan monarki itu tidak segera memberikan alasan untuk pilihanraya itu ; bagaimanapun , baru-baru ini terdapat laporan menuduh Parlimen mengendalikan undang-undang secara tidak cekap , dan juga mengamalkan rasuah .
Raja memerintahkan perkhidmatan awam untuk mengendalikan pilihan raya baru untuk menggantikan 110 anggota parlimen , walaupun tarikh yang tepat untuk pilihan raya masih belum dinamakan .
pengkritik parlimen telah berkata , pasukan itu tidak betul-betul menangani isu-isu seperti pengangguran dan kemiskinan .
pembangkang , bagaimanapun , menegaskan bahawa parlimen telah dibubarkan supaya kerajaan boleh menggunakan undang-undang darurat untuk meluluskan undang-undang .
Raja Abdullah kini telah membubarkan parlimen sebanyak dua kali sejak beliau berkuasa pada tahun 1999 .
pada kira-kira jam 00 : 26 , pada hari Rabu , 22 Mac , British Columbia feri MV Queen of the North terlanggar batu berhampiran Pulau Gil di Wright Sound , di luar pantai British Columbia , Kanada , 75 dari permulaan perjalanan dijadualkan kapal dari Prince Rupert ke Port Hardy di hujung utara Pulau Vancouver .
kapal itu terlepas perubahan haluan dan tersasar ke luar Pulau Gil .
ia mengambil masa kira-kira sejam untuk feri tenggelam , memberi masa penumpang untuk keluar .
kapal itu membawa 101 penumpang dan anak kapal dan semua tetapi 2 sahaja telah diambil kira .
Mujurlah tindak balas penduduk orang asli kampung memancing berdekatan Hartley Bay , dan CCGs Sir Wiflrid Laurier .
mangsa pantas diambil dari Ratu bot penyelamat Utara dan dibawa ke Hartley Bay dan menaiki kapal pengawal pantai , dan akhirnya kembali ke Prince Rupert menaiki Sir Wilfrid Laurier .
The Queen of the North , ( kira-kira ) 9,000 tan kasar , kapal motor yang dipandu , dibina di Jerman pada tahun 1969 .
Queen of North telah berada di sini 15 jam , feri berjalan 274 batu nautika sejak akhir bulan Mei 1980 .
pada musim panas dan kerja-kerja bantuan , kapal yang lebih kecil , Ratu Prince Rupert juga melakukan perjalanan itu .
bekas menteri tenaga nuklear Rusia Yevgeny Adamov ditahan pada hari Isnin oleh pihak berkuasa Switzerland .
penahanan itu dibuat atas permintaan pegawai A.S. yang mendakwa dia mencuri lebih daripada sembilan juta dolar diperuntukkan oleh Washington untuk membantu meningkatkan keselamatan nuklear Rusia .
Kementerian Keadilan di Switzerland berkata Adamov akan diekstradisi ke Amerika Syarikat .
waran itu membolehkan dia didakwa atas kesalahan mengalihkan wang dari Jabatan Tenaga Amerika Syarikat untuk beberapa syarikat yang dikuasainya .
peguam utama Adamov berkata dia akan berjuang untuk mencabar waran ekstradisi itu dan menyifatkan tuduhan itu " tidak berasas . "
Adamov , yang beberapa kali disiasat bagi urusan kewangan beliau oleh Amerika Syarikat dan juga Rusia , berkata beliau dihukum kerana bantuannya dalam membina loji nuklear di Iran .
Amerika Syarikat kini mempunyai 60 hari untuk mengemukakan permintaan formal , dan selepas itu mahkamah Swiss akan membuat keputusan .
pegawai Swiss berkata ia adalah perkara biasa bagi proses ini untuk mengambil masa beberapa bulan .
peguam Amerika Syarikat Adamov , Larry Breur berkata Adamov mengaku mendepositkan wang ke dalam akaun peribadi , tetapi kemudian dia menggunakan akaun itu untuk mengeluarkan wang itu untuk agensi-agensi Rusia dan ahli-ahli sains nuklear .
Breur berkata proses itu adalah perkara biasa di Rusia untuk mengelakkan percukaian yang berlebihan .
Yevgeny Adamov ialah seorang menteri dalam kerajaan Boris Yeltsin , tetapi telah dibuang dari kuasa oleh Vladimir Putin dalam usaha untuk menghapuskan rasuah .
Adamov berada di Bern mencuba untuk membuka sekatan akaun bank yang dimiliki oleh anak perempuannya .
pemimpin pro-demokrasi Aung San Suu Kyi dari Myanmar didaftarkan semalam sebagai calon dalam pilihan raya kecil Parlimen .
beliau bertanding bagi pihak parti beliau Liga Kebangsaan bagi Demokrasi ( NLD ) , untuk Kawhmu , antara 48 kerusi dalam pilihan raya yang dijadualkan pada bulan April .
Suu Kyi akan bertanding dalam pilihan raya untuk kali pertama .
parti beliau memenangi pilihan raya tahun 1990 , tetapi dia berada di bawah tahanan rumah .
junta tentera tidak menerima kemenangan majoriti NLD dalam pilihan raya itu .
NLD membantah keputusan pilihan raya dan memboikot pilihan raya tahun 2010 .
Kawhmu ialah perbandaran luar bandar di barat Myanmar yang dilanda taufan Nargis pada tahun 2008 .
parti Suu Kyi tidak akan mempunyai banyak kuasa walaupun ia memenangi kesemua 48 kerusi dalam pilihan raya .
walau bagaimanapun , penyertaan beliau boleh menjadi cabaran bagi perubahan demokratik di Myanmar .
The Program Pencegah Hujan Batu Kebangsaan dilancarkan pada tahun 2000 dan dijangka dimuktamadkan pada 2014 .
ia bertujuan untuk melindungi kawasan-kawasan di negara ini yang paling terjejas oleh hujan batu .
projek ini memerlukan pelaburan sebanyak 10.9 juta lei baru ( 3 juta euro ) , separuh daripada yang telah diperuntukkan , menurut penyelaras projek , Stancu Samoila .
Carl-Henric Svanberg , Ketua Pegawai Eksekutif Ericsson , memulakan lawatan ke beberapa kilang di Marconi di Eropah pagi ini , bermula di Coventry dan bergerak ke Beeston untuk sesi petang .
Genoa dan Backnang akan dilawati pada hari Rabu dan Khamis .
Mike Parton , Ketua Pegawai Eksekutif Marconi Corporation , bercakap mengenai ' berita baik ' kepada semua pihak berkepentingan dan memperkenalkan Svanberg yang menerima tepukan gumuruh daripada majoriti kakitangan di New Century Park Coventry , manakala kakitangan lain dari Coventry New Horizon Park mendengar panggilan persidangan .
tujuan lawatan ini adalah untuk berkomunikasi dengan lebih kurang lapan puluh peratus daripada kakitangan Marconi dan membolehkan mereka untuk bertanya soalan mengenai pembelian aset yang dicadangkan oleh Ericsson .
pengembara Belanda Ralph Tuijn telah mencapai separuh percubaanya untuk menjadi orang pertama mendayung merentasi Lautan Pasifik tanpa bantuan .
perjalanan 16,000 kilometer dari pantai Peru ke bandar tepi pantai di Brisbane , Australia , bahagian yang paling luas di Pasifik , tidak pernah dilintasi sama sekali tanpa bantuan oleh pendayung , dan Tuijn berkata hanya sembilan orang telah mengayuh di sana dengan bantuan .
Tuijn telah sampai ke titik tengah persimpangan , sebuah tempat yang tidak ketara di lautan , 111 hari selepas berangkat dari Peru pada bulan Mac .
beliau telah membuat kemajuan yang baik , dan telah mengurangkan anggaran masa beliau tiba di Brisbane selama sebulan .
warga Belanda itu , yang kini dijangka untuk sampai ke destinasi pada 20 Oktober , telah berhubung dengan orang-orang mengikuti pergerakan melalui siaran internet setiap hari dari komputer riba , termasuk isterinya Winnie .
perahu beliau , the Zeeman Challenger , berukuran tujuh meter kapal papan lapis yang direka khas .
Tuijn telah mengatasi pelbagai halangan untuk mencapai titik tengah .
beliau mengalami perhatian yang berterusan dari jerung , yang sering bertembung dengan perahunya dan mengganggu usahanya ketika tidur .
seekor jerung , yang digelar ' Gomulka ' oleh Tuijn , sentiasa di belakang bot pengembara untuk satu tempoh yang lama .
beliau juga tidak sengaja melecur apabila dia tertumpah air panas di kakinya ketika cuba untuk membuat kopi , nampaknya juga berpunca dari ' pertembungan ' dengan jerung .
beliau juga terpaksa secara mempam air dengan manual untuk memasak dan minum selepas pam air automatik beliau rosak tidak lama ketika dalam perjalanannya .
kapal beliau tidak mempunyai motor atau layar , tetapi bergantung kepada kuasa fizikal mendayungnya untuk bergerak .
bot itu tidak mempunyai sistem kuasa solar untuk membekalkan tenaga untuk komputer riba , telefon dan sistem kedudukan global .
Tujin , yang mengumpul wang untuk rumah kanak-kanak di Mumbai , India , mendayung pada kelajuan purata 58 kilometer setiap hari .
Dietnya terdiri daripada makanan dan ikan beku kering , yang mengekalkan keadaan fisikal dengan baik walaupun kepenatan dari segi mental .
beliau telah mendayung merentasi Lautan Atlantik dan Laut Utara , dan juga telah merentas seluruh Rusia dan kawasan berais Greenland .
Presiden Rusia Dmiry Medvedev mengikut presiden Georgia , Mikheil Saakashivili dan telah menandatangani perjanjian gencatan senjata pada hari Sabtu .
dokumen pelan keamanan pada asalnya telah digubal oleh Nicolas Sarkozy , Presiden Perancis .
Medvedev mengumumkan di mesyuarat Majlis Keselamatan Russia bahawa beliau telah menandatangani dokumen tersebut .
genjatan senjata telah ditandatangani oleh Saakashvili pada Jumaat , selepas mesyuarat dengan Setiausaha US di Negeri Condoleezza Rice .
sejurus selepas mesyuarat , sidang akbar telah diadakan di mana Saakashvili menyatakan bahawa beliau telah menandatangani perjanjian tersebut .
tetapi beliau menegaskan bahawa " ini bukanlah sepenuhnya perjanjian . "
" kita perlu melakukan yang sebaik mungkin untuk menghalang tindakan seperti itu di masa hadapan . "
dengan menandatangani perjanjian tersebut , kedua-dua belah pihak bersetuju untuk menarik semula tentera mereka dari kedudukan pra-konflik .
perjanjian itu membenarkan beberapa konsesi kepada kedua-dua Georgia dan Rusia .
pada awalnya Medvedev memberitahu bahawa beliau telah mengarahkan tentera Russia supaya mula meninggalkan Georgia pada 11 Ogos .
walau bagaimanapun , menteri luar Rusia Sergei Lavrov eggan meletakkan tempoh waktu bagi pengunduran tentera Rusia dari kawasan pedalaman Georgia dan menyatakan bahawa perlepasan mereka bergantung kepada ukuran keselamatan tambahan yang diletakkan di tempat itu .
Lavrov juga berkata Rusia akan menguatkan kontijennya di Ossetia Selatan .
dalam surat kepada Saakashivili , Nicolas Sarkozy mengesahkan bahawa mengikut kepada pelan keamanan yang ditandatangani , tentera Rusia mesti berundur dari semua bandar-bandar besar Georgia tanpa mengira " ukuran keselamatan tambahan " yang dinyatakan di dalam dokumen .
mengikut kepada Sarkozy , ukuran tambahan itu merujuk kepada kawasan sempadan sahaja .
pada masa yang sama menteri hubungan dalaman Georgia melaporkan bahawa tentera Rusia mengubah sempadan pentadbiran di Abkhazia , dan menawan satu daripada kawasan pelan janakuasa Georgia .
ia juga melaporkan bahawa tentera Rusia telah memusnahkan jambatan kereta api strategik Georgia di Kaspi .
mengikut kepada Lavrov , dokumen yang ditandatangani Saakashvili berlainan daripada yang telah ditandatangani oleh Medvedev , yang kurang di bahagian pengenalannya .
Jugal Kishore Raibir , Presiden Samajawadi Jana Parishad ( Majilis Para Sosialis ) meninggal dunia di Hospital Sadar di Jalpaiguri , Bengal Barat pada Selasa 6 November , 2007 selepas tiga bulan bertarung dengan kanser .
upacara pengebumian Raibir , yang mana merupakan Aktivis sosial terkemuka telah diadakan pada petang Rabu .
menyatakan rasa turut berduka cita atas kematiannya Gabenor Bengal Barat Gopal Krishna Gandhi berkata beliau telah menumpukan kepada punca yang tidak ada .
pemimpin-pemimpin dan personaliti-personaliti dari lain-lain bahagian di negara itu , termasuk ketua Narmada Bachao Andolan , Medha Patkar , menunjukkan rasa hiba atas kematian tersebut .
ribuan orang berkumpul di Pusat Samatha , kawasan kediaman Kishore , yang sangat terkenal terutamanya di kalangan petani-petani dan pekerja-pekerja ladang teh .
ketua-ketua dari serata spektra politik memberi penghormatan yang tinggi kepada Jugal Kishore Raibir .
ketua Sosialis Kanan seperti Vinod Prasad Singh , Yogendra Yadav , Shivapoojan Singh , Somnath Tripathi , Viswanath Bagi dan ribuan orang melawat Pusat Samatha untuk memberi penghormatan .
dua penentang di Amerika Syarikat yang terlibat dengan ' Pengepungan Pasir Tar ' telah ditahan pada Isnin selepas mereka meyekat mereka sendiri di sebahagian Talian Paip Minyak Keystone yang berada di bawah pembinaan di Winona , Texas .
pemilik talian paip , TransCanada , telah menghentikan pembinaan sebaik sahaja penunjuk perasaan bermula .
" TransCanada Corporation tidak kisah untuk bertanya kepada mereka di kawasan berhampiran samada mereka mahu berbilion galon pasir tar dipam melalui laman mereka , " kata seorang daripada penentang yang berada di dalam talian paip , Matt Almonte dalam kenyataan yang diletakkan di laman web milik kumpulan tersebut .
" Syarikat multinasional telah membuli para pemilik tanah dan merampas rumah-rumah untuk mengaut keuntungan " , tambah Almonte .
Glen Collins , penentang kedua berkata , " Saya menyekat paip ini dengan Kepungan Pasir Tar hari ini untuk menyatakan dengan lebih lantang dan membersihkan industri pengekstrakan yang mana komuniti kita dan merupakan sumber-sumber yang kita bergantung untuk terus hidup tidak musnah tercagar . "
mengikut kepada laman web mereka , www.tarsandsblockade.org , Almonte dan Collins memasuki talian paip itu awal iaitu lebih kurang 7 : 30 a.m. waktu tempatan .
mereka pergi 25 kaki ke dalam talian paip dan mengambil bersama mereka dua tong berisi simen , yang mana beratnya ialah 600 pounds setiap satu dan mengunci diri mereka di antara keduanya .
pada lebih kurang tengah hari , polis memasuki kawasan paip , hanya keluar beberapa minit kemudian tanpa penunjuk perasaan tersebut .
pada 12 : 30 , selepas ambulans tiba di lokasi , polis sekali lagi memasuki paip dan mula untuk menarik satu daripada tong .
mereka berjaya mengalihkan dan kedua-dua Almonte dan Collins telah ditahan .
tidak lama kemudian , penentang ketiga , yang dikenali sebagai Isabel Indigo Brooks , juga telah ditahan .
dalam kenyataan kepada Wikinews , jurucakap kepada TransCanada , Grady Semmens menggelar kejadian itu sebagai suatu yang " amat dikesali " berkata , " Projek ini adalah untuk membekalkan warga Kanada dan Amerika minyak kepada kilang penapis U.S. , menolak minyak mentah dengan harga yang lebih tinggi daripada rejim luar yang tidak menyokong nilai kebebasan dan pemikiran Amerika - Libya , Venezuela dan Timur Tengah . "
" ia sangat tidak bernasib baik kerana penunjuk perasaan cuba untuk menghalang ribuan warga Amerika daripada kerja-kerja mereka bergantung untuk menampung keluarga mereka . "
" projek ini sangat penting bukan sahaja kepada ribuan pekerja-pekerja tersebut tetapi juga kepada warga Amerika secara umumnya , " tambah Semmens .
kerja pembinaan di bahagian-bahagian talian paip telah dihentikan pada Januari apabila Rumah Putih memberhentikan permit-permit untuknya disiapkan .
" pengumuman ini bukanlah bersifat penilaian ke atas kesan baik talian paip , tetapi bersifat sewenang-wenangnya yang menghalang Jabatan Negara daripada mengumpul maklumat-maklumat yang diperlukan untuk membenarkan projek tersebut dan melindungi rakyat Amerika , " kata Presiden Barack Obama pada Januari .
bahagian talian paip yang terkesan oleh ppenunjuk perasaan ialah sebahagian daripada ' Projek Talian Paip Pantai Gulf ' yang berukuran lebih kurang 485 miles panjang dan mempunyai " 36-inch talian paip minyak mentah yang bermula di Cushing , Oklahoma dan menganjur ke selatan Nederland , Texas " , kata TransCanada di laman web mereka .
arkitek British , Norman Foster dan presiden FC Barcelona , Joan Laporta hari ni membentangkan di Barcelona mengenai projek pembangunan semula stadium pasukan tersebut , Camp Nou , yang telah dibina pada tahun 1957 .
kelab Catalan menjangkakan perekaan semula bentuk akan menjadikan stadium itu sebagai mercu tanda bandar dan " imej luaran stadium itu akan menjadi jenama yang dikenali bagi FCB . "
Stadium baru akan dikenakan dengan mozaik berwarna-warni mengikut warna tema pasukan itu ( biru dan merah ) dan warna bendera Catalan ( merah dan kuning ) dan yang serupa kepada gaya Gaudi .
jubin penutup seperti reptilia dan lampu-lampu akan membolehkan stadium itu diubah mengikut masa dan acara yang yang dijalankan .
projek itu juga melibatkan pembinaan bumbung yang boleh ditarik balik .
mengikut kepada Kelab , " pengubahsuaian stadium itu direka sebegitu supaya ia dapat dibina dengan gannguan yang minimum kepada aktiviti normal FCB . "
ribut besar pertama yang melanda Amerika Syarikat pada musim sejuk telah menyebabkan banyak kawasan di New England diselaputi salji .
keadaan tegang dari Virginia ke Maine , ribut , membawa angin berkelajuan lebih daripada 50 batu sejam ( 80.5 kilometer sejam ) , menyebabkan salji lebih dari dua kaki di beberapa kawasan .
penduduk bersedia menghadapi nor ' easters terburuk dalam tempoh beberapa ketika .
ribut mempunyai syarat-syarat yang sama kepada ribut taufan katogeri 2 .
Wellfleet , Massachusetts melihat tiupan angin kencang berkelajuan 80 batu sejam , merupakan yang terkuat direkod dalam ribut ini .
Connecticut , New York dan Maine semuanya merekodkan tiupan angin kencang melebihi 60 batu sejam dan tiupan angin melebihi 70 batu sejam melanda Cape Cod .
keseluruhan dengan jumlah 32 inci ( 81.3 sentimeter ) turun di Rahway , merupakan antara negeri yang paling kuat dilanda ribut .
kebanyakan bandar-bandar di New Jersey menerima salji lebih dari satu kaki , sementara Connecticut , Delaware , Mine , dan Maryland semuanya menerima salji melitupi lebih kurang 1 kaki ( 30.48 sentimeter ) dengan Massachusetts dilitupi setinggi satu kaki setengah .
pada Isnin , kesukaran dalam perjalanan dilihat , dengan penerbangan dari Philadelphia , Newark , New York City , Hartford , Boston , Portland , dan Washington , D.C. telah dibatalkan .
Pemandu-pemandu juga menghadapi masalah di lebuhraya-lebuhraya besar di mana kemalangan tidak dapat dielakkan di atas jalan yang licin .
media Jepun melaporkan bahawa Perdana Menteri Junichiro Koizumi semalam mencadangkan bahawa kerajaan akan menyerahkan draf kepada Diet untuk menulis semula Akta Rumah Diraja dalam tahun hadapan .
ini merupakan tindakan kepada lembaga pakar-pakar yang menyiasat isu perwarisan .
lembaga pakar-pakar di Akta Rumah Diraja , sendirinya telah melantik Perdana Menteri , mencapai kepada persetujuan mengenai isu di mana Maharani perlu diterima .
Implimentasi kepada cadangan mereka yang mana perwarisan kepada jawatan tertinggi dalam masyarakat Jepun perlu dijalankan tanpa kecenderungan jantina .
pada masa kini , rumah diraja Jepun tidak mempunya ahli lelaki di bawah usia 20 tahun ; undang-undang sekarang hanya membenarkan keturunan lelaki untuk mewarisi Chrysanthemum Throne .
penyelesaian yang dicadangkan akan meletakkan Puteri Aiko , anak tunggal kepada Putera Mahkota Masako di tempat yang mana paling berkemungkinan untuk mewarisi kedudukan monarki , mengikuti di belakangnya adalah Puteri Sayako yang akan meninggalkan Rumah Diraja kerana plannya untuk mengahwini orang biasa .
undang-undang di Jepun hari ini meletakkan pewaris adalah memihak kepada anak lelaki ; kali terakhir negara mempunyai Maharani adalah pada tahun 1771 , apabila Maharani Go-Sakuramachi menuruni takhta untuk anak saudaranya .
walaupun fakta bahawa terdapat duluan bagi sorang Maharani , beberapa sarjana telah mencadangkan ahli keluarga yang mana sebelum ini telah memutuskan hubungan dengan keluarga diraja yang dikenali itu selepas berakhirnya Perang Dunia II perlu menimbang semula perwarisan , membuka peluang untuk lebih ramai sebagai calon .
kumpulan sarjana mencadangkan penyelesaian ini menekankan bahawa penyelesaian mereka adalah bermatlamat untuk mengekalkan tradisi pewaris lelaki .
selepas gempa bumi bermagnitud 8.9 yang melanda pada Jumaat lalu , diikuti oleh tsunami , Naoto Kan , perdana menteri Jepun mendakwa bahawa negara berdepan dengan masalah terbesar selepas berakhirnya Perang Dunia II pada tahun tahun 1945 .
Kan melaporkan bahawa bekalan elektrik yang ada adalah terhad akibat daripada penutupan beberapa stesyen tenaga , termasuklah plan tenaga nuklear yang terletak di Wilayah Fukushima .
mengikut kepada NHK , organisasi penyiaran di Jepun , lebih kurang 310,000 individu telah pun selamat dipindahkan ke pusat perlindungan yang , berada dalam pelbagai keadaan , tanpa bekalan elektrik .
kerajaan Jepun telah melaporkan kematian seribu individu , walau bagaimanapun terdapat ribuan yang lain masih belum termasuk dalam kiraan .
polis mendakwa bahawa jumlah kematian di Wilayah Miyagi kesan daripada gempa bumi dan tsunami mampu mencecah kepada puluhan ribu .
100,000 tentera - yang mana bersamaan dengan hampir 40 % daripada angkatan tentera negara - dikatakan sangat komited untuk membantu mereka yang terselamat daripada bencana tersebut .
agensi nuklear Jepun mempertimbangkan keadaan di Plan Tenaga Nuklear Fukushima I berada di Aras 4 pada Skala Acara Nuklear Antarabangsa , yang mana merupakan bencana kepada penduduk tempatan .
mengikut kepada Berita Dalam Talian BBC , kejadian seperti ini biasanya menyebabkan kematian satu orang disebabkan oleh kesan radiasi .
tiada individu dari pelan tenaga dilaporkan meninggal dunia .
di NHL Buffalo Sabres mengalahkan New York Islanders 3-0 dalam permainan pada Khamis malam mengikat rekod NHL bagi permulaan yang baik dalam musim ini .
" saya fikir kami semua bangga dengan apa yang dicapai setakat ini . "
" tetapi di akhir nanti , ia bukanlah apa yang kami sasarkan bagi menuruni jalan ini , " kata Daniel Briere , pembantu kapten bagi Sabres .
" kami mahu untuk memiliki pecutan seperti ini di dalam perlawanan penetapan . "
" saya fikir ia akan membantu kami di masa hadapan , tetapi buat masa ini kami hanya perlu mata , " kata Ryan Miller , seorang daripada penjaga gol Sabres .
buat masa ini , Buffalo dengan 10-0-0 dan kini berada di tangga tertinggi dalam NHL .
mereka akan bermain dengan Atlanta Thrashers , yang ketinggalan hanya 3 mata di belakang Sabres dalam NHL secara keseluruhan , pada Sabtu , 28 Oktober .
bermula di pengakhiran musim lalu , Sabres telah menang 15 permainan berturut-turut .
wakil Rumah A.S. meluluskan pembinaan 700 batu pagar dua tingkat antara A.S. dan Mexico tengahari ini , ia merupakan kali kedua tahun ini di mana isu itu sebelum ini di kongres dan rang undang-undang itu lulus dengan 238-138 undi .
sempadan panjang sepanjang 2000 batu kini mempunyai pagar sepanjang 75 batu .
rang undang-undang itu juga mengarahkan Jabatan Keselamatan Tanah Air A.S. untuk mengambil alih kawalan sempadan dalam masa 18 bulan dan menjanjikan kuasa ejen sempadan baru bagi menghentikan melarikan kenderaan .
ia juga mengarahkan Setiausaha Keselamatan Tanah Air , Michael Chertoff untuk menjalankan kajian ke atas keperluan dan keboleh laksanaan kerja pembinaan untuk " sistem penghadang seni antara negara " di sepanjang sempadan Kanada .
harga minyak mencapai tahap tertinggi bagi tempoh enam bulan pada Jumaat , merupakan tanda baru di mana ekonomi A.S. mungkin tidak akan pulih secepat yang dipercayai .
harga minyak mentah A.S. mencapai US $ 66.47 setong , aras yang tidak pernah dilihat sejak November lalu .
minyak mentah Laut Utara Brent telah meningkat dari $ 1.13 ke $ 65.52 pada akhir minggu lalu , selepas mencapai kemuncaknya pada $ 65.70 , juga merupakan aras tertinggi sejak November lalu .
ini hadir selepas laporan dikeluarkan oleh Jabatan Kewangan A.S. yang menunjukkan bahawa GDP A.S. jatuh sebanyak 5.7 % , selepas semakan semula dari kiraan asalnya pada 6.1 % .
analisis menjangkakan bahawa harga minyak akan terus meningkat di tengah-tengah kebanyakan berita positif ekonomi , terutama dari kuasa besar ekonomi seperti India dan Jepun .
" konklusi para peserta di pasaran minyak bahawa ia adalah merupakan yang terburuk dalam kemelesetan ekonomi lalu dan keperluan kepada pemulihan mesti berada di tangan yang disokong lebih tinggi daripada pertumbuhan suku pertama yang dijangkakan di India dan lompatan tajam dalam industri produksi pada April di Japan , " kata John Kilduff dari MF Globa .
" kami telah mendapat lebih banyak optimisme mengenai tinjauan ekonomi dari apa yang telah kami lakukan . "
" pasaran ialah pemfaktoran dalam keperluan kepada pemulihan di akhir tahun , " kata analisis bagi Komoditi Waran Australia , Toby Hassall .
Sunday Times memetik sumber tidak bernama kerajaan U.K. berkata bahawa tentera Britain boleh meninggalkan Basra seawal bulan Oktober .
senario didakwa akan membolehkan Gordon Brown untuk mengumumkan pengunduran tentera dalam kenyataannya pada masa kepulangan MPs ke Parlimen .
spekulasi telah menyemarakkan ktitikan daripada komentator tentera A.S. pada hujung minggu ini .
Jeneral Jack Keane berkata pengunduran ini " banyak terlibat dengan syarat-syarat di U.K. " daripada keadaan di Iraq .
Frederick Kagan , di Institut Perusahaan Amerika , berkata pengunduran itu dijangakakan " menandakan perbezaan yang makin jelas antara pendekatan British dan Amerika . "
baru semalam , bekas Jeneral Sir Mike Jackson menggelar pendekatan Donald Rumsfeld kepada keberadaan A.S. di Iraq sebagai " intelektual muflis . "
kenyataan rasmi dari Menteri Pertahanan Britain berkata bahawa keputusan mengenai jumlah tentera di Selatan Iraq akan mengambil kira kedudukan kerajaan Iraq dan A.S.
Menteri berkata bahawa walaupun selepas " pasukan keselamatan kompeten Iraq " akan menggantikan mereka , sebahagian tentera akan terus kekal di Basra .
sehingga kini , Gordon Brown tetap untuk menolak menetapkan tempoh masa bagi pengunduran tersebut .
rumah atas bekas Kyrgyz parlimen mengisytiharkan ia menghentikan kerjanya " untuk menstabilkan keadaan dan menghapuskan konflik " pada hari Selasa , seperti mana rumah bawah telah melakukannya sehari sebelum itu .
keputusan itu telah ditandatangani oleh 32 daripada 45 timbalan .
" kami fikir kami telah memenuhi tugasan kami , seboleh mungkin , lebih-lebih lagi dalam tempoh percubaan seperti ini , " kata mereka .
" bahagian besar daripada sistem negeri menumpukan kepada proses pilihanraya . "
" ini bukan rahsia ... "
" kami telah melihat semua yang berlaku apabila eksekutif cawangan terlibat dalam pilihanraya . "
" saya fikir kita tidak akan dapat masuk kepada itu buat masa ini ... "
" saya fikir kakitangan patut kembali kepada kerja mereka , " kata beliau .
" siapa pun ... kepada semua staf saya , jika saya mendengar bahawa ada antara mereka mendapat promosi untuk duit atau kerana ada terdapat saudara kepada seseorang , atau mereka merupakan sebahagian daripada kaum kerabat , mereka akan dibuang serta merta , " tambah beliau .
" kami akan menyediakan talian umum supaya orang boleh membuat aduan mengenai pengamalan rasuah , " beritahu beliau kepada mereka .
pada masa yang sama , penyokong presiden yang digulingkan Askar Akayev berkata mereka akan membentuk parti dan menjadi calon dalam pilihan raya presiden .
Menteri kecemasan yang digulingkan , Timirbek Akmataliyev dan menteri dalam negeri Keshenbek Dyushenbayev berkata bahawa mereka membentuk Akyikat ( Keadilan ) parti politik .
lelaki di Rotorua hari ini telah ditembak selepas terlibat dalam kemalangan di luar Stadium Internasional Rotorua .
saksi berkata bahawa seorang lelaki telah mengeluarkan pistol dan menembak seorang yang lain di kepala .
saksi Alby King berkata " Saya cuma mendengar kemalangan kereta besar ini , dan ada dua orang yang bergaduh , dan seorang daripadanya menembak seorang yang lain di belakang kepala . "
lelaki , yang ditembak , terselamat dari tembakan tersebut dan berada dalam keadaan yang serius tetapi stabil di hospital .
polis berkata bahawa mereka telah menahan lelaki yang berusia 38 tahun yang mana berkait dengan penembakan tersebut , dia ditemui di jalan berhampiran selepas melarikan diri dari tempat kejadian .
polis tidak akan mengeluarkan komen mengenai samada ia adalah kejadian yang melibatkan kumpulan .
menjelang pilihanraya umum pada 7 September , kedua-dua pemimpin memfokuskan kepada polisi pelarian dengan Abbott menyerang Rudd kerana gagal mempertahankan sempadan negara secara efektif dengan pembubaran perjanjian pertahanan sempadan yang diimplimasi oleh kerajaan Liberal yang lepas .
" disebabkan Mr. Rudd telah memberhentikan semuanya kita telah menerima lebih dari 50,000 kedatangan yang menyalahi undang-undang , " dakwa Abbott .
" terdapat lebih dari 800 bot , 11 bilion dolar yang dalam belanjawan hilang dan dengan tragiknya , lebih dari 1000 mati di laut . "
Rudd mendakwa bahawa polisi yang diketengahkan beliau mempunyai " satu prinsip mudah " di belakangnya : " jika kamu penyuludup membawa seseorang untuk Australia dan kamu mahu menempatkan mereka di Australia , kami tidak akan membenarkannya . "
" mereka akan dihantar untuk tindakan pemprosesan di Papua New Guinea . "
Rudd juga telah berdebat untuk mengambil pendirian tegas di atas isu perkahwinan sama jantina .
berikrar bahawa tuntutan untuk membenarkan kepada perkahwinan sama jantina akan diperkenalkan dalam tempoh 100 hari bekerja , Rudd berjanji akan membenarkan " undi suara penuh " jika beliau dipilih sekali lagi .
Rudd memanggil pembangkang untuk melakukan perkara yang sama , menyatakannya sebagai " tanda kesopanan " dan menyatakan bahawa " rakyat di luar sana yang mahukan ini terjadi . "
Abbot , walaubagaimanapun , setuju bahawa di ketika perkahwinan sama jantina merupakan " isu yang penting , " ekonomi merupakan isu yang lebih besar .
Nine Network telah mengumumkan kematian salah seorang daripada lelaki terkaya Australia , Key Packer , pada usia 68 tahun .
juruhebah Richard Wilkins berkata di Today Show bahawa dia baru sahaja diserahkan pengesahan rasmi mengenai kematian Mr Packer di usia 68 .
dia menyebut kenyataan daripada Tony Ritchie , ketua berita Nine , yang berkata : " Mrs Kerry Packer dan anaknya James dan Gretel dengan sedihnya telah melaporkan kematian suaminya dan ayah mereka Kerry pada petang tadi . "
" beliau meninggal dengan tenang di rumahnya bersama keluarganya di sisi katil . "
Packer merupakan pemegang stok saham terbesar dalam Publishing and Broadcasting Limited ( PBL ) yang mana memiliki siaran televisyen Nine dan Akbar Gabungan Australia , produser kepada kebanyakan majalah-majalah Australia dan New Zealand .
Packer juga terlibat dalam industri perjudian dan pelancongan dan memiliki Crown Casino di Melbourne .
pada 1970s , Kriket Siri Dunia miliknya telah merevolusi kriket , membawa kriket Sehari ke hadapan dengan memperkenalkan perkara-perkara seperti pakaian seragam berwarna , bola putih & perlawanan siang / malam .
majalah Business Review Weekly menjangkakan harta bersih Packer berjumlah AU $ 6.5 bilion pada tahun 2004 .
hartawan media kaya terkemuka Australia lain , yang mana mungkin telah hilang kerakyatan Australianya , ialah Rupert Murdoch .
Amanah Vornado Realty di Paramus NJ telah melengkapkan perjanjian untuk mengambil faedah majoriti pada 1.8 milion kaki persegi bangunan di 555 California di San Francisco , ( juga dikenali sebagai The Bank of America Center ) dan 2 milion kaki persegi bangunan di 1290 Aveneue of The Americas di New York City .
dalam pengumuman perjanjian bernilai $ 1.8 bilion , pelabur baru mendapat 70 peratus faedah di kedua-dua menara , mengurangkan pemilik-pemilik sekarang , Syarikat Bersekutu Hudson Waterfront dengan segala liabiliti yang mungkin dalam undang-undang dibawa menentang mereka oleh Donald Trump .
dibina pada tahun 1969 , 555 California merupakan menara pejabat terbesar SF dan bangunan ke2 tertinggi dengan ketinggian 779 kaki ketinggalan beberapa kaki daripada Piramid Transamerica 48 tingkat dengan ketinggian 853 kaki yang siap dibina pada tahun 1972 .
struktur SF , di mana perjanjian sekarang menjangkakan nilainya pada $ 575 per kaki persegi , telah pun dijual pada tahun lepas untuk $ 1.05 dengan sendirinya ( $ 583 satu kaki persegi ) , apabila hartawan harta Walter Shorenstein menjualnya kepada Henry Cheng dan Vincent Lo ' s Hong Kong berdasarkan Syarikat Bersekutu Hudson Waterson , rekod bagi harta bandar .
sebelum tahun 2005 , 555 California pernah menjadi HQ Bank of America ' s World , tetapi status itu berakhir apabila NationsBank yang berpusat di Carolina Utara bergabung dengan legasi perbankan pantai barat A.P Giannini dan mengekalkan nama B kepada A , tetapi meletakkan HQ utamanya di Charlotte NC .
bagi Iooke Ioos di tingkat ke-52 555 California dilengkapi Carnelian Room terkemuka , pergantungan baik bagi pengurus-pengurus bank , broker-broker , peguam-peguam dan pelancong-pelancong untuk memeriksa keluar pemandangan luas dari apa yang sebelum ini merupakan struktur barat tertinggi bagi Mississippi , yang kini hanyalah Bangunan Ke-5 Tertinggi di pantai barat , tetapi masih lagi mengagumkan .
bagi mereka yang takut dengan ketinggian dan tab bagi " tempat makan yang baik , " aras bawah juga dilengkapi Starbucks .
sekurang-kurangnya seorang wanita cedera selepas bom surat meletop dalam bangunan Capita Group Plc di Jalan Victoria , berhampiran Scotland Yard yang terletak di bahagian pusat London , England .
wanita itu memegang bom tersebut ketika ianya meletop dan mengalami kecederaan di perut dan tangannya .
" kami telah dihubungi di sekitar jam 9.40 pagi ini untuk melaporkan pakej suspek di alamat perniagaan di Jalan Victoria , " kata jurucakap bagi Scotland Yard .
jalan Victoria telah pun ditutup dari Westminster Abbey ke Scotland Yard sementara para penyelamat dan polis menyiasat kejadian tersebut .
" sebagai langkah berjaga-jaga , kepungan telahpun diletakkan di tempat sekitar kejadian , " kata jurucakap polis yang lain .
bom berada di dalam " jiffy bag " yang mengandungi surat yang terletak di dalam sampul surat yang diletakkan pad .
wanita yang cedera tersebut tidak dipercayai menjadi sasaran .
polis tidak akan memberitahu kepada siapa surat itu ditujukan .
tiada kecederaan atau kematian lain dilaporkan setakat ini .
" di peringkat ini , kami bukan dalam kedudukan untuk berbincang siapa yang mungkin bertanggungjawab ataupun tidak , " kata polis .
Presiden Xanana Gusmao mengambil kuasa keselamatan istimewa dalam usaha untuk memadamkan keganasan amuk di Timor Timur .
dalam tempoh pemerintahan darurat , yang mana akan kekal selama 30 hari , dikenakan untuk " menghalang keganasan dan mengelakkan lebih banyak kematian " dan membawa kepada " penubuhan semula segera ketenteraman awam . "
sekurang-kurangnya 27 orang telah terbunuh , dokumen-dokumen laporan jenayah telah dicuri , dan rompakan berleluasa di pusat Timorese Timur , Dili ketika tempoh masa pergolakan sekarang .
komander tentera Australia di Timor Timur , Brigadier Michael Slater telah memanggil para perusuh sebagai " samseng tidak berisi perut . "
Mr Alkatiri tidak dapat menghentikan rusuhan berikutan keputusan kerajaan pada Mac lalu untuk memberhentikan 600 tentera apabila mereka menolak untuk bekerja , mengadu mengenai pendiskriminasian .
gangguan merebak pada April dan May , Timor Timur ke hadapan bagi merayu untuk bantuan antarabangsa .
Menteri Kehakiman Domingos Sarmento berkata bahawa Portugal telah menawarkan untuk membekalkan Timor Timur dengan 120 anggota keselamatan pada hujung minggu ini .
usaha pembersihan sedang dijalankan selepas hujan lebat turun pada hari Jumaat , 4 September yang mengakibatkan banjir besar di utara-timur Scotland .
agensi Perlindungan Alam Sekitar Scotland ( SEPA ) berkata bahawa ramalan kaji cuaca beberapa hari mendatang adalah lebih baik , dengan tiada penurunan hujan berjumlah besar dijangkakan .
lebih 500 rumah terpaksa dipindahkan di Moray selepas Sungai Spey dan Sungai Lossie mula melimpah dari tebingnya .
400 rumah juga dipindahkan di kawasan Elgin dan 50 lagi di Fochabers .
kawasan-kawasan lain yang terjejas termasuk Aberdeen , Dyce , Lossiemouth dan Rothers , di mana 25 rumah terpaksa dipindahkan .
polis Grampian dan Polis Tayside menasihatkan para penduduk untuk tidak memandu melainkan betul-betul perlu .
di beberapa kawasan , hujan mempunyai kadaran untuk sebulan telah turun dalam hanya tempoh selama 24 jam .
hampir 67 milimeter hujan telah turun di Aberdeen - secara kasarnya bersamaan dengan purata hujan yang turun selama sebulan .
di Lossiemouth , hujan yang turun ialah 76.4 milimeter - 15mm lebih daripada purata hujan yang turun setiap bulan .
usaha pembersihan memiliki progres , Ketua eksekutif Majlis Moray Alistair Keddie berkata , " Segalanya adalah mungkin untuk dilakukan untuk melindungi para penduduk . "
walau bagaimanapun , beberapa penduduk di kawasan setempat tidak beberapa pasti akan hal tersebut .
Mary Campbell , 62 dari Fochabers berkata kepada Times Online bahawa dia " menghubungi [ untuk pertolongan ] dari 8pm tetapi tiada orang muncul sehinggalah hampir tengah malam . "
" di sepanjang masa itu air sungai naik dan terus naik . "
" mereka datang dengan bag pasir , tetapi pada masa itu ia sudah terlalu lambat . "
MSP bagi Moray Angus Robertson MP menyatakan , " Paras air adalah lebih tinggi dari yang pernah saya lihatnya sebelum ini dan komuniti-komuniti telah bangkit untuk menyokong orang yang rumah-rumah dan perniagaan-perniagaan mereka ditenggelami air . "
" objektif sekarang ialah untuk semua orang membantu mangsa-mangsa banjir buruk yang melanda Moray bagi beberapa tahun untuk membantu mereka membina semula kehidupan mereka dan mendapatkan semula normaliti secepat yang mungkin . "
" pengajaran penting yang dipelajari dari kehancuran terbaru ini termasuk keperluan agensi-agensi tempatan untuk menggandakan semula usaha mereka untuk mendapatkan perkiraan pencegahan banjir dan mengenal pasti bahawa perubahan iklim hanya akan menyebabkan lebih banyak banjir pada masa hadapan . "
kerajaan New Zealand terpakasa mengambil tindakan disebabkan oleh surat yang telah dihantar kepada Perdana Menteri Helen Clark yang mana mendakwa bahawa penyakit Kaki dan Mulut sengaja disebarkan di Pulau Waiheke .
surat tersebut , yang mana dianggap hanyalah palsu , mampu memberi impak yang besar kepada industri daging New Zealand .
Menteri Pertanian Jim Sutton pergi jauh dengan mengatakan bahawa penggantungan eksport daging dari beberapa negara mungkin betul-betul terjadi .
tempoh pengeraman penyakit kaki dan mulut apabila haiwan-haiwan itu telah dijangkiti , tanda-tandanya akan dapat dilihat dalam masa sepuluh hari .
pada masa itu , pakar-pakar dan doktor haiwan di Kementerian Pertanian dan Perhutanan , yang mendapat banyak pengalaman daripada tercetusnya wabak itu baru-baru ini di United Kingdom , menjalankan pemerhatian intensif ke atas haiwan-haiwan yang dijangkiti di Pulau tersebut .
semua kambing biri-biri dan lembu diperiksa satu demi satu setiap 48 jam .
sementara itu , sekatan ke atas pergerakan ternakan dikenakan , supaya tiada pengeluaran kenyataan mengenai penyakit tersebut , kesannya akan dapat dibendung .
polis sedang menjalankan usaha menjejaki sumber kepada surat itu yang memulakan ketakukan tersebut .
kerajaan Mexico telah memberitahu bahawa Aeromexico Boeing-737 , pesawat 576 dari Cancun , telah dirampas dan selamat mendarat di Lapangan Terbang Antarabangsa Mexico City di Mexico City .
keadaan tersebut berakhir tanpa sebarang kejadian dan semua penumpang dan krew di atas pesawat dapat keluar dengan selamat .
semua perampas telah ditahan selepas pasukan keselamatan Mexico menaiki pesawat tersebut .
kejadian bermula sejurus selepas 1 : 30 p.m. ( CDT ) seorang lelaki mengambil alih kawalan pesawat tersebut dan meminta untuk bercakap dengan Felipe Calderon , presiden Mexico .
perampas berkata bahawa sekiranya kehendaknya tidak dipenuhi , dia akan meletupkan kapal terbang itu .
laporan awal menyatakan bahawa terdapat bahan letupan di atas pesawat , tetapi tiada yang telah dijumpai .
tidak berapa lama kemudian , empat lelaki yang ditahan telah dilepaskan tanpa sebarang dikenakan apa-apa .
pihak berkuasa mengenal pasti perampas tunggal itu adalah Jose Mar Flores , 44 , yang mana dikatakan sebagai kaki botol , penagih dadah , fanatik beragama .
dia mendakwa dia dalam misi untuk memberi amaran kepada Mexico bahawa gempa bumi akan melanda negara itu .
Flores berkata bahawa signifikasi kepada tarikh 9 / 9 / 09 , terbalik kepada 666 , adalah merupakan alasan kenapa dia merampas pesawat tersebut .
laporan mengatakan dia membawa kotak yang diperihalkannya sebagai bom dan akan diletupkan sekiranya permintaannya untuk bercakap dengan Calderon mengenai gempa tersebut tidak dipenuhi .
104 orang berada di atas pesawat , tetapi semua penumpang dan krew di atas pesawat telah pergi dengan selamat .
lapangan terbang terus dibuka sementara pesawat tersebut diuruskan dengan melalui landasan kecemasan .
Calderon berada di hangar presiden di lapangan terbang menunggu untuk berlepas apabila pesawat tersebut mendarat .
Margaret Wilson telah dilantik sebagai Speaker Dewan Rakyat .
beliau menjadi Speaker Dewan perempuan pertama New Zealand .
beliau juga berada di antara jawatan tertinggi dalam pengambilan New Zealand oleh wanita .
kesemua empat Gabenor Jeneral , Perdana Menteri , Ketua Hakim dan Speaker Dewan adalah perempuan .
Clem Simich ( Nasional MP ) menerima 37 dan ACT MP Ken Shirley mendapat lima undi .
jawatan tersebut biasanya dilantik tanpa perlu bertanding , tetapi dua calon lain bangun membankang kepada kurangnya konsultasi oleh Perdana Menteri Helen Clark .
Wilson mengambil alih jawatan itu dari Jonathan Hunt , yang mana meninggalkan jawatan itu untuk menjadi Pesuruhjaya New Zealand di London .
Hunt akan terus menjadi penyokong kerajaan sehingga awal bulan hadapan .
Wilson sebelum ini merupakan Peguam Negara , jawatan yang mana Timbalan Perdana Menteri Dr. Michael Cullen pegang sekarang .
Leslie Feist adalah merupakan artis yang paling berjaya di Anugerah Juno di Calgary , Alberta pada hari Ahad .
single " 1234 " penghibur yang berjaya di peringkat antarabangsa itu memenangi lima katogeri : album Tahun Ini , Pop Album Tahun Ini , Single Tahun Ini , Artis Tahun Ini dan Penulis Lagu Tahun Ini .
kumpulan veteran Blue Rodeo menang dalam tiga katogeri : kumpulan Tahun Ini , Album Alternatif Dewasa Tahun Ini dan Video Tahun Ini .
Fame , Dewan Muzik Canada menambah kumpulan rock veteran Kanada , Triumph kepada roll terhormatnya .
anugerah Kemanusiaan telah dianugerahkan kepada penghibur negara , Paul Brandt sementara Anugerah Pencapaian Istimewa Walt Grealis telah dianugerahkan kepada Citytv dan pengasas MuchMusic , Moses Znaimer .
anugerah Juno bermula pada tahun 1970 , yang mulanya dikenali sebagao Anugerah Daun Emas , dan merupakan penganugerahan tahunan muzik terpenting Kanada .
anugerah ini telah disiarkan di televisyen seluruh negara di Kanada semenjak tahun 1975 .
upacara tahun depan akan diadakan di Vancouver , British Columbia .
keluarga kelasi warga Sepanyol yang ditahan selama lebih dari sebulan merayu kepada kerajaan Sepanyol pada hari Jumaat untuk berunding dengan lanun Somali untuk pembebasan mereka .
penculik telah mengugut untuk membunuh tiga daripada krew bot pukat selepas bertempur dengan tentera Sepanyol .
mereka memanggil kerajaan untuk membebaskan dua Somali yang ditahan di Sepanyol , yang mana disyaki terlibat dalam perampasan Alakrana dan 36 krewnya .
dalam kes Lynn Rival , kapal layar British , penculik-penculik telah menuntut pembebasan mereka .
Ricardo Blach , kapten bot pukat yang mana telah ditahan oleh lanun , memberi amaran kepada saudara-maranya melalui telefon bahawa mereka bercadang untuk membunuh tiga ahli krew-berpindah daripada bot pukat pada Khamis dan kembali pada Jumaat dalam percuban untuk menekan kerajaan Sepanyol-seharusnya tuntutan mereka tidak dipenuhi .
" mereka baru memberitahu bahawa jika dalam tempoh tiga hari tiada perubahan ke atas dua yang ditahan di Sepanyol , mereka akan membunuh tiga yang tersebut dan kemudian tiga yang lain dan lebih ramai lagi , " katanya .
kerajaan Sepanyol telah menetapkan perkara ini , tetapi sanggup untuk menyerahkan mereka kepada negara Afrika , seperti Kenya , seperti yang berlaku pada bulan Mei .
" terdapat isu yang perlu ditentukan oleh mahkamah , " komen Timbalan Perdana Menteri Maria Teresa Ferna ndez de la Vega Sanz kepada wartawan , menambah bahawa bercakap mengenai " topik teknikal yang mana tidak salah di sisi undang-undang adalah sangat rumit " adalah " berisiko . "
Menteri Luar Sepanyol Minguel Angel Moratinos menekankan keperluan untuk bertenang di ketika keadaan tegang untuk penyingkiran dan pemulangan tiga tahanan .
" apa yag dimaksudkan dengan itu ? "
" ia bermaksud kita perlu terus kekal tenang . "
" penculikan merupakan situasi yang rumit , degan tinggi dan rendah , mereka sangat sukar dan penuh stress . "
" tetapi kita kekal berkeyakinan dan tenang , " kata beliau ketika sidang akhbar .
" jika kita kekal tenang dan berkeyakinan saya yakin bahawa semua yang Sepanyol mahukan , apa yang keluarga mereka mahukan , apa yang kerajaan mahukan-tahanan dapat pulang ke rumah mereka dengan selamat dan penculikan berakhir dalam keadaan yang memuaskan . "
keluarga berkata krew yang ditangkap mempunyai " sedikit air minuman dan makanan . "
mereka menghubungi pihak berkuasa Sepanyol supaya " bertindak segera " dan " lakukan apa sahaja yang boleh untuk membawa balik 36 orang nelayan terlibat . "
" kami meminta semua pihak bekerja dalam satu arah " dan memohon bahawa kerajaan Sepanyol memilih " perundingan " berbanding dengan untuk mempertaruhkan nyawa krew yang dalam bahaya secara paksa .
lanun menahan bot pada 2 Oktober , dan meminta AS $ 4 ( € 2.6 ) milion sebagai tebusan sebagai tambahan terhadap pembebasan dua tahanan Somali .
krew terdiri daripada enam belas warga Sepanyol , krew termasuk lapan warga Indonesia dan ahli kepada Ghana , Ivory Coast , Madagascar , Senegal dan Seychelles .
tentera Sepanyol menangkap dua yang disyaki lanun apabila mereka meninggalkan bot tunda melalui bot kecil .
pada Jumaat , setiausaha pertahanan negeri Sepanyol , Constantino Mendez , berkeras bahawa pembebasan mereka " tidak dapat dirundingkan . "
beliau mengumumkan di Radio Nasional Sepanyol bahawa tahanan " berada dalam keadaan baik " dan penculik " berdrama " dengan keadaan sebagai " taktik perundingan . "
dua kapal frigat Sepanyol sedang memerhati keadaan di pantai Somali .
Queensland Australia Sir Joh Bjelke Petersen , tokoh kontrovesi yang berkhidmat sebagai Perdana Menteri untuk tempoh 19 tahun dan menerajui kerajaan yang kemudiannya menjadi subjek bagi Pertanyaan Fitzgerald , telah meninggal dunia di hospital di Kingaroy , pada usia 94 tahun .
" dalam setiap perkiraan , Sir Joh merupakan pembangun negeri yang lain dari yang lain yang akan diingati kerana sentiasa meletakkan Queensland di tempat pertama , " kata Jeneral Gabenor Australia , Mejar Jeneral Jeffery , dalam kenyataannya .
Perdana Menteri Australia , John Howard : " beliau sememangnya tokoh politik yang hebat dan saya menyampaikan rasa simpati kepada isteri dan keluarga beliau . "
tetapi tidak semua suara menyokong , aktivis Queensland Aboriginal terkenal Sam Watson sebagai contoh : " orang-orang Aboriginal akan sentiasa mengingati beliau sebagai bersifat perkauman , samseng dan seorang diktator . "
mengalami keuzuran yang teruk untuk beberapa minggu , dan penurunan tahap kesihatan sejak beberapa tahun , Sir Joh meninggal dunia pada jam 6 petang AEST .
beliau dikelilingi keluarganya , yang telah dipanggil balik semalam oleh Lady Flo , isteri beliau dan Senator satu masa , bagi mengucapkan selamat tinggal yang terkahir .
Ungkapan-ungkapan seperti " Jangan kamu bimbang untuk itu " dan " Kasih ke atas kamu " merupakan simbol bagi pemimpin yang menyeleweng .
senang dikenali sebagai ' Joh ' di kalagan ramai , beliau terkenal menggambarkan sidang media sebagai ' memberi makan chooks ' .
hari ini penduduk tempatan Kingaroy mengejek wartawan yang menunggu dengan jaritan dari " Kamu adalah chooks , kamu adalah chooks , ha ha " kepada " Pergi balik , wahai burung hering , " dan beberapa kata-kata lucah , seperti dilaporkan oleh Courier-Mail di Brisbane .
kejatuhan beliau dari kuasanya pada akhir 80-an di kelilingi oleh kontrovesi-kontrovesi , di mana negara terlibat dalam rasuah sehingga ke tahap timbalannya , dan Bjelke Petersen mendakwa kejahilan datang di bawah cabaran beserta caj sumpah pembohongan .
kes tersebut tidak pernah diperdengarkan kerana kontrovesi hung juri : penyelia juri , Luke Shaw , memegang jawatan sebagai Pemuda Negara - penggerak bagi Parti Nasional Bjelke Petersen - begitu juga ahli kumpulan yang menggelar diri mereka ' Rakan kepada Joh ' .
permulaan kepada kehidupannya sebagai petani kekacang kawasan terpencil Kingaroy , bekas Perdana Menteri telah selesa hingga ke saat yang terakhir , tetapi palsy lumpuh otot-otot dan organ-organnya , yang mana akhirnya menyebabkan beliau meninggal dunia .
" sepanjang hidupnya Sir Joh menggabungkan pelbagai tenaga , visi dan kerja kuat berkapasiti besar , terutamanya ketika 19 tahun pemerintahannya sebagai Perdana Menteri Queensland , " kata Gabenor Jeneral .
" apa yang kami lihat menjadi risiko besar pada masa itu bertukar menjadi pembangunan negara , " kata Bob Katter , bekas menteri bagi Kerajaan Joh , yang mendatangkan kredit kepada Sir Joh di mana bermulanya arang batu , aluminium dan industri pelancongan Queensland .
beliau juga diingati untuk merungkai kebanyakan daripada persatuan Negara , dan untuk suatu yang agak totalitarian dan cara yang agak kasar dalam mengekalkan pengawalan .
di bawah Joh , penentangan jalanan adalah diharamkan dan Cawangan Khas bagi memerhatikan secara meluas ketua authoritarian dilihat sebagai subversif , perkiraan segera Queensland , Majlis Kebebasan Sivil Australia , Terry O ' Gorman , bagi komen Sir Joh adalah " perdana menteri yang paling menyerlah pernah dimiliki Queensland dalam terma kebebasan sivil dan hak-hak kemanusiaan . "
Joh juga berpengaruh dalam kes terkenal Penyingkiran oleh Gabenor Jeneral dan kemudian- Perdana Menteri Gough Whitlam , pada tahun 1975 .
pada tahun terakhirnya sebagai Perdana Menteri , beliau membawa sebabnya ke kapital negara , dengan kempen " Joh sebagai PM . "
tetapi gangguan ini telah dikreditkan dengan kejatuhan kerajaannya , dengan siasatan rasuah dijalankan di saat akhir oleh orang dalamnya , Bill Gunn .
mayat Sir Joh , yang merupakan pengamal Lutheran , akan dikebumikan di Bethany , tanah milik keluarganya berhampiran Kingaroy .
Finland kini memegang rekod dunia bagi pusingan nyanyian karaoke tanpa henti terpanjang .
negara itu telah memegang rekod bagi jumlah terbesar penyanyi karaoke setiap masa .
rekod sebelum ini adalah selama 145 jam , yang dipegang oleh China .
walau bagaimanapun , di bar karaoke di Kouvola , bandar kecil di pantai selatan Finland , rekod itu telah ditandingi pada Rabu , dengan matlamat utamanya adalah 240 jam tanpa henti .
Finns mengembara jauh untuk menyertai acara tersebut , yang mana disiarkan secara lansung di internet .
rekod pergi bersama rekod lain Finland bagi karaoke , yang merupakan jumlah nyanyian terbesar setiap masa .
ini dijalankan oleh 80,000 peminat kumpulan rock hebat warga Finland , Lordi , yang telah bertemu di Helsinki untuk kumpulan tersebut bagi memberi konsert ringkas percuma untuk meraikan kejayaan mereka di Eurovision tahun lepas .
persembahan itu berakhir dengan semua 80,000 penyertaan dengan kumpulan tersebut atas kemenangan lagu , Hard Rock Hallelujah .
Hawker , Ibu Negara Wilayah Persekutuan Australia - Malam ini , pasukan kebangsaan Jepun mengalahkan pasukan bola lisut Ibu Negara Wilayah Persekutuan Australia ( ACT ) 1-0 di dalam satu dari dua siri permainan sebelum Jepun bermain siri ujian tiga permainan menentang pasukan kebangsaan Australia .
Jepun membawa lima pembaling ke Canberra untuk lawatan Australia mereka .
sejak Olimpik yang terakhir , Jepun berada di dalam tempoh pembangunan semula .
pemain sayap adalah muda dan kebanyakan pemain terbaik mereka masih belum mempunyai banyak pengalaman antarabangsa .
salah seorang pembaling terbaik mereka hanyalah berumur sembilan belas tahun .
belah ACT termasuk ahli-ahli pasukan kebangsaan Australia Aimee Murch dan Clare Warwick ; pemegang pingat gangsa Olimpik Brenda De Blaes ; wakil pasukan negeri Victoria , ahli pasukan kebangsaan dan pemegang pingat gangsa Olimpik Justine Smethurst ; dan Clare Currie , yang hampir kehilangan peluang untuk ke pasukan kebangsaan .
de Blaes memulakan separuh masa pertama di dalam yang pertama dengan satu pukulan .
Murch telah membaling untuk ACT memulakan separuh masa kedua di dalam yang pertama .
nombor 15 dari Jepun membuka inning dengan satu single , dan dinaikkan ke yang ketiga pada satu lagi single .
dia dicecah keluar selepas cuba berlari untuk mendapatkan markah selepas ahli pasukannya memukul pop up yang ditangkap oleh pemadang tengah ACT .
nombor 6 memukul double semasa inning ini , memberikan markah kepada hanya satu larian Jepun .
separuh masa pertama di dalam yang kedua menunjukkan pemain-pemain ACT , 1 , 5 dan 3 dicecah keluar selepas pukulan ke kawasan dekat .
separuh masa kedua di dalam yang kedua menyaksikan nombor 13 keluar pada bola faul ditangkap semasa di dalam permainan oleh penjaga tapak tiga , dan nombor 11 dan 24 keluar dengan bola yang dipukul ke dalam dan ditangkap oleh pemadang tengah ACT .
separuh masa pertama di inning ketiga menyaksikan nombor-nombor 24 dan 21 ground out .
separuh masa kedua yang ketiga melihat pemukul Jepun pertama ground out , nombor 8 mendapat single di pukulan kawasan dekat , permainan satu lagi mendapat out , dan inning berakhir dengan nombor 11 memukul kawasan dekat ground out .
permainan selebihnya mengikut corak yang sama .
dua pemain , seorang pemain ACT dan seorang dari Jepun , terkena bola dan jurulatih perlu melihat keadaan mereka .
Smethurst masuk dan membaling beberapa inning sebagai pengganti .
di antara inning kelima dan keenam , permainan ditungga seketika disebabkan seekor anjing bernama Streaker , dipunyai oleh Adam Folkard pemain kebangsaan bola lisut lelaki Australia , berlari ke dalam padang .
sebuah pengumuman dibuat di akhir permainan bahawa permainan yang dijadualkan untuk esok akan bermula lima belas minit lebih awal dari masa yang diiklankan iaitu pukul 18 : 00 .
Pentagon telah mengesahkan bahawa tentera AS telah memulakan sebuah operasi serangan udara berterusan di selatan Somalia pada hari Isnin , dan serangan itu , disasarkan kepada militia Islam , sedang berterusan .
Presiden Somalia telah terlebih dahulu berkata bahawa Amerika Syarikat telah memburu orang-orang yang disyaki dari pengeboman kedutaan Amerika Syarikat 1998 .
ia dipercayai bahawa pihak militan sedang menyembunyikan orang-orang yang disyaki .
sebuah serangan terhadap Ras Kamboni - sebuah pulau terpencil berdekatan sempadan Kenya , mewakili penglibatan Amerika yang pertama di dalam negara yang huru-hara itu sejak operasi 1993 yang menyebabkan kematian sebanyak 1,500 orang anggota militia dan orang awam .
seorang pegawai Kementerian Pertahanan Somali telah menambah laporan bahawa helikopter Amerika melancarkan serangan terhadap pejuang ICU di Afmadow , sebuah bandar berdekatan sempadan Kenya 350 kilometer barat daya Mogadishu .
serangan gunship AC-130 membunuh orang awam dengan jumlah yang tidak dapat dikenalpasti , secara bersilih ganti dilaporkan sebagai 4 , 19 atau 31 .
setakat ini , tiga orang ( termasuk seorang bayi ) telah terbunuh , dan sekurang-kurangnya sepuluh lagi cedera apabila dua treler berlanggar di dalam terowong di Interstate 5 ( Laluan Newhall ) di antara Los Angeles dan Santa Clarita California , Amerika Syarikat pada lewat malam 12 Oktober , menyebabkan perlanggaran yang bertindan-tindih tindak-balas rantai yang melibatkan di antara 28 dan 30 treler dan sebuah kereta penumpang .
kemalangan itu menyebabkan kebakaran besar yang mengambil masa selama enam jam .
sebelumnya ia dipercayai bahawa hanya 13 treler terlibat .
" kebakaran itu berlaku di dalam keadaan yang mengerikan selama lebih kurang empat jam dan membakar segala-galanya yang boleh dibakar , " kata John Tripp Ketua Bomba untuk daerah L.A.
disebabkan kemalangan itu , Gabenor California , Arnold Schwarzenegger mengisytiharkan keadaan darurat untuk Daerah Los Angeles .
serpihan telah diketepikan dan pegawai-pegawai berkata penyiasatan terperinci perlu dilakukan terhadap terowong itu sebelum ia boleh digunakan sekali lagi kerana struktur terowong itu telah terjejas .
" nampaknya tiada rebar yang cair , rosak buat masa ini . "
" tetapi ia tercabut dari dinding di beberapa kawasan , jadi kita kehilangan sokongan menegak apabila itu berlaku , " kata pegawai Jabatan Pengangkutan California , Doug Failing .
Tripp menambah bahawa lebih banyak mayat mungkin terperangkap di dalam bangkai tersebut , katanya " ... kami harus melakukan pencarian dengan sangat teratur . "
" mungkin malangnya lebih ramai orang yang tidak dapat melarikan diri . "
setakat ini pihak berkuasa belum mengenalpasti tiga orang yang terbunuh .
penyiasatan terperinci sedang dijalankan tentang apa yang menyebabkan kemalangan tersebut .
di dalam sebuah temubual dengan Washington Post yang menyebabkan kontroversi dan pengutukan berleluasa , Presiden Pakistan , Pervez Musharraf , telah membuat ulasan yang tidak dinilai dengan baik tentang rogol dan mangsa-mangsa rogol .
Musharaff dipetik sebagai berkata , " Rogol telah menjadi perkara membimbangkan yang menghasilkan wang " dan dia mencadangkan bahawa dengan dirogol adalah cara untuk mendapatkan visa ke negara-negara barat .
mangsa rogol yang ditonjolkan , Mukhtar Mai , menyingkirkan pemikiran bahawa mana-mana wanita boleh membenarkan dirinya diperlakukan sebegitu untuk wang .
kesnya mendapat perhatian berleluasa oleh media antarabangsa dengan ia dikatakan bahawa rogolnya telah diarahkan oleh panchayat ( majlis perbandaran ) tempatan .
Pesuruhjaya Hak Asasi Manusia Bangsa-bangsa Bersatu telah menyoal dasar-dasar pencari suaka yang ketat minggu ini , menyatakan bahawa peraturan penahanan mandatori Australia telah " mencemarkan " rekod hak asasi manusianya .
Navi Pillay , pemerhati Hak Asasi Manusia UN , telah terutamanya kritis tentang perjanjian pertukaran pencari suaka Perdana Menteri Julia Gilliard dengan Malaysia .
perjanjian dua hala ini , jika ditandatangani , akan melihat 800 pelarian yang cuba pergi ke Australia dengan bot terus dihantar ke Malaysia .
sebagai balasan , Australia akan mengambil 4,000 pelarian tulen dari Malaysia selama empat tahun .
walau bagaimanapun , Malaysia belum menandatangani sama ada Konvensyen Pelarian , atau Konvensyen Menangani Penyeksaan .
di dalam temubual dengan ABC , Cik Pillay menyuarakan kebimbangan terhadap perkara ini , menyatakan bahawa Australia mungkin " mencemari undang-undang pelarian " dengan menghantar pencari suaka ke sebuah negara di mana tiada undang-undang yang akan melindung mereka .
Pillay , seorang bekas pembantah anti-apartheid Afrika Selatan , juga menyuarakan kebimbangan terhadap kewujudan " penggambaran seseorang sebagai kejam " secara politik pencari-pencari suaka ini dengan menyatakan , " akibat penahanan politik yang berterusan ' dibanjiri ' orang yang ' mengelat ' telah menyebabkan pengecapan seluruh kumpulan , tidak mengira dari mana mereka datang atau daripada bahaya apa yang mereka melarikan diri . "
di dalam lawatan enam harinya itu , Pesuruhjaya Hak Asasi Manusia UN melawat dua pusat penahanan dan dia berkata dia terkejut dengan " keadaan berputus asa yang mengerikan " pencari suaka , yang mana ramai daripada mereka menunggu lebih 18 bulan untuk mendapatkan kes mereka dinilaikan .
penganiayaan pelarian ini telah diperkukuhkan hari ini dengan pelepasan laporan Suruhanjaya Hak Australia , yang memperlihatkan masalah-masalah besar kemurungan dan yang membahayakan diri di antara tahanan-tahanan di Pusat Penahanan Villawood di Sydney .
Senat Amerika Syarikat telah mengalahkan usul pindaan untuk melarang perkahwinan homoseksual .
rang undang-undang itu dikalahkan 48 kepada 49 dan tidak menerima jumlah minimum 60 undian yang tidak membenarkan rang undang-undang itu dibawa ke Senat penuh .
rang undang-undang itu kekurangan 18 undian daripada 67 yang diperlukan untuk kelulusan .
untuk rang undang-undang itu menjadi sebahagian Perlembangaan A.S. rang undang-undang ini harus diluluskan oleh majoriti dua pertiga di kedua-dua Senat dan Dewan Perwakilan , kemudian diluluskan oleh badan perundangan tiga perempat ( iaitu , 38 ) oleh Negeri-negeri .
walau bagaimanapun , Ahli Senat David Vitter , R-LA , seorang penyokong rang undang-undang itu berkata , " kami sedang membina undian . "
" kebanyakan rakyat Amerika masih belum yakin yang wakil pilihan mereka atau badan kehakiman akan mengembangkan definisi perkahwinan secara muktamad untuk memasukkan pasangan sama jantina , " kata John McCain ( R-AZ ) yang membantah rang undang-undang itu .
" satu undian untuknya adalah satu undian menentang perkahwinan , menentang konsep hidup bersama , menentang semua usaha-usaha yang lain untuk negeri-negeri memberi layanan yang adil kepada orang homoseksual di bawah undang-undang , " kata Ahli Senat Massachusetts Edward Kennedy .
rang undang-undang ini akan mentakrifkan perkahwinan sebagai di antara seorang lelaki dan seorang perempuan , dan akan menghalang perestuan perkahwinan sama jantina secara rasmi .
rang undang-undang itu dijangka dibawa balik ke Senat pada bulan Julai .
penggubal undang-undang AS telah mendapat perjanjian pada saat-saat akhir untuk mengelakkan penutupan kerajaan , yang sepatutnya boleh bermula pada hari Sabtu pukul 12 : 00 EDT ( 04 : 00 UTC ) .
perjanjian itu , diumumkan hanya sejam sebelum penutupan itu dijangka terjadi , melibatkan AS $ 38.5 bilion di dalam pengurangan belanjawan .
terlebih dahulu pada hari Jumaat , penggubal undang-undang AS mengelakkan dakwaan bahawa perjanjian tengah malam sedang dibuat , tetapi sumber Parti Republikan kemudian melaporkan sebuah perjanjian kemungkinan besar akan dicapai .
perjanjian itu nampaknya telah dicapai selepas pertikaian tentang pendanaan kerajaan untuk organisasi seperti Perancangan Masa Keibubapaan diselesaikan .
Boehner berkata kedua-dua belah membuat keputusan tentang tempoh lanjutan enam hari atau " jambatan " pendanaan kerajaan , yang akan membenarkan Kongres membuat penyelesaian akhir kepada tahun fiskal 2011 selebihnya , yang berakhir pada bulan September .
mengundi untuk perjanjian sebagai keputusan akan dilakukan minggu hadapan , menurut Boehner .
penutupan kerajaan AS sepenuhnya yang terakhir berlaku pada tahun 1995 , semasa pentadbiran Bill Clinton , berlangsung selama lima hari ; ianya diteruskan dengan penutupan separa selama 21 hari .
semasa penutupan kerajaan , pekerja persekutuan penting perlu bekerja , tetapi pekerja yang tidak penting diberi cuti dari bertugas tidak berbayar .
pekerja penting termasuk kakitangan tentera , pengawal trafik udara , pegawai kecemasan , dan pegawai perisik .
di Filipina , calon presiden Parti Liberal Benigno Simeon Cojuangco Aquino III , lebih terkenal sebagai Noynoy , telah secara rasmi dipilih sebagai Presiden Filipina baru di pilihanraya presiden 2010 .
beliau berkempen untuk menghentikan rasuah dan kemiskinan dan beliau berkata membuat dakwaan terhadap pegawai-pegawai yang menerima rasuah akan dijadikan keutamaan .
Noynoy menerima lebih daripada 15 juta undian , kira-kira 5.7 juta lebih banyak daripada lawan terdekatnya , Joseph Estrada yang tersingkir .
Noynoy berkata di dalam temubual , " Saya mahu memimpin dengan contoh . "
" saya telahpun membuat sumpah secara awam , saya tidak akan mencuri . "
Presiden Senat Juan Ponce Enrile memberitahu orang ramai selepas pengiraan : " kita telah lakukan ini ... untuk orang Filipina ... "
beliau berumur 50 tahun , seorang bujang , siswazah ekonomi , Ahli Senat dan satu-satunya anak lelaki bekas Presiden Corazon Aquino dan bekas Ahli Senat Benigno Aquino Jr .
bapa Noynoy telah ditembak semasa jagaan tentera sewaktu rejim diktator mendiang Ferdinand Marcos , sebelum ibunya , Corazon Aquino , memimpin Revolusi Kuasa Rakyat yang menjatuhkan Marcos pada tahun 1986 .
di Filipina , presiden dan naib presiden dipilih berasingan ; calon naib presiden Parti Puwersa ng Masang Pilipino , Jejomar Cabauatan Binay akan menjadi naib presiden negara itu .
Noynoy adalah bakal presiden , sementara Gloria Macapagal-Arroyo adalah penjawat kini yang akan keluar .
beliau akan secara rasmi menjadi presiden Filipina kelima belas pada 30 Jun.
di dalam Piala Dunia Ragbi 2007 , New Zealand telah mengalahkan pendatang baru Portugal dalam perlawanan .
All Blacks telah memperoleh lebih dari 100 mata dan 16 cubaan di dalam kemenangan 108-13 bagi mengekalkan posisi mereka di tempat teratas Kumpulan C.
perlawanan dominan separuh pertama dari Australia membawa mereka mengalahkan Wales di Cardiff .
satu pengakhiran yang kuat dari Wales tidak mencukupi untuk menghalang Wallabies , yang mendahului Kumpulan B , dengan memenangi 32-20 dan mendapat satu mata tambahan .
Ireland tiba dari belakang untuk menewaskan satu pasukan Georgian yang kuat 14-10 di Kumpulan D.
Georgia mendahului di permulaan separuh kedua dan mengancam untuk memperoleh mata di akhir perlawanan tetapi pertahanan Ireland berjaya memegang kemenangan empat mata .
New Zealand , salah satu pasukan kegemaran perlawanan , telah mengalahkan Portugal dengan 95 mata .
Joe Rokocoko telah memperoleh dua cubaan untuk memulakan perolehan mata bagi New Zealand .
Joe Toeva , Ali Williams , Aaron Mauger , Jerry Collins , Cris Masoe dan Andrew Hore masing-masing telah menambah cubaan dengan New Zealand menamatkan separuh lagi dengan 52-3 di hadapan .
Rui Cordeiro telah memperoleh satu-satunya cubaan Portugal di dalam perlawanan sejurus selepas permulaan semula , yang telah diubah oleh Duarte Cardoso Pinto .
bagaimanapun semua cubaan dari Brendon Leonard , Nick Evans , Andrew Ellis , Leon MacDonald , Carl Hayman dan dua dari Conrad Smith telah menyempurnakan kemenangan New Zealand .
Duarte Cardoso Pinto telah menambah satu penalti bagi Portugal di dalam minit ke75 .
Nicky Evans memperoleh sejumlah 33 mata buat New Zealand , menukar 14 cubaan dan memperoleh satu dari dirinya .
New Zealand adalah teratas di dalam Kumpulan C dengan sepuluh mata , di hadapan Scotland dengan 5 dan Itali dengan 4 .
Australia mendahului dengan serta merta selepas beberapa saat penalti dari Striling Mortlock , tetapi Wales menyamakannya lima minit kemudian melalui Stephen Jones .
Australia telah mendominasi pada separuh pertama , dan mendahului 25-3 pada separuh masa selepas cubaan dari Matt Giteau , Stirling Mortlock dan Chris Latham dan satu gol sepakan dari Berrick Barnes .
Jonathan Thomas memperoleh satu cubaan dan James Hook menambah pertukaran dan satu penalti bagi memotong defisit kepada dua belas mata .
bagaimanapun Chris Latham memperoleh cubaan keduanya di dalam perlawanan , dan keempat Australia , bagi memulihkan kedudukan mereka di dalam perlawanan dan menjamin mata tambahan .
Shane Williams memperoleh satu cubaan bagi Wales di dalam minit ke76 selepas penamat yang kuat , tetapi ianya tiba lewat dan Australia telah menang dengan dua belas mata .
Wales di tempat kedua dengan lima mata , di hadapan Fiji dengan perbezaan mata , sementara Jepun mempunyai satu mata dan Kanada di tempat terbawah kumpulan itu dengan tanpa mata .
Rory Best memperoleh satu-satunya cubaan dalam separuh pertama di minit ke17 , di mana Ronan O ' Gara telah menukarnya .
Merab Kvirikashvili memperoleh satu penalti lewat separuh pertama bagi Georgia , menjadikan mata kepada hanya 7-3 di separuh masa .
Georgia mendapat pendahuluan yang mengejutkan di separuh kedua , apabila Georgi Shkinin memperoleh satu cubaan di minit ke45 .
Girvan Dempsey mendapatkan semula pendahuluan bagi Ireland dan satu lagi pertukaran oleh Ronan O ' Gara dibuat menjadikan mata sebanyak 14-10 .
Georgia terus memberi tekanan kepada Ireland di tahap akhir perlawanan , dua kali menghampiri garis cubaan Ireland , tetapi mereka tidak dapat menembusinya dan Ireland berjaya memenangi dengan empat mata di hadapan .
Ireland berada di tempat kedua di Kumpulan D dengan lapan mata , di belakang Argentina dengan sembilan mata .
Perancis berada di tempat ketiga dengan satu mata dari perlawanan tunggal , sementara Georgia mempunyai satu mata dari dua kekalahan .
dua orang tentera US yang dibunuh di Afghanistan semalam selepas ditembak oleh seorang penterjemah bahasa warga Afghan di wilayah Wardek barat daya Kabul , menurut NATO .
seorang pengawai berkata penterjemah itu telah menembak mereka di satu pertahanan di timur Afghanistan sebelum dia ditembak mati oleh tentera lain .
sebab mengapa penterjemah bahasa itu memulakan tembakan masih belum dijelaskan ; Namun , penyerang itu sepertinya adalah seorang " pekerja yang tidak berpuas hati , " dan bukanlah seorang ahli militan , menurut kepada seorang pengawai tentera US .
penterjemah bahasa itu dikatakan telah bergaduh dengan tentera-tentera itu berkenaan upah dan layanan terhadapnya sebelum menembak .
NATO pada awalnya hanya mengeluarkan satu kenyataan ringkas semalam , yang menyatakan bahawa dua orang tentera dan seorang orang awam telah terbunuh .
sementara itu di bahagian wilayah Wardek yang lain , empat orang tentera Afghan telah mati di dalam satu serangan udara oleh angkatan bersenjata gabungan .
kedua-dua kejadian tidak difikirkan mempunyai kaitan .
NATO menyatakan yang kematian itu adalah " disesalkan " dan akan membuat siasatan ke atasnya .
Kementerian Pertahanan Afghan meminta hukuman dijatuhkan ke atas " pembunuh " yang bertanggungjawab ke atas serangan udara tersebut .
kerajaan persekutuan Australia dan kerajaan New South Wales tidak akan menjual saham mereka di Snowy Hydro Limited ( pemilik dan pengendali Rancangan Hidroelektrik Snowy Mountains ) .
pemegang saham terbesar Snowy Hydro Limited adalah kerajaan NSW dengan memegang saham sebanyak 58 peratus .
kerajaan Victoria memiliki taruhan sebanyak 29 peratus dan kerajaan persekutuan memiliki 13 peratus .
Perdana Menteri NSW Morris Iemma telah mengumumkan pada Disember 2005 bahawa beliau berhasrat untuk menjual saham negara di Snowy Hydro yang menyebabkan kerajaan persekutuan dan kerajaan Victoria mengikut langkahnya .
cadangan jualan itu telah menarik kritikan yang amat banyak oleh mereka yang percaya jualan itu akan memberi kesan kepada alam semula jadi dan bekalan air di sepanjang Snowy River , ini telah diperkukuhkan semalam apabila 58 rakyat Australia terkemuka telah membentangkan satu petisyen kepada kerajaan bagi menentang jualan tersebut .
Perdana Menteri John Howard telah mengumumkan pada hari ini bahawa kerajaan persekutuan tidak akan menjual 13 peratus sahamnya di Snowy Hydro berikutan apa yang beliau panggil sebagai " reaksi gigih dari komuniti . "
di dalam satu kenyataan , En . Howard berkata , " Keputusan untuk menjual Snowy Hydro telah mencipta kesedihan , kerisauan dan kekacauan yang amat di dalam komuniti rakyat Australia . "
En . Howard berkata yang jualan itu bukanlah satu janji pilihanraya dari kerajaannya dan kerajaan persekutuan telah gagal melihat manfaat jangka panjang dari jualan tersebut .
beliau turut berkata yang kerajaan perlu untuk " melindungi kepentingan semua pihak yang bergantung kepada sumber air ikonik Australia . "
kerajaan Persekutuan bagaimanapun telah menyatakan yang walaupun ia tidak akan menjual sahamnya di Snowy Hydro , ia tidak akan membeli saham tambahan jika NSW dan Victoria tetap meneruskan jualan saham yang dipegang mereka .
walaupun telah memberitahu Radio Macquarie pagi ini yang kerajaannya akan tetap dangan jualan itu kerana ia adalah " kepentingan terbaik bagi NSW , " Perdana Menteri Iemma kemudiannya telah mengumumkan selepas kenyataan En . Howard , yang kerajaan NSW akan menarik saham mereka dari jualan .
En . Iemma mengaku yang jualan tersebut menjadi amat susah untuk diteruskan dengan kerajaan persekutuan menarik 13 peratus sahamnya dari jualan .
" Perdana Menteri telah menarik diri dari jualan dengan tiba-tiba , " kata En . Iemma .
" keputusan Komanwel telah menyebabkan NSW amat sukar untuk meneruskannya , " beliau mengaku .
Victoria masih belum mengumumkan samada akan menarik sahamnya dari jualan .
para saintis yang menggunakan Satelit Swift NASA dan teleskop lain telah memerhati satu supernova berdekatan masa nyata yang terjadi di kumpulan bintang Aries .
letupan itu dikatakan adalah letupan terkuat diketahui saintis , yang terdiri daripada satu pecahan sinar gama atau pecahan sinar-x .
para saintis berkata yang pecahan itu adalah tanda permulaan kepada kematian sebutir bintang .
Swift pada mulanya telah mengesan letupan tersebut pada 18 Februari ( ia telah diberi gelaran GRB 060218 ) , yang membenarkan teleskop dan satelit untuk melihat kejadian tersebut ketika ia terjadi .
pecahan itu terjadi selama lebih dari 2,000 saat ( 33 minit ) .
" ini adalah salah satu kejadian yang tidak diaturkan di alam semesta berdekatan kita yang kami harap Swift dapat menangkapnya , " kata Neil Gehrels , penyiasat utama Swift di Pusat Penerbangan Angkasa Goddard NASA di Greenbelt , Maryland .
" pemerhatian itu menangkap masa apabila bintang runtuh , mengeluarkan lapisan luarannya dan kebanyakan beratnya dan meninggalkan satu tinggalan padat . "
" dan kami berpendapat tinggalan padat itu adalah sebutir bintang neutron , " kata seorang penulis untuk jurnal Nature , di mana laporan tersebut akan diterbitkan pada hari Khamis .
para saintis sedang merancang untuk menggunakan teleskop Angkasa Hubble dan sinar-X Balai Cerap Chandra di dalam usaha mendapat lebih banyak imej kejadian tersebut .
bintang itu terletak sekurang-kurangnya 440 juta tahun cahaya dari Bumi .
kumpulan saintis yang diketuai Sergio Campana dari Institut Astrofizik Kebangsaan Itali dan Alicia Soderberg , seorang pelajar siswazah di Caltech di Pasadena , California .
kamera utama pada Teleskop Angkasa Hubble telah ditutup dan mungkin akan hanya dipulih semula kepada sebahagian fungsinya , menurut satu laporan dari Pentadbiran Angkasa dan Aeronautik Kebangsaan ( NASA ) .
kamera pada teleskop itu , yang dikenali sebagai " Kamera Termaju untuk Tinjauan " atau ACS , boleh diaktifkan semula tetapi akan dipulihkan kepada hanya satu pertiga kapasiti operasinya .
kamera tersebut telah ditutup pada hujung minggu , kemungkinan atas sebab satu kegagalannya untuk bekalan kuasa sokongan .
ini adalah kali ketiga kamera itu tertutup sebegitu di dalam tahun kalendar lalu .
kamera itu telah beroperasi dengan kuasa sokongan sejak dari 30 Jun , 2006 , apabila jurutera telah menukar dari bekalan kuasa utama ( " Side A " ) kepada sokongan ( " Side B " ) atas sebab kerosakan .
satu lembaga ulasan telah diadakan pada 29 Januari bagi mengkaji semua pilihan dan membuat keputusan tindakan yang akan diambil .
keputusan mereka akan dilaporkan kepada NASA pada 2 Mac , 2007 .
ACS , yang telah dibangunkan secara bersama oleh empat agensi Amerika , telah dipasangkan pada Mac 2002 .
ia adalah sebuah sistem dengan tiga kamera , penapis , dan penyerak yang bertindak untuk mengesan jarak gelombang cahaya antara dekat infra-merah hingga ke ultra-ungu .
ia adalah sebuah sistem yang dirancang bertahan sehingga lima tahun , menurut Preston Burch , pengarah bersekutu dan pengurus program bagi Teleskop Angkasa Hubble .
NASA turut menunjukkan yang empat sistem utama lain di teleskop kekal tidak terganggu dan berfungsi dengan normal .
satu misi dijadualkan ke teleskop angkasa itu pada 2008 dijangkakan untuk menghantar peralatan bagi meningkatkan lagi keupayaan teleskop itu .
kesan kegagalan ACS pada misi yang dijadualkan itu masih belum diketahui .
Burch berkata di dalam satu siaran akhbar yang diletakkan di laman web utama NASA , " Adalah amat penting bagi lembaga ulasan untuk menjalankan penyiasatan penuh yang membolehkan kami menentukan jika perlu sebarang perubahan kepada peralatan baru yang akan dipasangkan semasa misi servis yang akan datang dan supaya kami dapat memastikan hasil saintifik yang maksimum dari teleskop itu . "
" kami akan terus melakukan usaha terbaik di dalam persediaan kami ke arah misi servis itu , yang pada masa kini dirancang akan terbang pada September 2008 . "
satu hari selepas Perancis mula menguatkuasakan satu larangan untuk orang awam dari memakai purdah Islam yang menutup muka , sama ada niqab atau burqa , polis Perancis dalam jangka masa pendek telah menahan dua orang wanita berpurdah .
polis itu kemudiannya mendakwa yang kedua wanita itu telah ditangkap kerana mengambil bahagian di dalam satu protes tanpa kebenaran , bukan kerana mereka memakai purdah .
wanita itu ditahan ketika berada di luar Gereja Besar Notre Dame yang terkenal di Perancis , dan mungkin akan dikenakan denda sehingga $ 217 ( 150 euro ) , servis komuniti dan / atau satu kursus kerakyatan di bawah undang-undang .
walaupun larangan itu termasuk burqa dan niqab , ia tidak termasuk hijab atau chador .
hijab adalah satu purdah yang membolehkan wajah masih dapat dilihat walaupun menutupi rambut dan leher , dan chador menutup hanya badan .
undang-undang itu telah menimbulkan banyak perdebatan , kedua-dua di Perancis dan di sekeliling dunia .
mereka yang menentang undang-undang baru itu berkata ia mengehadkan kebebasan berucap dan kebebasan beragama , manakala penyokong mendakwa martabat wanita dijatuhkan dengan pemakaian purdah dan undang-undang itu bermaksud untuk memberi kuasa kepada wanita , dan juga meningkatkan keselamatan awam .
kerajaan Perancis , dalam membela larangan itu , berkata yang ia adalah perlu kerana pemakaian purdah bertentangan dengan standard hidup di Perancis dan merendahkan status wanita di dalam sebuah negara di mana semua orang dianggap sama .
Perdana Menteri Perancis Francois Fillon berkata yang larangan itu konsisten dengan nilai kebangsaan Perancis .
" Republik Perancis tinggal di dalam fesyen dengan kepala yang didedahkan , " kata beliau di dalam sebuah kenyataan yang diterbitkan oleh akhbar kerajaan .
kerajaan Perancis dahulunya telah berusaha untuk memuatkan Muslim di negara itu , termasuklah menubuhkan satu badan bagi menangani kewujudan Islam ; bagaimana pun , menurut Amer Sahar , seorang profesor yang sedang mengkaji topik tersebut , sesetengah Muslim di negara itu berkata yang mereka merasa seperti mereka sedang diserang oleh kerajaan .
dia berkata sebahagiannya " geram kerana mereka tidak dibenarkan untuk menjadi kedua-dua Muslim dan rakyat Perancis . "
kerajaan Perancis turut risau dengan wanita dan kanak-kanak yang dipaksa memakai purdah .
tindakan sedemikian dikatakan adalah " satu bentuk baru penghambaan dan republik tidak boleh menerima ia terjadi di atas tanahnya . "
aktivis Rachid Nekkaz telah menggadai salah satu rumahnya bagi menyediakan wang untuk membayar denda buat sebarang wanita yang ditangkap di bawah undang-undang itu .
" saya mahu menghantar satu mesej yang jelas kepada Presiden Nicolas Sarkozy yang kami boleh buat apa yang kami mahu . "
" kami mempunyai perlembagaan dan semua orang perlu menghormatinya , " kata dia .
menurut Badan Perlembagaan Perancis , undang-undang itu " mematuhi Perlembagaan " kerana ia tidak mengehadkan kebebasan beragama atau menghukum dengan melampau kerana menjalankan hak itu di tempat ibadat .
satu arahan paten kontroversi telah dilontar keluar di dalam sebuah undian majoriti .
648 MEP dari 680 telah mengundi pada hari ini untuk menolak cadangan , yang bertujuan untuk membawa Eropah sebaris dengan rang undang-undang U.S. yang serupa .
" ini adalah satu kejayaan besar buat mereka yang berkempen untuk memastikan inovasi dan daya saing Eropah dipelihara dari pemonopolian fungsian perisian dan kaedah perniagaan . "
" ini menandakan pengakhiran usaha Suruhanjaya Eropah dan pengawai paten kerajaan bagi mengenakan kemerosotan dan amalan Pejabat Paten Eropah ( EPO ) yang boleh dipersoalkan secara undang-undang ke atas negara ahli , " kata Penubuhan Infrastruktur Maklumat Bebas , yang menentang arahan tersebut .
penentang arahan paten itu mendakwa satu rang undang-undang yang meliputi Harta Intelektual ( IP ) akan " menahan inovasi " di Eropah , kerana ia membenarkan pelaksanaan paten di dalam perisian .
banyak aktivis anti-paten berkata yang jika rang tersebut diluluskan , perniagaan kecil dan penggemar akan terdedah kepada bahaya tuntutan mahkamah dari syarikat besar dan potfolio paten mereka yang luas .
Presiden Amerika Syarikat Barack Obama sedang mencari satu " strategi keluar yang menyeluruh " dari perang Afghanistan .
di dalam temubual 60 minit , Obama berkata , " Strategi keluar mesti ada . "
" perlu difahami yang ini bukanlah satu perkara tanpa tujuan yang berterusan . "
pada Februari Obama berkata yang 17,000 orang tentera lagi akan dihantar pada tahun ini sebelum pilihanraya Ogos bagi menambah kepada 36,000 orang tentera Amerika yang sudah diletakkan di Afghanistan .
Obama menyatakan yang Misi U.S. di Afghanistan adalah untuk " memastikan al-Qaeda tidak dapat menyerang tanah air U.S. dan kepentingan U.S. dan sekutunya . "
pilihan di dalam strategi itu termasuklah memperbaiki hubungan Afghan-Pakistan , dalam masa yang sama membina semula ekonomi Afghanistan .
" saya menjumpai satu simetri pandangan yang amat menggalakkan di antara sekutu NATO dan tentera dari negara lain dengan Amerika Syarikat , " Richard Holbrooke , Wakil Khas U.S. ke Afghanistan dan Pakistan berkata .
" di masa lalu , kerajaan Amerika Syarikat telah membangunkannya dalam keadaan yang terpencil , dan mereka telah mempunyai satu polisi Afghan dan satu polisi Pakistan . "
" kami perlu mengintegrasikan kedua-duanya dan saya berharap seluruh dunia dapat bersama-sama kami di dalam usaha itu , " kata Holbrooke .
Obama turut menyatakan yang " kerumitan Afghanistan telah dipadankan , dan mungkin turut dibantutkan , oleh kerumitan keadaan ekonomi . "
" mesti ada cara untuk keluar dari Afghanistan dan fokus kepada perkembangan ekonomi . "
" kami mungkin perlu membawa masuk lebih banyak pendekatan diplomatik kawasan untuk dilakukan . "
" kami mungkin perlu mengkoordinasi dengan lebih efektif dengan sekutu kami . "
" tetapi kami tidak boleh lari dari misi utama kami . "
sekutu Eropah telah menyatakan yang mereka mempunyai rancangan keluar untuk tiga ke empat tahun akan datang .
Hamid Karzai , Presiden Afghan berkata bahawa walaupun beliau menyokong idea tersebut , beliau menekankan yang tidak perlu ada sebarang " pengaturan yang cepat . "
wakil Tom Tancredo ( R-CO ) telah menjelaskan kenyataannya sebelum ini yang " kamu boleh mengebom tempat suci mereka , " di dalam kejadian serangan nuklear ke atas U.S. oleh pengganas Islam .
Rep. Tancredo enggan untuk meminta maaf , dengan mengatakan " Apabila kami mengebom Hiroshima , apabila kami mengebom Dresden , kami telah menghukum ramai orang yang tidak semestinya ( bersalah ) . "
" tidak semua rakyat Jerman adalah ahli Parti Nazi . "
bagaimanapun , Tancredo menegaskan bahawa dia bercakap secara hipotetikal dan tidak semestinya mencadangkan polisi .
kata-kata itu , dikeluarkan di dalam satu temubual radio pada 15 Julai , yang dihoskan oleh Pat Campbell dari WFLA di Orlando , Florida , telah mendapat sokongan dari kumpulan konservatif seperti Rangkaian Perisikan Timur Laut dan Republik Bebas , dan telah menyinggungkan komuniti Muslim Amerika .
wartawan Veteran Rumah Putih Helen Thomas , 89 , telah mengumumkan persaraannya semalam bermula dengan serta merta , menamatkan lima puluh tujuh tahun kariernya , di tengah-tengah kritikan ke atas komen kontroversi .
Thomas telah bekerja sebagai seorang wartawan selama lebih lima puluh tahun dan telah membuat liputan setiap presiden dari John F. Kennedy hingga kepada Obama .
Thomas , anak perempuan kepada pendatang warganegara Lebanon , yang meninggalkan jejak buat wartawan wanita di politik di Amerika Syarikat , telah menamatkan kariernya selepas meminta maaf kerana mengatakan yang Israel perlu " keluar dari Palestin . "
semasa persaraan , Thomas berkata : " saya amat menyesal dengan komen yang dibuat pada minggu lepas mengenai Israel dan Palestin . "
" ia tidak menunjukkan perasaan saya-yang percaya keamanan akan muncul di Timur Tengah hanya jika semua pihak mengakui keperluan untuk saling hormat-menghormati dan toleransi . "
pemergiannya sebagai kolumnis Hearst Newspaper telah diumumkan selepas dia dirakam di dalam satu video mengatakan : " ingat , mereka ini sedang diduduki dan itu adalah tanah mereka . "
" itu bukan Jerman , itu bukan Poland , " dan Israel perlu " keluar dari Palestin " dan " mereka perlu kembali " ke Poland , Jerman , US dan " tempat lain . "
Rabai David Nesenoff , seorang pembuat filem bebas berkata dia bercakap dengan Thomas di luar Rumah Putih pada Hari Warisan Yahudi pada 27 Mei .
video komen kontroversinya telah tersebar luas dengan cepat di Internet melalui laman webnya , rabbilive.com , yang dilancarkan pada minggu lepas .
dia dikeluarkan dari agensi pidato umum dan alamat permulaan sebuah sekolah tinggi telah dibatalkan .
kenyataan Hearst tiba tidak lama selepas setiausaha akhbar Rumah Putih Robert Gibbs memanggil komennya sebagai " melampau dan patut dicela . "
Thomas telah bekerja sebagai seorang wartawan selama lebih lima puluh tujuh tahun dan telah bekerja selama beberapa dekad sebagai wartawan Rumah Putih untuk United Press International dan menjadi kolumnis rantai akhbar Hearst beberapa tahun lalu .
dia merupakan pengawai wanita pertama di dalam Kelab National Press , ahli wanita pertama dan presiden Persatuan Wartawan Rumah Putih , dan , pada tahun 1975 , ahli wanita pertama Kelab Gridiron .
Thomas tidak banyak berusaha untuk menyembunyikan pandangannya , dengan selalu menyoal Presiden George W. Bush dan Barack Obama dan setiausaha akhbar mereka tentang perang di Timur Tengah .
dua minggu lalu , dia bertanya Obama , " En . Presiden , bilakah anda akan keluar dari Afghanistan ? "
" Mengapakah anda terus membunuh dan mati di sana ? "
" apakah alasan anda ? "
" dan jangan berikan kami Bushisme seperti , ' Jika kami tidak pergi ke sana , mereka akan datang ke sini . "
semasa pentadbiran Kennedy , Helen telah menamatkan semua persidangan akhbar presiden dengan satu tanda " Terima kasih , En . Presiden " dan sentiasa mengeluarkan kaveat tentang kerjanya : " di dalam karier saya anda hanya sebaik cerita terakhir anda . "
polis di Austria telah melaporkan yang situasi di bilik bawah tanah di mana orang telah dipenjarakan secara haram selama lebih dua dekad adalah ' zalim ' .
mereka juga turut berkata yang mereka tidak dapat berada di bilik bawah tanah itu untuk lebih dari satu jam .
AP melaporkan yang ini kerana aras oksigen yang rendah di dalam bilik bawah tanah itu .
pengumuman oleh polis ini timbul selepas polis di bandar Lower Austrian di Amstetten telah menahan seorang lelaki tua berusia 73 tahun yang didakwa telah menyimpan anak perempuannya , yang kini berumur 42 tahun , dikunci di dalam bilik bawah tanah rumahnya di Amstetten sejak dari 29 Ogos , 1984 .
lelaki itu , yang dikenalpasti polis sebagai Josef Fritzl , dikatakan telah mula mencabul secara seksual anak perempuannya , yang dinamakan sebagai Elisabeth Fritzl , ketika dia masih berusia sebelas tahun , dan kemudiannya melahirkan tujuh orang anak .
salah seorang dari anak-anaknya , satu set kembar yang dilahirkan pada tahun 1996 , telah mati akibat pengabaian sejurus selepas kelahiran dan mayatnya dibakar oleh ayah mereka .
enam orang anak-anak yang terselamat , tiga lelaki dan tiga perempuan , yang kini berusia di antara 5 hingga 20 tahun .
tiga dari anak-anak ditinggalkan di muka pintu Josef F. dan kemudiannya dibesarkan sebagai anak angkat oleh Josef F. dan isterinya , Rosemarie , sementara tiga anaknya yang lain ditinggalkan dengan ibu mereka dan tidak pernah merasai cahaya matahari sehinggalah dia dijumpai .
Rosemarie F. dikatakan tidak sedar akan aktiviti suaminya .
polis menjadi sangsi apabila seorang anak perempuan berumur 19 tahun , Kerstin , telah dibawa ke hospital dengan satu penyakit membawa maut yang misteri , dan rekod perubatan keluarga itu telah diperiksa .
polis berkata yang Elisabeth F. kelihatan " amat terganggu " dari segi psikologi , dan hanya bersetuju untuk bercakap setelah pihak berkuasa menjamin yang dia tidak akan perlu berhubung dengan bapanya , dan anak-anaknya akan dijaga .
pihak berkuasa tempatan baru-baru ini telah mengeluarkan satu kenyataan mengenai insiden ini , dengan satu bahagian terjemahan Bahasa Inggeris seperti di bawah :
berita itu telah mengejutkan Austria , kerana persamaannya dengan kes Natascha Kampusch yang diculik pada umur 10 tahun , dan telah melarikan diri setelah dikurung di dalam sebuah " kurungan bawah tanah " selama lapan tahun pada 2006 .
tuduhan pertama di bawah Akta Mahkamah Jenayah Antarabangsa U.K. yang baru telah dibawa menentang tujuh orang pasukan setia negara British .
tuduhan tersebut berkaitan dengan penganiayaan orang awam dan kematian Baha Mousa ( 26 ) seorang penyambut tetamu hotel di Basra pada 2003 .
tuduhan tersebut termasuklah membunuh , perlakuan tidak berperikemanusiaan , yang menyebabkan kerosakan badan secara nyata , dan serangan biasa terhadap orang awam Iraq .
seorang Pengawai Waran dan seorang Mejar di dalam Kor Perisik British dan bekas komander Regimen Lancashire Permaisuri ( kini Duke bagi Regimen Lancaster ) telah dituduh atas kecuaian dalam menjalankan tugas .
pasukan setia negara British yang pertama memberi bukti adalah , seorang juruterbang senior di dalam RAF , yang memberi keterangan yang dia melihat tahanan dengan bag di atas kepala mereka ditendang dan dianiaya secara lisan .
dia berkata yang dia tidak pernah melihat sesuatu seperti itu dan tidak tahu apa yang perlu dilakukan .
dia tidak masuk campur kerana " mereka ( tentera-tentera itu ) lebih besar dari saya , dan saya tidak tahu apa arahan mereka . "
mahkamah tentera berterusan di Pusat Mahkamah Tentera , Kem Bulford , Wiltshire .
dua orang tentera British telah terbunuh di Afghanistan pada hari Rabu , dengan salah seorang darinya adalah pengawai British dengan pangkat tertinggi yang pernah dibunuh dalam masa 30 tahun .
Leftenan Kolonel Rupert Thorneloe , 40 tahun , Pengawai Pemerintah bagi Batalion pertama Pengawal Wales , dan Trooper Joshua Hammond , 18 tahun , dari Regimen Kereta Kebal Diraja Ke-2 , telah terbunuh ketika satu alat letupan diimprovisasi telah meledak di bawah kenderaan Viking berperisai mereka .
mereka sedang bergerak di sepanjang Shamalan Canal , berdekatan Lashkar Gah di Wilayah Helmand , di dalam perjalanan untuk menambah bekalan serangan yang sedang dijalankan ketika ini menentang Taliban .
Jeneral Sir Richard Dannatt , Ketua Staf Am UK , berkata Thornloe merupakan " seorang pengawai pemerintah yang cemerlang . "
di dalam kenyataan Kementerian Pertahanan ( MoD ) , Dannatt berkata , " Keberanian dan pengawasan serius [ Thornloe ] di Batalion Pertama Pengawal Wales sejak dari Oktober tahun lepas telah mempersiapkan mereka dengan mahir bagi permintaan di Afghanistan , kedua-dua di dalam kebolehan secara profesional dan semangat tidak mudah kalah sebagai satu pasukan . "
Trooper Hammond , Dannatt berkata di dalam kenyataan MoD , " merupakan ahli tentera kereta kebal kelas pertama yang menunjukkan contoh unggul semangat dan keazaman di dalam setiap operasi seperti yang dijangkakan dari seorang tentera Kor Kereta Kebal Diraja . "
Leftenan Kolonel Thorneloe meninggalkan seorang isteri , Sally , dan dua orang anak perempuan Hannah dan Sophie .
pusat Penyelidikan T.J. Watson IBM di Cambridge telah mengeluarkan satu peralatan percuma pada 25 Mac bagi pemvisualan perubahan sejarah sebuah dokumen atau direktori dokumen , yang dipanggil aliran sejarah .
peralatan tersebut menawarkan pelbagai pandangan tentang dokumen sejarah , termasuk satu pandangan yang memberi setiap semakan kepentingan yang sama , dan sebuah pandangan garis waktu yang menunjukkan setiap semakan mengikut kadar kepada berapa lama ia kekal semasa .
setiap editor berbeza yang membuat perubahan kepada artikel mempunyai warna yang berlainan , membenarkan setiap teks editor tersebut dapat dikesan kelak .
peralatan itu pertama kali dibangunkan pada tahun 2003 dengan satu kerjasama di antara Fernanda B. Vieges dari Makmal Media MIT dan Martin Wattenberg dan Kushal Dave dari IBM .
ia pada mulanya diuji ke atas satu bahagian besar dari halaman di Wikipedia , sebuah projek ensiklopedia percuma dalam talian yang mengekalkan setiap perubahan yang dibuat ke atas setiap artikelnya .
keputusannya telah dirangka pada musim sejuk tahun 2003 dan dibentangkan di sebuah konferens pada April 2004 ; ia kekal sebagai gambaran keseluruhan yang paling komprehensif bagi kitaran hayat setiap artikel di dalam sebuah komuniti aktif wiki .
setahun selepas itu , kertas aliran sejarah itu masih kekal sebagai sumber statistik yang paling banyak dipetik bagi pengembalian vandalisme di Wikipedia .
peralatan itu pada masa kini diselenggara oleh Martin Wattenberg and Jonathan Feinberg di IBM .
ia membenarkan pengguna untuk memuat turun teks dan setiap sejarah isi kandungan bagi sebarang wiki MoinMoin , atau bagi melihat sejarah isi kandungan untuk keseluruhan direktori dokumen .
peralatan itu adalah percuma untuk dimuat turun dan digunakan , tetapi kodnya bukan dari sumber terbuka .
sokongan untuk semua wiki MoinMoin datang melalui sebuah sambungan wayar , jadi peralatan itu boleh dipanjangkan kepada antara muka asli bagi peralatan wiki yang lain di masa hadapan .
Silver Birch telah memenangi Grand National 2007 di Balapan Lumba Kuda Aintree di Liverpool .
Ditunggang oleh Robbie Power dan dilatih oleh Gordon Elliot , kuda 33-1 yang tidak dijangka akan menang telah memenangi perlumbaan 4 mile 4 furlong ( 7.2 km ) dengan panjang tiga-suku , dan menjadi pemenang Ireland keenam bagi tempoh sembilan tahun .
Slim Pickings , yang mendahului perlumbaan di pagar kedua yang terakhir , telah dikalahkan oleh Silver Birch pada lompatan terakhir .
Silver Birch kemudiannya mendapat cabaran pada saat terakhir dari McKelvey menghampiri garisan penamat .
McKelvey tiba di tempat kedua dengan 12-1 , sementara Slim Pickings tamat di tempat ketiga dengan 33-1 dan Philson Run di tempat keempat dengan 100-1 .
Numbersixvalverde , pemenang perlumbaan tahun 2006 , telah tamat pada tempat keenam sementara pemenang pada tahun 2005 Hedgehunter telah tamat pada tempat kesembilan .
kegemaran bersama 8-1 Point Barrow , Joes Edge dan Monkerhostin telah gagal untuk menghabiskan perlumbaan , dengan Point Barrow gagal di pagar pertama .
juara semasa Premier Schoolboys Sunshine Coast Pertama XV telah melepasi Kolej Christian Nambour dengan tujuh mata ke atas lima di Kelab Ragbi Nambour pada hari Rabu .
mereka telah layak pusingan separuh akhir sebelum pusingan tersebut .
perlawanan itu telah dipindahkan dari Universiti tersebut kerana cuaca lembap baru-baru ini yang menyebabkan tanah dimasuki air .
Grammar telah mendapat satu percubaan pertukaran separuh jalan semasa masa pertama .
sepuluh minit kemudian , Nambour boleh menjaring tetapi gagal untuk menyudahkannya .
mereka berlawan dengan lasak untuk sepuluh minit kemudian , tetapi gagal untuk mengambil kesempatan dari peluang yang dicipta mereka dan kesilapan Grammar .
Grammar kini bermain di premiers minor Sekolah Tinggi Mountain Creek State di sebuah perlawanan semula bagi separuh akhir tahun 2007 mereka , sementara Kolej Katolik Siena akan menyambut Kolej Anglican Matthew Flinders di separuh akhir lain .
calon-calon Republikan bagi Presiden Amerika Syarikat Newt Gingrich dan Rick Perry telah gagal untuk layak bagi membuang undi untuk pilihanraya primer Virginia , yang dijadualkan pada 6 Mac , Super Selasa .
Gingrich , bekas Pengerusi Dewan Rakyat Amerika Syarikat dan Perry , Gabenor Texas , tidak menghantar 10,000 tandatangan , dengan sekurang-kurangnya 400 dari setiap sebelas daerah kongres negara , kepada lembaga pilihanraya negara sebelum tarikh tutup jam 5 : 00 petang Khamis lalu yang diperlukan untuk memperoleh kebenaran untuk membuang undi , menurut Parti Republikan Virginia .
kempen Gingrich dan Perry kedua-duanya mendakwa mempunyai tandatangan lebih dari yang diperlukan , masing-masing 11,050 dan 11,911 .
para sukarelawan telah menghabiskan malam semalam untuk menyemak petisyen yang dihantar dan mengesahkan semua tandatangan .
dilaporkan Rick Perry sedang mempertimbangkan satu rayuan untuk penilaian .
di antara calon utama yang lain bagi pencalonan presiden Republikan tahun 2012 , bekas Gabenor Massachusetts Mitt Romney dan ahli kongres Texas Ron Paul telah menghantar petisyen yang diperlukan dan layak untuk membuang undi .
pada hari Khamis , calon Michele Bachmann dan Rick Santorum didedahkan turut gagal untuk mendapat kebenaran membuang undi .
menurut pengurus kempen Gingrich , Michael Krull , bekas Pengerusi Dewan merancang untuk bertanding di primer Virginia , walaupun tidak mendapat kebenaran membuang undi , sebagai calon bertulis .
Krull menyalahkan satu " sistem yang gagal " untuk ketidakupayaan kempen itu untuk mendapat kebenaran membuang undi .
pengurus kempen Rick Perry berkata dia kecewa dengan kegagalan kempen untuk layak bagi membuang undi .
menurut undian terkini dari 489 pengundi Republikan oleh Universiti Quinnipiac , Gingrich mendahului dengan sokongan 30 % , diikuti oleh Mitt Romney sebanyak 25 % dan Ron Paul sebanyak 9 % .
oleh kerana wakil Virginia ke Konvensyen Kebangsaan Republikan tidak dianugerahkan dasar pemenang akan mengambil kesemuanya , calon-calon selain pemenang utama negara turut menerima wakil-wakil dari negara .
agensi akhbar rasmi Korea Utara melaporkan bahawa negara itu telah siap mengeluarkan semua batang bahan api nuklear yang telah digunakan , lebih 8,000 kesemuanya , dari reaktor utama di loji nuklear Yongbyon .
semua batang itu boleh diproses semula untuk beberapa bulan bagi menyari plutonium gred-senjata .
para pengawai berkata yang semua batang itu mampu menyediakan plutonium yang mencukupi bagi membuat dua bom nuklear .
ini mungkin menjadi tanda yang Korea Utara sedang bersiap sedia untuk ujian senjata nuklear .
Korea Utara mungkin telah mempunyai bahan yang mencukupi bagi membuat enam bom nuklear .
Korea Utara turut mengumumkan rancangan untuk terus menjalankan operasi fasiliti Yongbyon itu , dan juga memulakan pembinaan reaktor yang lebih besar .
hasil dari kehendak penguna yang banyak , Penerbangan British telah mengumumkan semalam yang ia akan menjalankan tiga lagi penerbangan mingguan bagi laluan dari Bucharest ( Henri Coanda Antarabangsa ) ke London ( Gatwick ) .
penerbangan Bucharest-London itu akan berjalan pada hari Isnin , Khamis dan Sabtu , sementara penerbangan dua hala akan berjalan pada hari Rabu , Jumaat dan Ahad .
penerbangan tambahan ini bermaksud Penerbangan British kini akan terbang dari Bucharest ke London , dan kembali , sepuluh kali seminggu .
pemandu Renault Fernando Alonso telah memenangi Grand Prix Televisyen Jepun Fuji FIA Formula-1 2006 di Perlumbaan Suzuka Antarabangsa .
walaupun pemandu Ferrari Felipe Massa dan Michael Schumacher telah memulakan perlumbaan dari barisan pertama , Alonso berjaya memintas kedua-dua pelumba Toyota itu di bahagian pertama perlumbaan dan Massa selepas hentian pit .
selepas itu Alonso mula menghampiri Michael Schumacher dan mendekatkan jarak kepada hampir 5 saat .
kegagalan enjin telah memaksa Schumacher untuk menghentikan kereta selepas terowong pada pusingan 36 dan warganegara Sepanyol itu memecut ke kemenangan ketujuhnya bagi musim ini .
Giancarlo Fisichella , ahli pasukan Fernando , mempunyai permulaan yang buruk , tetapi memecut melalui Toyota dan tamat di belakang tempat kedua iaitu Filipe Massa .
pemandu Toyota Jarno Trulli dan Ralf Schumacher hilang lebih banyak posisi , apabila pemandu Honda Jenson Button dan pemandu Mercedes McLaren Kimi Raikkonen menyelinap di hadapan mereka dan masing-masing tamat di tempat ke-4 dan ke-5 .
situasi kejuaraan pemandu menjadi lebih kritikal buat Schumacher , yang hilang 10 mata di penghujung minggu ini .
hanya satu peluang tinggal untuk Schumacher bagi memenangi gelaran juara kelapannya - jika dia menang peringkat akhir Grand Prix Brazil 2006 dan Alonso tidak memperoleh sebarang mata .
" saya perlu nyatakan dengan jelas yang saya tidak percaya kepada kejuaraan lagi , " merupakan reaksi Schumacher .
tinggal satu lagi perlumbaan untuk tempat ketiga dalam kejuaraan pemandu , dimana Massa mempunyai satu mata mendahului Fisichella .
di dalam kejuaraan pengeluar Renault mempunyai 9 mata di hadapan Ferrari .
seekor gajah sarkas telah berjaya melarikan diri dari jurulatihnya pada malam hari Ahad di bandar Zurich , Switzerland sebelum ditangkap semula oleh polis tempatan dan penjaga haiwan sarkas .
gajah betina berusia 26 tahun itu , yang dinamakan Sabu , ialah dari Zirkus Knie Switzerland .
ia mampu melarikan diri sejurus sebelum dimasukkan ke dalam treler , ketika penjaga tidak memberi perhatian kepadanya .
sekitar 1930 waktu tempatan ( 1730 UTC ) , Sabu telah dilihat mengharungi Tasik Zurich untuk masa yang seketika sebelum berjalan kembali ke jalan bandar .
polis Zurich berkata yang Sabu telah merayau-rayau di sepanjang lebuh Bahnhofstrasse di Zurich , yang dikenali sebagai pusat membeli-belah paling ekslusif di bandar itu .
ia turut melalui Zurich Hauptbahnhof ( stesen kereta api utama bandar tersebut ) dan Paradeplatz , sebuah medan di Bahnhofstrasse , di mana ada ibu pejabat kedua-dua kumpulan Kredit Suisse AG dan UBS AG .
untuk hampir dua jam , polis telah mengejar gajah itu di sekitar bandar tersebut sebelum ia akhirnya ditangkap semula secara aman di seksyen Talstrasse di Zurich .
para pengawai sarkas dan polis telah mengikut Sabu , tetapi seorang jurucakap sarkas berkata yang ia tidak memberi respon kepada panggilan mereka .
Sabu turut dikatakan bergerak dengan amat pantas sehingga polis mempunyai kesusahan menghampirinya .
di sekitar jam 2000 waktu tempatan ( 1900 UTC ) , seorang penjaga telah berjaya mengawal haiwan tersebut dan memasukkannya ke dalam trak untuk membawanya ke Winterthur , di mana haiwan sarkas lain berada .
tidak ada laporan sebarang kerosakan atau kecederaan semasa kejadian itu , dan walaupun polis menahan orang ramai yang melihat , sekurang-kurangnya seorang yang berada di tempat kejadian berjaya merakam video kejadian itu .
pihak sarkas berkata yang Sabu mungkin telah melarikan diri setelah ditakutkan oleh ribut berdekatan Zurich .
selepas kembali ke sarkas , ia dikatakan dalam kepenatan , tetapi " gembira untuk kembali . "
pemuisi Welsh Dannie Abse ( 81 ) dan isterinya Joan ( 78 ) telah terlibat di dalam satu kemalangan kereta semasa memandu dari Golders Green ke rumah percutian mereka di Ogmore-di tepi Laut , South Wales .
Puan Abse meninggal dunia dengan serta-merta ; En . Abse mengalami tulang rusuk patah .
pasangan itu sedang pulang dari bacaan puisi yang diberikan mereka .
Dannie Abse ialah seorang penulis Yahudi terhormat yang tinggal di Glamorgan , South Wales .
Joan Abse , isterinya , merupakan seorang ahli sejarah seni dan penulis .
Dannie Abse dikenali sebagai seorang pemuisi dan seorang doktor perubatan .
Abse , sebenarnya , seorang pakar di klinik dada untuk lebih tiga puluh tahun .
tetapi Abse paling dikenali untuk tulisannya dan telah menerima banyak anugerah sastera dan kedoktoran .
pada tahun 1989 , dia telah menerima ijazah kedoktoran dari Universiti Wales .
pasangan itu telah berkerja bersama semasa menyunting dua buah buku pada 1980an .
Joan Abse meninggalkan suaminya , seorang anak lelaki , dan dua orang anak perempuan .
kumpulan ekstremis Palestin Hamas telah dijemput untuk bertemu dengan wakil kerajaan Afrika Selatan .
Hamas telah memenangi pilihanraya majlis undangan Palestin pada Januari 2006 dengan kemenangan majoriti dan kini sedang menghadapi pembentukan sebuah kerajaan dan hubungan tegang dengan Kesatuan Eropah dan Amerika Syarikat , yang mengklasifikasikannya sebagai organisasi pengganas yang bertanggung jawab ke atas beberapa serangan bunuh diri .
Timbalan menteri luar negara Afrika Selatan Aziz Pahad mengesahkan pada hari Khamis yang negara itu sedang menyiapkan sebuah mesyuarat dengan kumpulan kontroversi tersebut .
menurut Pahad Afrika Selatan berharap untuk berkongsi pengalamannya dalam transformasi dari era Apartheid ke demokrasi dengan Palestin dan Israel .
Afrika Selatan turut melihat kepentingan untuk kekal berhubung dengan Hamas dalam mencari keamanan di Timur Tengah .
sami Abu Zuhri , seorang jurucakap Hamas berkata bahawa masih belum lagi ada tarikh untuk perbincangan dengan Afrika Selatan .
Russia telah menjemput pemimpin Hamas untuk perbincangan , yang akan bermula pada hari Jumaat .
