tidak ada margin selesa dalam mara ke Homestead , kerana apa-apa sahaja boleh berlaku .
jadi bagi saya - Phoenix adalah landasan perlumbaan yang berubah-ubah bagi saya - saya harus benar-benar fokus pada hari latihan untuk mendapatkan apa yang saya perlukan , untuk memberikan [ ketua kru ] Mike [ Ford ] maklumat yang saya perlukan - hanya 100 peratus menumpukan perhatian adalah apa yang boleh saya lakukan .
tetapi seperti yang saya katakan , saya tidak akan berfikiran konservatif jika saya mempunyai pilihan .
saya akan ingin mencapainya sejauh yang mungkin sebelum kami sampai peringkat Homestead .
England menewaskan Paraguay 1-0 dalam pertembungan sengit di antara bayang-bayang Arena Commerzbank , Frankfurt , Sabtu .
dalam cahaya matahari dan haba , yang mencapai 30 darjah Celsius , ia menjadi satu permainan fizikal yang menyaksikan tiga tempahan dan pengadil kerap meniup wiselnya .
England mendapat pemarkahan permulaan yang sempurna selepas hanya 3 minit dari tendangan percuma David Beckham .
bergerak ke dalam dari sebelah kiri padang , bola itu memukul kepala kapten Paraguay Carlos Gamarra dalam menuju ke jaring .
kedua-dua pihak kelihatan gementar dan tiada pihak menguasai bahagian tengah padang .
hantaran bola kerap disalahletak dan serangan dari kedua-dua pasukan kurang mantap .
Paraguay kehilangan penjaga gol nombor satu Justo Villa kerana kecederaan pada minit keenam permainan .
kehilangan Wayne Rooney , boleh dikatakan pemain pasukan itu yang paling mahir , yang kecederaan baru-baru ini walaupun sembuh telah mengetepikannya daripada perlawanan ini , peminat England yang bising di khalayak ramai tiada apa-apa untuk dinyanyikan kecuali kemenangan .
pengurus pasukan England dari Sweeden Sven-Göran Eriksson mempunyai lebih permilikan tetapi gagal menjaringkan lebih daripada satu gol awal .
pada pihak mereka , Paraguay tidak mampu mengambil kesempatan ke atas beberapa kesilapan pertahanan England untuk mendapatkan gol penyamaan .
England akan bertemu dengan Trinidad dan Tobago manakala Paraguay menghadapi tanah air pengurus England , Sweden .
sebuah kereta api Virgin bergerak pada kelajuan tinggi berlanggar dengan sebuah kereta berhampiran Copmanthorpe , Yorkshire , England , membunuh pemandu kereta itu .
kemalangan itu berlaku pada kira-kira 20 : 55 GMT apabila kereta api Kelas 220 / 221 , berjalan pada kelajuan lebih kurang 100mph , melanggar kereta di atas trek itu .
sebahagian dari kereta api itu kemudiannya tergelincir tetapi kekal tegak , berhenti jauh di bawah trek .
pemandu kereta dipercayai terbunuh serta-merta .
polis North Yorkshire berkata , kereta itu telah meninggalkan jalan raya , dilanggar dan melalui pagar dan berhenti di trek itu .
kereta api itu adalah Virgin Voyager 14 : 25 perkhidmatan merentas negara dari Plymouth ke Edinburgh Waverley , mampu mencapai kelajuan sehingga 125mph , tetapi menyahpecut semasa berdekatan York .
landasan antara York dan Leeds telah ditutup selama beberapa jam , melambatkan perkhidmatan lain .
jurucakap Virgin Arthur Leathley memberitahu pemberita bahawa Rangkaian Rail berharap supaya tiga daripada empat landasan dalam seksyen trek itu beroperasi pada pagi Selasa .
satu pengeboman maut hotel di Mogadishu , ibu negara Somalia , telah membunuh sekurang-kurangnya lima belas orang , termasuk tiga menteri Kabinet Somalia , awal hari ini .
letupan itu mensasarkan majlis graduasi universiti yang dihadiri oleh beberapa pegawai kerajaan .
Shamo Hotel telah menganjurkan istiadat majils graduasi untuk Universiti Benadir .
para saksi melaporkan bahawa seorang pengebom berani mati dapat masuk ke tempat itu dengan berpakaian seperti seorang wanita , memakai abaya dan tudung yang lengkap .
penyerang memakai bahan letupan yang diikat pada badannya , tetapi tidak ditepuk-tepuk oleh pengawal keselamatan .
pengarah Hospital Median , Ali Yusuf , mengulas bahawa " empat puluh orang luka terkena serpihan termasuk pelajar dan doktor perubatan , telah dimasukkan ke hospital hari ini .
bekas ahli Kesatuan Mahkamah Islam di tempat kejadian dikenal pasti sebagai pengebom , yang kepala dan mukanya dicukur sepenuhnya , sebagai ahli al- Shabab , kumpulan Islam ultra-konservatif itu dipercayai mempunyai kaitan dengan al- Qaeda .
Menteri Kesihatan Qamar Aden Ali , Menteri Pendidikan Ahmed Abdullahi Waayeel , dan Menteri Pengajian Tinggi Somalia , Ibrahim Hassan Adow terbunuh dalam serangan ke atas Hotel .
Abdulkadir Mohamed Osman , Presiden Pengarah maklumat Somalia , mengulas mengenai kejadian itu .
letupan itu menggegarkan dalaman hotel , membunuh tiga orang menteri dan mencederakan seorang lagi . "
Adow berkhidmat sebagai setiausaha asing untuk pemberontak Kesatuan Mahkamah Islam apabila ia mengambil alih kuasa pada tahun 2006 .
Menteri sukan Somalia juga dilaporkan dimasukkan ke hospital dan dalam keadaan kritikal .
Mohamed Mohamoud , graduan yang menghadiri majlis itu , berkata bahawa dia sendiri melihat mayat menteri kesihatan itu di atas lantai , di samping mayat pegawai-pegawai kerajaan yang lain .
mereka telah belajar di persekitaran yang begitu dasyat , dan hari ini mereka meninggal dunia tanpa bermanfaat daripada pendidikan mereka .
dua wartawan , seorang wartawan Radio Shabelle dan jurukamera TV al- Arabia , juga didapati mati akibat letupan .
Kesatuan Kebangsaan Wartawan Somalia telah mengeluarkan kenyataan mengutuk serangan itu dan menyatakan kemarahan atas kehilangan rakan-rakan mereka .
Somalia merupakan salah satu tempat paling berbahaya di dunia untuk pekerjaan wartawan .
lapan terbunuh di Somalia sejak awal 2009 .
hotel Shamo sering dipilih oleh pegawai-pegawai kerajaan untuk menjadi tuan rumah majlis dan pada satu masa adalah pilihan penginapan popular untuk wartawan asing .
wartawan Kanada Amanda Lindhout dan wartawan foto Australia Nigel Brennan yang dilepaskan baru-baru ini menginap di hotel itu sebelum penawanan mereka tahun lepas .
pihak keselamatan hotel mengatakan bahawa mereka telah diusir dari bilik itu sebelum majlis bermula , pegawai-pegawai keselamatan kerajaan mahu pengendalian tunggal upacara itu .
pegawai-pegawai kerajaan telah menghadiri istiadat graduasi 43 pelajar dari universiti tempatan Universiti Banadir .
angka kematian rasmi akibat letupan itu dijangka terus meningkat , dengan beberapa laporan menunjukkan bahawa lebih daripada 60 orang telah ditemui mati .
serangan itu adalah yang terbaru dalam rentetan kejadian yang menghubungkan al-Shabab kepada taktik pemberontak yang biasa digunakan oleh kumpulan-kumpulan pengganas Islam di bahagian lain dunia .
sehingga kebelankangan ini , pengeboman berani mati adalah satu amalan luar biasa di Somalia .
pada bulan September , al-Shabab mengaku bertanggungjawab untuk serangan berani atas mesyuarat antara pegawai-pegawai kerajaan dan misi pengaman Kesatuan Afrika di Somalia , yang dikenali sebagai AMISOM , yang mengorbankan 17 anggota pasukan pengaman , termasuk ketua komander Burundian .
dua kenderaan yang mengandungi bahan letupan dengan dibenarkan masuk ke pangkalan AMISOM dan seterusnya meletup .
kumpulan pemberontak yang berjuang untuk kawalan negara yang dilanda peperangan terhadap Kerajaan Persekutuan Peralihan yang disokong Barat , yang diketuai oleh bekas pemberontak Islam Sheikh Sharif Sheikh Ahmed .
kumpulan pemberontak menguasai sebahagian besar Somalia selatan dan tengah , serta sejumlah besar kawasan Mogadishu .
kerajaan sedang disokong oleh kehadiran berterusan pasukan pengaman yang terdiri daripada orang Uganda dan Burundi .
kuasa-kuasa AMISOM diberi mandat dengan perlindungan tapak utama bandar seperti lapangan terbang , pelabuhan , dan istana presiden .
Sir Richard Branson , usahawan British yang berjaya , yang lebih dikenali sebagai pengasas jenama Virgin , telah membuat cadangan kepada Canselor British untuk menyelamatkan MG Rover , pengeluar terbesar kereta di England yang tidak terkawal oleh syarikat lain sehingga ia runtuh musim bunga ini , dan juga membantu permintaan minyak yang meningkat pesat .
dia mahu kerajaan British untuk memberikan subsidi kepada pembuat kereta yang merosot supaya ia boleh menjadi pengeluar kereta hibrid pertama di Eropah .
seorang budak lelaki 7-tahun dari Tennessee yang bersemangat untuk mendapatkan lesen memandunya mendapat pendidikan awal apabila dia memutuskan untuk mengambil trak pikap ibu bapanya untuk bersiar-siar dgn kereta yang dicuri itu .
budak itu , yang namanya tidak dipaparkan , teringat untuk memakai tali pinggang keledar dan juga menggunakan lampu isyarat belok apabila sepatutnya .
polis mengejar kanak-kanak itu pada mulanya mereka sangka mereka sedang mengejar pemandu mabuk .
dia tidak boleh tetap di jalannya , " kata Pegawai Josh Laverette .
tetapi apabila trak itu berhenti di hadapan sebuah rumah , polis melihat bahawa ia adalah seorang budak lelaki , murid darjah dua , hampir belum sampai 4 kaki tinggi , memandu kereta .
" dia sangat rendah , dia terpaksa duduk sangat dekat dengan stereng , " kata Laverette .
" setiap kali dia brek , dia akan meninggikan dirinya dengan kaki kiri dan menghentak brek dengan kaki kanannya . "
apabila polis mula bercakap dengan budak itu , yang berjaya meletakkan kereta di hadapan rumahnya sendiri , " Dia berkata sebab dia membawa kenderaan itu adalah kerana dia mahu mendapatkan lesen , " kata Laverette .
" rasanya terdapat lima kereta bandar dan tiga kereta daerah dan polis negeri " yang semuanya mengejar pikap itu , kata Susan Daniel , seorang saksi kejadian itu .
" ia mengejutkan saya kerana kami melihat dia menggunakan lampu isyarat belok dan membelok , dan kita dapat lihat apabila dia lalu bahawa dia memakai tali pinggang keledar , " kata Daniel .
" kemudian kami mengetahui dia adalah seorang kanak-kanak , saya benar-benar terkejut . "
budak lelaki itu didakwa memandu tanpa lesen , mengelakkan diri daripada polis dan meninggalkan tempat kemalangan .
beliau dijangka hadir di mahkamah juvana minggu depan .
akhbar-akhbar Itali La Repubblica dan Corriere della Sera melaporkan bahawa pasukan tentera AS mungkin tidak dimaklumkan mengenai operasi untuk menyelamatkan wartawan Itali yang diculik , Giuliana Sgrena , di mana ejen perisikan Nicola Calipari telah dibunuh oleh tentera AS .
kerajaan Itali mempertikaikan perkara ini , dan telah berkata bahawa AS menyedari sepenuhnya operasi itu pada 4 Mac .
La Repubblica melaporkan bahawa tentera AS menyedari kehadiran ejen perisikan Itali Nicola Calipari , tetapi bukan mengenai butir-butir tertentu misinya .
bercakap dalam akhbar La Repubblica , Jeneral Mario Marioli membantu mereka yang terlibat dalam operasi itu di Baghdad , dengan mendapatkan lencana khas untuk mereka daripada tentera bersekutu semasa ketibaan mereka .
walau bagaimanapun , sebagai timbalan komander angkatan campuran di Iraq , Marioli melaporkan bahawa dia tidak tahu mengenai tujuan Calipari di Iraq , jadi dia tidak boleh memberitahu tentera bersekutu di darat butiran terperinci misi Itali .
menurut La Repubblica , Marioli melaporkan bahawa dia " tidak mempunyai hubungan dengan pegawai-pegawai perisikan AS " sebelum tembakan tersebut .
Republik Rakyat China telah menandatangani satu perjanjian dengan ASEAN untuk menubuhkan kawasan perdagangan bebas terbesar di dunia .
Jepun , Korea Selatan , New Zealand , India dan Australia sedang mempertimbangkan untuk menyertainya .
anggota ASEAN termasuk Myanmar , Laos , Thailand , Kemboja , Vietnam , Filipina , Malaysia , Brunei Darussalam , Singapura dan Indonesia .
dalam tempoh empat tahun lepas China telah menjadi pengimport utama minyak dan komoditi , dan pengeksport utama barangan siap .
China juga telah mengukuhkan hubungan dengan pembekal minyak di Timur Tengah dan Afrika .
pakatan ini menghilangkan sekatan perdagangan dan membuang tarif dari banyak barang import dan eksport .
ia juga membolehkan China untuk terus memanipulasikan nilai mata wang dalam kepentingan sendiri .
Yuan kini di bawah nilai , menjadikan barangan buatan China murah secara buatan bagi pengimport asing .
dinyatakan dalam perjanjian itu adalah niat ASEAN untuk mewujudkan ekonomi bersatu--dan dengan implikasi tatanegara--sama dengan EU .
perjanjian ini akan mengukuhkan peranan China sebagai pusat ekonomi serantau Asia Selatan , dan pada masa yang sama mengukuhkan hubungan antara China dan negara-negara lain di rantau ini dan mengurangkan syak wasangka mereka tentang kuasa besar yang semakin meningkat .
Perdana Menteri Jepun Junichiro Koizumi dan Presiden Korea Selatan Roh Moo-Hyun berasingan menerima kesepakatan dengan 10 negara dalam Persatuan Negara-negara Asia Tenggara , bersetuju untuk melancarkan rundingan awal tahun depan .
Australia dan New Zealand dijangka menandatangani perjanjian yang sama dengan ASEAN sebelum perbincangan berakhir lewat hari Selasa , walaupun ASEAN terus berwaspada terhadap keengganan Perdana Menteri Australia , John Howard untuk menandatangani persetiaan tidak menceroboh .
Howard meredakan kebimbangan ini tetapi berkata dalam rekod bahawa dia berhak untuk bertindak terlebih dahulu terhadap pengganas di negara asing jika mereka mengancam Australia .
pegawai Pakistan telah berkata lima serangan ke atas kawasan kerajaan di seluruh negara telah membunuh sekurang-kurangnya empat puluh orang .
serangan terbaru berlaku lewat pada hari Khamis di kawasan perumahan kerajaan di Peshawar .
pegawai berkata , mereka mengesyaki militan Taliban bertanggungjawab terhadap serangan itu .
pihak berkuasa berkata bahawa keadaan di bandar timur Lahore adalah terkawal , berikutan serangan berasingan di Agensi Siasatan Persekutuan ( FIA ) dan dua pusat latihan polis .
lelaki bersenjata dengan sekurang-kurangnya satu jaket bunuh diri menyerbu bangunan FIA pada tengah pagi .
FIA merupakan agensi yang bertanggungjawab untuk menyiasat perkara berkaitan dengan keganasan dan imigresen .
awal tahun lepas , bangunan itu adalah sasaran bom trak berani mati yang membunuh lebih daripada 20 orang .
" Khabarnya , empat lelaki menyerang bangunan FIA dan laporan awal adalah bahawa kedua-dua mereka telah dibunuh , " kata setiausaha dalam wilayah , Nadeem Hassan Asif Punjab .
tidak lama selepas serangan ke atas FIA bermula , lelaki bersenjata mensasarkan dua pusat latihan polis di pinggir Lahore .
di luar bandar Manawa , lelaki bersenjata mensasarkan pusat yang diserang militan awal tahun ini .
dalam kejadian lain , penyerang dengan jaket berani mati di Bedian memanjat dinding untuk masuk ke dalam Pusat Latihan Elite Force .
ia mengambil masa beberapa jam sebelum pasukan keselamatan dapat mengawal semua kawasan itu .
serangan di timur Pakistan yang berlaku beberapa jam selepas kereta pengebom berani mati mensasarkan sebuah balai polis di sebuah bandar garrison kira-kira sejam perjalanan dari bandar barat laut Peshawar .
bercakap kepada media tempatan , Menteri Dalam Negeri Pakistan Rehman Malik berkata agensi perisikan menjangkakan serangan ke atas kawasan keselamatan di negara ini dan pihak berkuasa akan sentiasa berwaspada .
dia berkata keganasan baru-baru ini menunjukkan militan mahu membawa barisan hadapan dari barat laut ganas Pakistan ke wilayah Punjab .
pada hari Sabtu , militan yang berkaitan dengan Punjab serta kawasan puak Waziristan Selatan , menyerang ibu pejabat tentera Pakistan di Rawalpindi .
pegawai-pegawai perisikan Pakistan percaya bahawa serangan itu adalah reaksi terhadap serbuan tentera di Selatan Waziristan .
tentera dijangka melancarkan serangan besar-besaran ke atas militan Taliban di kawasan bersempadan dengan Afghanistan .
England menewaskan Kenya dengan 7 wickets ( dengan 60 bola berbaki ) dalam perlawanan terakhir Kumpulan C di Piala Dunia di Stadium Beausejour , Gros Islet , Saint Lucia .
England kini akan mara ke peringkat Super 8 .
hujan menangguhkan permulaan perlawanan itu selama kira-kira dua jam , dan oleh itu perlawanan itu hanya mencapai mata 43 dalam keseluruhan permainan .
jualan telefon pintar yang menggunakan sistem operasi Android telah meningkat tiga kali ganda sejak awal tahun 2010 , menurut angka yang dikeluarkan semalam .
penganalisis pasaran GfK berkata bahawa " lebih kurang satu daripada setiap lapan telefon bimbit yang dijual di UK antara April dan Jun 2010 dengan kontrak dikendali Android , berbanding dengan satu dalam 33 secara purata antara Januari dan Mac . "
minggu lepas , Samsung meningkatkan pemasaran untuk peranti terbaru dikendali Android , Galaxy S.
lain-lain peranti yang dikendali Android termasuk Sony Ericsson X10 dan HTC Desire .
Juruanalisis GfK Megan Baldock berkata kepada The Guardian : " angka menunjukkan peningkatan jumlah pengguna kini meminta telefon bimbit Android berdasarkan nama . "
seorang lelaki Ohio yang terlampau gemuk meninggal dunia pada hari Rabu selepas didapati tidak sedarkan diri di rumahnya beberapa hari sebelumnya .
lelaki itu telah duduk di kerusi selama dua tahun dan secara fizikal bersatu kepadanya apabila dia ditemui oleh dua rakan sebilik , seorang daripadanya adalah teman wanitanya .
pihak berkuasa yang tiba di rumah itu di Bellaire dilaporkan menemui lelaki itu duduk di atas air kencing dan najisnya sendiri , yang penuh dengan ulat .
kulit lelaki itu melekat pada kain kerusi baring , kata pegawai-pegawai penguatkuasa undang-undang , salah seorang daripada mereka terpaksa melupuskan pakaian seragam selepas membalas panggilan rumah itu .
dalam usaha mengangkut lelaki itu ke hospital , pegawai terpaksa memotong sebahagian daripada dinding .
Richard Hughes yang dikenali berusia 43 tahun , lelaki itu meninggal dunia selepas dibawa ke Hospital Wheeling di West Virginia .
tuan rumah kediaman itu berkata Hughes , berat 348 paun ( 157 kilogram ) , mula duduk di kerusi itu selepas lututnya mula sakit , dan enggan membangun .
teman wanita Hughes memberitahu polis bahawa dia menyuapkan Hughes kerana dia tidak dapat bergerak .
Jim Chase , seorang pegawai bandar , menelefon bilik itu di mana lelaki itu berkeadaan " sangat kotor , sangat buruk " dan berkata ia " sukar dipercayai bahawa seseorang tinggal dalam keadaan seperti itu . "
Kuwait mungkin membiayai sejumlah besar kerja-kerja awam di Timor Timur , dalam pelaburan bernilai 500 hingga 600 juta dolar , Perdana Menteri Timur Timor berkata hari ini .
José Ramos Horta tinggal hari ini untuk lawatan rasmi ke Kuwait .
" saya mahu memulakan proses rundingan sekarang juga dengan Dana Pembangunan Kuwait bagi pembinaan projek-projek besar untuk jalan raya , jambatan , pelabuhan dan lapangan terbang Timor Timur , " Ramos Horta , Perdana Menteri Timur Timor , berkata .
" bagi projek sebesar ini , yang dijalankan sepanjang beberapa tahun , jumlah wang yang akan dibelanjakan adalah sekitar 500 juta kepada 600 juta dolar atau lebih .
kita sedang tunggu kajian awal yang dilakukan oleh sebuah syarikat India , yang dibayar oleh Kuwait , " kata Ramos Horta .
delegasi Timor Timur terdiri daripada Menteri Kerja Raya , Odete Victor , dan Menteri sumber tenaga & mineral , José Teixeira .
lawatan itu adalah sebahagian daripada jemputan oleh Perdana Menteri Kuwait Nasser Al-Mohammed Al-Ahmed Al-Sabah , dan termasuk mesyuarat dengan Emir Sabah Al-Ahmad Al-Jaber Al-Sabah , putera mahkota Nawaf Al-Ahmad Al-Jaber Al -Sabah , Menteri Luar Negeri Sabah Mohammed Al Salem Al Sabah dan wakil-wakil daripada Dana Pembangunan Kuwait .
ini merupakan lawatan kedua ke Kuwait dalam dua tahun oleh Ramos Horta , sebuah negara yang Perdana Menteri Timur Timor mengekalkan hubungan dengan beberapa ahli keluarga diraja dan kerajaan .
sekumpulan terdiri daripada 19 orang , termasuk orang asli tempatan dan kakitangan Pihak Berkuasa Jalan dan Trafik ( RTA ) , telah disembur pesawat pendebu tanaman di luar bandar Australia hari ini .
mereka berjalan mengikuti laluan yang dicadangkan bagi jalan pintas lebuh raya , mencari kawasan yang mungkin berkepentingan kepada orang-orang Asli .
pintasan lebuh akan menjadi sebahagian daripada Lebuhraya Hume , dekat Coolac di barat daya New South Wales .
polis masih belum mengetepikan anggapan bahawa pendebuan itu adalah disengajakan .
" kami tidak tahu sama ada mereka tahu orang di sana atau tidak jadi kami merayu supaya sesiapa sahaja yang mungkin telah menyaksikan kejadian itu atau mengetahui apa-apa mengenai pesawat pendebu tanaman yang terbang rendah di kawasan itu supaya menghubungi polis , " katanya .
berita tersedia melalui laman web tidak ( seperti tulisan ini ) memperincikan kesan penyemburan itu .
ABC Online melaporkan bahawa juruterbang pesawat itu mungkin menghadapi dakwaan .
letupan di lombong arang batu telah membunuh sekurang-kurangnya 80 orang di bandar Donetsk , Ukraine , sementara 20 orang dilaporkan hilang .
menurut laporan yang dihantar oleh akhbar tempatan dan Jabatan Situasi Kecemasan , 360 pelombong berjaya menaiki permukaan tanah dengan selamat ; 28 orang lain sedang dimasukkan ke hospital , beberapa orang luka terbakar yang teruk .
lombong Zasyadko hampir 1,000 meter dalam , dan 457 orang berada dalam lombong ketika letupan berlaku pada 3 : 11 pagi .
laporan awal menunjukkan bahawa letupan itu disebabkan oleh metana bercampur dengan udara di lombong .
pada waktu petang , lebih daripada tiga puluh pasukan penyelamat telah ditemui di tempat kejadian , memakai topi keras dan tangki oksigen semasa bersedia untuk memasuki lombong .
saudara-mara mangsa berkumpul di sekitar pintu masuk ke lombong , menunggu berita daripada orang tersayang .
Perdana Menteri Ukraine , Viktor Yanukovych , membalas mengenai kejadian ; Presiden negara ini , Viktor Yushchenko , akan melawat kawasan itu Isnin ini .
" saya bersedih dengan Ukraine , " mengisytiharkan orang Ukraine sebagai ketua negara .
dia juga mengkritik kerajaan itu , mengatakan industri perlombongan telah menjadi mangsa " usaha yang tidak mencukupi . "
dengan pemasangan yang usang dan pembinaan yang teruk , Ukraine telah menjadi mangsa pelbagai kemalangan perlombongan pada masa lalu .
menurut anggaran kesatuan , antara 2006 dan 2007 hampir 250 pelombong meninggal dunia dalam kemalangan .
carian Internet ulung Google sedang bersedia menyediakan perkhidmatan percuma VoIP - teknologi yang menjadikannya boleh menjalankan perbualan telefon dengan internet .
teknologi tersedia ada akan dipasarkan atas nama Google , sesuatu yang mengubah keadaan sekarang dengan sepenuhnya .
sumber menunjukkan bahawa Google mungkin akan mula-mula memperkenalkan perkhidmatan telefon kepada pengguna di United Kingdom , tetapi tarikh sebenar apabila perkhidmatan itu akan dilancarkan dan maklumat tepat tentang pelan tersebutmasih tidak diketahui .
Google adalah enjin carian yang berpangkalan di California yang misinya " adalah untuk menyusun maklumat dunia dan menjadikannya boleh diakses dan berguna . "
enjin carian terbesar di web , Google menerima lebih daripada 200 juta pertanyaan setiap hari melalui pelbagai perkhidmatannya .
Zimbabwe telah mengalahkan Australia dengan lima wicket dalam Kumpulan B Kejohanan Dunia Twenty20 2007 di Padang Kriket Newlands , Cape Town , Afrika Selatan .
Australia , yang merupakan juara dunia dalam format 50 over , berjuang terhadap beberapa pemadang dan bowling daripada Zimbabwe .
Elton Chigumbura mengambil 3-20 dan Gary Brent mengambil 2-19 sementara Australia terhad kepada 138 untuk 9 wickets selepas 20 overs .
Brad Hodge adalah batsman Australia yang mendapat paling banyak mata , menjaringkan 35 not out , manakala Andrew Symonds menjaringkan 33 run sebelum dimatikan .
batsman Zimbabwe bermula dengan baik , tetapi Vusi Sibanda telah terbelakangan sebanyak 23 , sama seperti Hakim Chibhabha , Tatenda Taibu dan Stuart Matsikenyeri meninggalkan Zimbabwe pada 70-4 .
hujan lebat mengganggu inning , tetapi perlawanan itu bermula semula dan Brendan Taylor menjaringkan 60 not out semasa Zimbabwe mencapai sasaran dengan satu bola baki dalam akhir masa yang tegang .
pengeluar ubat-ubatan Merck & Co. didapati bertanggungjawab ke atas kematian seseorang mengenai penggunaan ubat tahan sakit Vioxx , menurut satu keputusan juri di mahkamah Texas .
kes plaintif itu , diketuai oleh balu Robert Ernst , yang meninggal dunia pada tahun 2001 akibat degupan jantung tidak teratur dan arteri tersumbat semasa menggunakan ubat Vioxx , telah berjaya dianugerahkan $ 253.4 juta dolar .
Vioxx telah ditarik balik dari kedai pada tahun 2004 selepas satu kajian mendapati ia boleh menggandakan risiko serangan jantung atau strok jika diambil untuk lebih daripada 1.5 tahun .
walau bagaimanapun , agensi kerajaan AS , FDA , memutuskan pada bulan Februari tahun ini untuk membolehkan produk kembali di rak .
harga saham Merck turun 10 % dalam beberapa minit keputusan itu diumumkan , dan terus jatuh dalam beberapa jam selepas itu .
terdapat lebih daripada 4,200 tuntutan mahkamah Vioxx yang lain yang belum selesai di seluruh AS .
pengeluar wain Moldovan mendapat masa tiga pingat perak pada pertandingan merasa wain dan penilaian minuman keras yang kuat antarabangsa tahunan ketiga , " Concours Mondial de Bruxelles 2008 . "
sebelum ini , acara itu diadakan di Portugal dan di Maastricht pada tahun 2007 dan akan diadakan di Sepanyol tahun depan .
pingat itu diperolehi oleh wain yang dihasilkan oleh syarikat saham Acorex Wain Holding , Amaro de la Valea Perjei 2003 , Pinot Grigio / Aligote / Sauvignon Blanc 2005 dan Pinot Noir 2005 , dengan dua terakhir daripada siri rizab Persendirian .
edisi keempat belas pertandingan tahun lepas , diadakan di Belanda pada tahun 2007 , wain Moldovan memenangi tiga pingat emas dan tiga perak .
ahli Parlimen British dalam Jawatankuasa Audit Alam Sekitar Dewan Rakyat memberi amaran bahawa Britain mungkin menghadapi bekalan elektrik terputus yang meluas jika kapasiti penjanaan baru tidak ditambah tidak lama lagi .
kaedah penjanaan bersih dan boleh diperbaharui akan diutamakan dalam kajian tenaga Kerajaan , termasuk kembali ke penjanaan kuasa nuklear .
tetapi jawatankuasa itu memberi amaran bahawa tiada loji kuasa nuklear baru dijangka berfungsi dalam talian sehingga sekurang-kurangnya tahun 2017 dengan rangkaian yang dicadangkan itu tidak mencapai kapasiti penuh sehingga selewat 2030 .
sementara itu hampir satu perempat kapasiti penjanaan semasa Britain dijadualkan akan di luar talian sebelum tahun 2016 , mewujudkan kekurangan yang digambarkan oleh jawatankuasa itu sebagai " jurang generasi " yang tidak boleh dikurangkan oleh tenaga nuklear .
" pelaburan sangat besar dalam penjanaan kapasiti baru dan kecekapan tenaga akan diperlukan supaya lampu terus bernyala , " kata Pengerusi Jawatankuasa Konservatif Ahli Parlimen Tim Yeo .
Jawatankuasa itu menyatakan bahawa " banyak " program pembinaan stesen tenaga gas baru akan diperlukan untuk memenuhi kekurangan yang diramal .
kenyataan jawatankuasa itu mendapat sokongan daripada pencinta alam sekitar dan juga dari beberapa industri sektor tenaga .
Friends of the Earth telah berhati-hati bersorak dengan komitmen jawatankuasa untuk kecekapan tenaga , dan sokongan pelepasan dikurangkan .
" ... orang ramai memahami tenaga boleh diperbaharui adalah perkara penting akan datang dan kita harus meneruskannya , " kata Maf Smith , Ketua Pegawai Eksekutif Tenaga Boleh Diperbaharui Scotland kepada BBC .
Lower Saxony , Jerman pihak berkuasa cukai memindahkan 12,000 komputer meja untuk menggunakan SuSE Linux dengan KDE sebagai persekitaran atas meja .
sistem itu akan dihijrahkan dari Sun ' s Solaris x86 versi 8 , yang telah digunakan dalam organisasi itu sejak tahun 2002 .
menurut Eva Brucherseifer , presiden masyarakat KDE di Jerman dan Pengarah Urusan basysKom , proses penghijrahan dalam " fasa puncak " dan sedang mengalih 300 sistem setiap hari .
Interpol telah mengeluarkan " Notis Orange " untuk pemimpin Asia Tenggara Jemaah Islamiyah , Mas Selamat bin Kastari , yang melarikan diri dari pusat tahanan pada hari Rabu .
Menteri Dalam Negeri Singapura Wong Kan Seng memberitahu Parlimen bahawa " kesilapan keselamatan " menyebabkan pelarian diri Mas Selamat .
sementara menunggu untuk melawat keluarganya , Mas Selamat melarikan diri dari pusat tahanan Jabatan Keselamatan Dalam Negeri Whitley Road tidak lama selepas waktu tempatan 4 petang selepas diberi kebenaran untuk menggunakan bilik air .
pelarian diri menyebabkan Encik Wong meminta maaf atas kejadian itu dan permulaan pemburuan polis di seluruh pulau untuk Selamat .
" dalam perkara pelarian diri , beberapa jam pertama sangat penting , " kata Jean-Michel Louboutin , pengarah eksekutif perkhidmatan polis Interpol .
" negara Singapura telah melaksanakan semua yang yang perlu dilakukan .
ia adalah sebuah negara yang kecil , jadi ia mudah untuk dilalui dan pergi . "
selamat , bekas mekanik bas berusia 47 tahun dan bapa kepada 5 anak , pernah dituduh berkomplot merampas kapal terbang dan merempuh Lapangan Terbang Antarabangsa Singapura .
dia adalah " seseorang yang mempunyai potensi bahaya fizikal kepada orang lain , tetapi juga potensi bahaya dengan menganjurkan pengeboman masa depan , " kata Louboutin .
Mas Selamat bin Kastari , seorang rakyat Singapura yang lahir di Indonesia dan berketurunan Indonesia , tinggi 158 cm ( kira-kira 5 kaki 2 1 / 4 inci ) tinggi dan berjalan tempang pada kaki kirinya .
selepas " Notis Orange " dikeluarkan , gambar dan cap jari Mas Selamat telah dilepaskan kepada 186 negara anggota Interpol .
sila jangan memadam halaman ini sehingga ditanda untuk penghapusan segera oleh pengguna !
ini adalah untuk demonstrasi penggunaan Wikinews Bahasa Inggeris mengenai Semakan Ditanda kepada pelbagai orang yang bekerja dengan Yayasan itu dalam pelaksanaan Bahasa Inggeris Wikipedia .
pada hari Jumaat , 27 Mei , 2005 , 9 kereta api kereta api bawah tanah New York City akan bergerak untuk kali terakhir , mengakhiri perkhidmatan waktu sibuk dan pemberhentian di stesen tertentu di IRT Broadway - Seventh Avenue Line utara 137th Street-City College .
semasa waktu puncak , 9 adalah tambahan perkhidmatan pemberhentian di stesen tertentu untuk 1 , berjalan laluan yang sama tetapi melangkau beberapa perhentian di Upper Manhattan dan Bronx .
pada masa yang sama , 1 melangkau hentian lain , yang hanya boleh sampai dengan menggunakan 9 pada waktu sibuk ; beberapa hentian boleh sampai dengan menggunakan semua kereta api .
corak perkhidmatan in menghasilkan kereta api yang lebih cepat sedikit , tetapi waktu menunggu yang lebih lama untuk mereka yang pergi ke atau dari stesen dilangkau .
perkhidmatan 9 telah dimulakan pada 12 Disember 1988 , pada mulanya berjalan pada waktu sibuk dan tengah hari .
sebuah kereta api , yang berjalan pada kelajuan tinggi , membawa lebih daripada 850 penumpang apabila ia merempuh sebuah kereta api kosong berhampiran Rio de Janeiro .
kereta api kosong itu sedang dalam proses untuk dipindahkan antara set trek .
pegawai kini menganggar angka kematian adalah lapan , dan sekurang-kurangnya 70 orang lain cedera ringan .
" kita perlu menggunakan penunu bagas untuk membuka dua belah kereta kereta api untuk mencapai penumpang , " kata Pedro Machado , komander jeneral Jabatan Bomba Rio de Janeiro .
" keutamaan kami adalah untuk memberikan sokongan kepada mangsa , penumpang terperangkap di dalam bangkai , dan mengurangkan jumlah mangsa maut , " kata Kolonel Souza Filho , ketua Jabatan Pertahanan Awam Rio de Janeiro dalam satu temu bual dengan rangkaian TV Globo .
" mereka mempunyai keretakan pada tangan mereka , muka mereka , di mana-mana sahaja , " kata Marcos de Souza , Pengarah Hospital Posse dalam satu temu bual televisyen .
dia berkata hospital itu memang mempunyai wad kecemasan yang besar tetapi mereka membawa masuk kakitangan tambahan untuk merawat mangsa perlanggaran .
enam organisasi media , termasuk Fairfax , adalah pelekap satu cabaran perlembagaan untuk perbicaraan rahsia dalam percubaan keganasan akan datang di Australia .
perbicaraan itu melibatkan lelaki Sydney Faheem Khalid Lodhi , yang didakwa melakukan perbuatan dalam persediaan untuk serangan pengganas .
Lodhi dituduh bersubahat dengan suspek keganasan Perancis Willie Brigitte untuk menyerang pengkalan tentera Sydney dan rangkaian bekalan elektrik .
peguam Negara Persekutuan Phillip Ruddock akan mengeluarkan sijil untuk mengelakkan maklumat dinilai sebagai sensitif daripada sampai orang ramai dalam perbicaraan Lodhi ini .
peguam Negara Persekutuan mempunyai kuasa untuk melakukannya di bawah Akta Maklumat Keselamatan Negara ( Jenayah dan Prosiding Awam ) .
Alasan-alasan untuk cabaran ini adalah bahawa undang-undang Maklumat Keselamatan Negara melanggar pengasingan kuasa eksekutif dan kehakiman , yang dikehendaki oleh perlembagaan Australia .
Tom Blackburn , Penasihat Kanan Undang-undang , peguam yang mewakili kumpulan media meningkatkan cabaran mendakwa bahawa perbuatan itu membolehkan eksekutif persekutuan untuk menceroboh ke dalam perkara-perkara kehakiman dengan memerintah bahagian perbicaraan itu perlu dirahsiakan .
cabaran itu akan dibicarakan pada 31 Januari 2006 oleh Hakim Anthony Whealy Mahkamah Agung NSW .
dalam perbicaraan Lodhi ini , ke arah akhir bulan Disember Hakim Anthony Whealy memutuskan bahawa bukti dan perkara sebelum perbicaraan yang perlu kekal dirahsiakan .
seorang hakim persekutuan memutuskan pada hari Isnin bahawa kontroversi pil pencegah kehamilan Pelan pil B perlu disediakan tanpa preskripsi kepada kanak-kanak perempuan seawal usia 17 , memetik kesediaan Pentadbiran Makanan dan Ubat-ubatan ( FDA ) untuk mengalah kepada pengaruh konservatif pentadbiran Bush dengan menetapkan had umur kepada 18 pada tahun 2006 .
pelan B , yang boleh didapati di Amerika Syarikat sejak tahun 1999 , terdiri daripada dua pil yang direka untuk mencegah penghamilan dan mesti diambil dalam masa 72 jam selepas hubungan seks .
hanya sejak 2006 , kini ia boleh didapati tanpa preskripsi , berikutan kempen Pertubuhan Kesihatan Sedunia dan Persatuan Perubatan Amerika .
pada masa ini ubat ini hanya boleh didapati tanpa preskripsi untuk wanita yang berumur 18 ke atas .
tuntutan mahkamah itu difailkan pada tahun 2005 oleh Pusat Hak Reproduktif .
dalam keputusan itu , hakim menyalahkan FDA kerana mengalah kepada " pertimbangan politik " dan melambatkan kelulusan had umur baru .
Susan F. Wood , bekas pengarah kesihatan wanita di FDA , meletak jawatan pada tahun 2005 kerana membantah pengendalian agensi dadah .
" apa yang berlaku dengan Pelan B menunjukkan bahawa agensi itu tidak mengikut jadual , dan tidak dibenarkan menjalankan tugasnya dengan baik , " katanya .
majlis Penyelidikan Keluarga , sebuah pertubuhan konservatif , berkata hakim itu telah mengalah kepada " ideologi politik yang mempromosikan lesen seks untuk remaja . "
FDA berkata ia sedang mengkaji semula keputusan itu , yang mempunyai tiga puluh hari untuk mematuhinya .
satu bom dengan berat 600 paun yang ditemui di Ireland Utara telah dimatikan oleh pasukan pemusnah bom .
bom itu ditemui di tepi jalan berhampiran perkampungan Forkhill di Daerah Armagh , Ireland Utara , berhampiran sempadan dengan Republik Ireland .
ia telah dimatikan oleh pasukan pakar pemusnah bom dari Tentera Darat Ireland .
bahan letupan itu adalah buatan sendiri dan berat 600 paun ( 270 kg ) .
adalah dipercayai bahawa bom itu ditanam di sana oleh penentang republikan .
perkhidmatan Polis Ireland Utara mempercayai bahawa mungkin terdapat satu " hasil yang amat buruk " - dan mereka juga mungkin adalah sasaran pengebom .
ketua Inspektor Sam Cordner berkata : " tindakan penjenayah pengganas dalam menanam peranti ini di kawasan Forkhill merisikokan rakyat dan pegawai polis tempatan . "
" sasaran mereka mungkin adalah polis , tetapi mereka tidak peduli siapa mereka bunuh atau cederakan . "
" hanya melalui kerja susah dan profesionalisme pegawai-pegawai polis dan rakan-tentera mereka bahawa kawasan itu telah dijadikan selamat , " kata Cordner .
20 orang terpaksa meninggalkan kediaman mereka sementara bom itu selamat dimatikan .
pihak berkuasa mengambil peranti dan akan menjalankan pemeriksaan forensik .
sebuah pesawat Hubungan Udara Sudan Selatan terhempas hari ini di Sudan Selatan , membunuh lebih daripada sedozen orang , termasuk menteri pertahanan di kawasan ini .
terdapat laporan bercanggah tentang berapa ramai orang yang berada di atas pesawat itu dan berapa ramai yang mati dalam kemalangan di Bahr Gazal , tetapi sekurang-kurangnya dua puluh orang berada di atas pesawat itu .
sesetengah sumber mencadangkan sembilan belas kematian dan dua terselamat , dan yang lain mengatakan terdapat 26 kematian dan tiada mangsa terselamat ; harus diambil perhatian bahawa jika salah seorang daripada ini adalah betul , maka terdapat lebih daripada dua puluh orang di atas pesawat .
Leftenan Jeneral Dominic Dim Deng , menteri pertahanan kawasan itu , disahkan telah meninggal dan dikatakan sekurang-kurangnya 19 pegawai tentera telah mati .
" pesawat itu telah disewa dari syarikat berkanun dan membawa delegasi pemimpin daripada ( bekas pemberontak ) Pergerakan Pembebasan Rakyat Sudan dari Wau ke Juba ibu negaranya , " kata Luka Mariak , jurucakap presiden Sudan Selatan Salva Kiir .
ini menjadikan perjalanan itu sepanjang kira-kira 450 kilometer ( 290 batu ) , dengan pesawat terhempas di kawasan rata berjarak 375 kilometer ( sekitar 220 batu ) dari Juba .
Bangsa-Bangsa Bersatu berkata , Misi Pertubuhan Bangsa-Bangsa Bersatu di Sudan ( UNMIS ) telah menghantar sebuah helikopter untuk membantu usaha tindak balas kecemasan .
PBB juga berkata , pesawat itu merupakan Beechcraft 1900 dan bahawa mereka akan melibatkan pegawai kerajaan dan pakar penerbangan untuk menjalankan satu siasatan .
Ashraf Jehangir Qazi , Setiausaha Agung Perwakilan Khas UNMIS , mengucapkan takziah kepada kerajaan bagi pihak kedua-dua UNMIS dan PBB secara keseluruhan .
Kiir berkata dalam satu sidang akhbar " Dua puluh satu penumpang terbunuh dan sama ada dua atau tiga anak kapal . "
" dua enjin gagal berfungsi dan tiada apa-apa juruterbang itu boleh lakukan . "
Justin Yak dan isterinya juga disahkan mati .
Yak adalah menteri hal ehwal kabinet sehingga rombakan pada tahun 2007 menggulingkannya .
beliau merupakan penasihat kepada presiden pada masa kematiannya .
mayat-mayat diterbangkan ke Lapangan Terbang Juba di mana saudara-mara menunggu berjam-jam untuk mendapatkan berita .
UNMIS dijangka menerbangkan mayat ke lapangan terbang berdekatan mereka , yang tidak ada capaian awam .
bencana tersebut dianggap sebagai suatu kemalangan yang disebabkan oleh masalah mekanikal .
juruterbang telah menghubungi Kawalan Trafik Udara ( ATC ) melaporkan masalah enjin dan meminta kebenaran untuk menlakukan pendaratan cemas di Rumbek yang berdekatan .
dalam prosiding oleh suruhanjaya tentera Guantanamo di Pangkalan Tentera Laut Teluk Guantanamo Amerika Syarikat pada hari Isnin , Khalid Sheikh Mohammed dan empat pengkomplot bersama tertuduh menyatakan bahawa mereka akan mengakui dan mengaku bersalah terhadap tuduhan mereka hadapi dalam perancangan dan pelaksanaan serangan 11 September pada tahun 2001 .
defendan mengumumkan niat mereka di mahkamah , dan Stephen R. Henley membaca kenyataan mereka .
beliau juga berkata ia adalah " keinginan sungguh-sungguh kami " dan mengaku bersalah dan berkata dia mahu prosiding itu tamat kerana " Saya tidak percaya orang Amerika . "
Mohammed juga melahirkan rasa tidak puas hati bahawa ia mengambil masa lebih sebulan bagi mahkamah itu untuk menyatakan permintaan dakwaannya meminta " sesi perbicaraan segera mengumumkan pengakuan kami . "
di mahkamah dia berkata , " Saya tidak tahu - kerja-kerja tentera menggunakan merpati pengangkut atau apa ? " bercakap dalam bahasa Inggeris .
hakim tidak akan menerima rayuan daripada Binalshibh dan al-Hawsawi , dengan menyuruh supaya perbicaraan kecekapan mental untuk kedua-dua orang itu dijalankan .
Al Hawsawi membantah dan memberitahu hakim bahawa dia berkeputusan untuk mengaku bersalah " dengan semua kapasiti lengkap mental saya dan secara sukarela . "
walau bagaimanapun , Mohammed memberitahu hakim mereka tidak akan membuat akuan mereka tanpa Binalshibh dan al-Hawsawi , " Kami mahu semua orang mengaku bersama-sama . "
selepas penilaian kompetensi , perbicaraan lain akan diadakan , di mana lima orang itu boleh membuat akuan mereka .
pegawai yang mempengerusi Stephen Henley meminta penjelasan daripada pendakwa raya sama ada suruhanjaya ketenteraan boleh " menerima akuan bersalah untuk kesalahan besar . "
perbicaraan hari ini adalah luar biasa dalam bahawa , sebagai tambahan kepada akhbar , keluarga lima orang mangsa 9 / 11 juga hadir .
inisiatif Pembasmian Polio Global telah mengumumkan matlamat untuk membasmi polio di Asia pada tahun 2005 .
projek swasta-awam yang berusia 16 tahun bertujuan untuk menambahkan Poliomyelitis ke atas senarai penyakit kanak-kanak yang telah dihapuskan .
Pertubuhan Kesihatan Sedunia , Rotary International , Pusat Kawalan dan Pencegahan Penyakit A.S. dan UNICEF memimpin Inisiatif itu dan menyelaraskan satu siri kempen imunisasi bertindih di rantau ini .
pada tahun 2004 Afghanistan , India dan Pakistan mengurangkan bilangan kes Polio sebanyak 45 % .
pada tahun 2005 matlamatnya adalah untuk mengurangkan jumlah kes dengan sebanyak 100 % .
ketiga-tiga negara adalah yang terakhir di Asia yang mempunyai endemik polio , dan penyakit ini terhad kepada sebilangan kecil kawasan-kawasan di negara itu .
hanya 186 kes dilaporkan pada tahun 2004 , turun daripada 336 pada tahun sebelumnya .
perintah Strategik tentera Amerika Syarikat ( STRATCOM ) telah berkata bahawa ' bola api ' yang ditemui di kawasan Texas di Amerika Syarikat pada hari Ahad 15 Februari , tidak berkaitan dengan perlanggaran satelit A.S. dan Rusia di angkasa .
menurut spaceweather.com , NASA berkata bahawa objek itu ialah meteor .
" tiada hubungan antara serpihan perlanggaran itu dan laporan kemasukan semula , " kata jurucakap tentera STRATCOM Major Maj. Regina .
" ia adalah satu meteor semula jadi , sudah pasti , " kata Bill Cooke , seorang ahli astronomi di Meteoroid Persekitaran Pejabat NASA .
pada hari Selasa , 10 Februari , satelit komunikasi awam Amerika Iridium 33 , yang dilancarkan pada tahun 1997 , dan satelit komunikasi tentera Kosmos-2251 Rusia yang sudah rosak dan tidak berfungsi lagi , yang dilancarkan pada tahun 1993 , bertembung di Siberia .
pada hari Jumaat 13 Februari , Pentadbiran Lautan dan Atmosfera Negara ( NOAA ) mengeluarkan amaran mengenai jatuh serpihan daripada satelit , berikutan laporan " letupan dan gempa bumi " bersama dengan " kelipan di langit " di Jackson dan Louisville , Kentucky .
kemudian lagi pada hari Ahad , panggilan ke 9-1-1 mula datang ke Daerah Williamson , pejabat syerif Texas sekitar 12 : 30 tengahari ( masa Tengah ) bahawa serpihan yang membakar dan bola api dilihat jatuh dari langit ke bahagian Austin , Houston , Waco dan San Antonio .
" pentadbiran Penerbangan Persekutuan ( FAA ) melaporkan kepada penguatkuasaan undang-undang tempatan pada hari Jumaat bahawa peristiwa ini disebabkan oleh serpihan satelit yang jatuh . "
" kepingan serpihan telah menyebabkan letupan sonik , menyebabkan getaran dirasai oleh beberapa penduduk , serta kilauan cahaya di langit , " kata NOAA pada hari Jumaat dalam amaran maklumat awam yang disiarkan di laman web mereka .
FAA berkata bahan yang terbakar di Texas tidak berkaitan dengan amaran ini .
penduduk di Texas melaporkan rumah dan tingkap mereka bergoncang dan terdapat letupan besar pada pagi Ahad .
selepas pemeriksaan ke atas beberapa kawasan , pejabat syerif daerah Williamson melaporkan tiada serpihan atau kesan hentaman ditemui .
terdahulu laporan yang belum disahkan berkata serpihan itu mungkin adalah hasil daripada letupan kecil pesawat .
terdapat spekulasi sebelum ini bahawa objek itu di Texas mungkin adalah meteor .
doktor Marco Ciocca , seorang profesor di Universiti Kentucky Timur memberitahu WKYT pada hari Ahad adalah terlalu awal untuk serpihan daripada satelit memasuki kembali atmosfera planet .
" [ mungkin mengambil masa ] berbulan-bulan " sebelum mana-mana bangkai satelit itu memasuki atmosfera bumi .
" ia akan mengewap atau tinggal di orbit untuk beberapa ketika sebelum jatuh ke dalam atmosfera bumi . "
walau bagaimanapun , Kesatuan Saintis Prihatin ( UCS ) berkata pada 12 Februari bahawa serpihan itu boleh mengambil 10 hari atau kurang untuk kembali semula ke atas bahagian planet ini .
" dalam tempoh 24 jam selepas perlanggaran , sistem pengesanan ruang Amerika Syarikat telah mengenal pasti 600 keping serpihan . "
" jumlah besar ini menunjukkan bahawa perlanggaran itu mesti bertembung secara berdepan . "
" jika dua satelit itu berlanggar berdepan , dan bukannya satu pukulan yang terkena sipi , tenaga perlanggaran itu akan menghancurkan sama sekali kedua-dua satelit menjadi kepulan serpihan , " kata UCS dalam satu kenyataan di laman web mereka yang juga menambah bahawa perlanggaran itu berlaku di " kawasan sama ruang di mana China memusnahkan satelit cuaca China yang sudah rosak dan tidak berfungsi lagi dengan senjata anti-satelit ( ASAT ) " pada tahun 2007 .
" ujian Januari 2007 menghasilkan sejumlah besar serpihan . "
terdapat sekurang -kurangnya lapan perlanggaran satelit utama sejak 1991 .
satelit itu , yang kedua-duanya mempunyai jisim melebihi 450 kilogram , dan dalam perjalanan pada kira-kira 17,500 batu sejam ( 28,150 km / jam ) , berlanggar pada 491 batu ( 790 km ) di atas bumi .
saintis berkata , letupan yang disebabkan oleh perlanggaran itu sangat kuat .
mereka masih cuba menentukan berapa besar kemalangan itu dan bagaimana bumi akan terjejas .
keputusan analisis plot akan dipaparkan atas laman web awam .
penyelidikan baru yang diterbitkan dalam jurnal Nature Medicine telah menunjukkan hubungan antara gen rosak dan migrain .
ahli-ahli sains berharap penemuan ini akan membawa kepada rawatan pengurusan kesakitan yang lebih baik untuk pesakit , dengan faedah mungkin untuk rawatan sakit secara am .
kejayaan ini melibatkan gen yang dikenali sebagai TRESK , difikirkan mengawal tindak balas otak untuk sakit : jika ia rosak , maka banyak aktiviti dan tindakan normal akan sakit .
penghidap migrain ( difikirkan di United Kingdom sebanyak kira-kira lapan peratus lelaki dan lapan belas peratus wanita ) sering mengadu bahawa cahaya , bunyi dan sentuhan menyebabkan kesakitan .
TRESK mungkin boleh dipengaruhi oleh ubat-ubatan yang akan mengubah titik di mana ia melaporkan rasa sakit , yang akan mengurangkan penderitaan mereka yang mempunyai migrain .
kajian ini melibatkan ahli-ahli sains dari Unit Fungsi Genomics Majlis Penyelidikan Perubatan di Universiti Oxford dan dari Kanada .
mereka melihat DNA 110 orang yang mempunyai migrain dan ahli-ahli keluarga mereka , dan mendapati TRESK merupakan komponen utama dalam migrain .
salah seorang penyelidik Oxford , pakar perunding neurologi Zameel Cader , menyifatkannya sebagai " amat sukar dijumpai " dan berkata bahawa ia mungkin " berpotensi membawa kepada rawatan sakit secara umum . "
sebelum kajian ini , tiada gen pernah dikaitkan secara langsung dengan migrain , walaupun sebahagian DNA yang meningkatkan risiko umum telah ditemui .
migrain dikatakan oleh Pertubuhan Kesihatan Sedunia sebagai penyebab utama hilang upaya di seluruh dunia .
di Britain , dianggarkan bahawa migrain menjejaskan 20 peratus penduduk , dengan kira-kira 190,000 migrain berlaku setiap hari dan lebih 25 juta hari hilang kerja setiap tahun .
Lee Tomkin , pengarah amal pesakit , Migrain Action , menyifatkan berita itu " hebat " dan " benar-benar satu langkah ke depan yang betul-betul hebat . "
profesor Peter Goadsby dari Migrain Trust mengatakannya " arah baru untuk mempertimbangkan terapi baru dalam keadaan yang sangat menghilangkan keupayaan . "
dengan kajian mencadangkan kewujudan kehidupan di Marikh , sistem baru tidak lama lagi akan menyaksikan pelaksanaan .
Paraguay menewaskan Trinidad dan Tobago dalam perlawanan yang tidak mempunyai kesan ke atas kelayakan mara ke pusingan enam belas Piala Dunia Fifa , Selasa .
Paraguay menewaskan permainan itu dari awal hingga akhir dan mendapat gol dalam setiap babak .
Trinidad dan Tobago hanya berjaya menjaringkan dua jaringan untuk mencemaskan Aldo Bobadilla di jaring Paraguay .
Kelvin Jack , yang memulakan perlawanan pertama Piala Dunia Fifanya , berjaya menyelamatkan percubaan sebanyak tujuh kali .
selepas 25 minit Jack ialah seorang pemerhati apabila sepakan percuma Roberto Acuna dipacu kuat ke dalam kotak itu .
pemain pertahanan tengah Jack Brent Sancho secara tidak sengaja mengawal bola itu untuk dimasukkan gol dengan kepala .
gol yang memeterai perlawanan itu untuk Amercians Selatan telah dijaringkan enam minit sebelum waktu tamat oleh Nelson Cuevas selepas dia berbalas hantaran dengan Roque Santa Cruz .
permainan ini terkenal sebagai penampilan terakhir untuk Carlos Gamarra , 35 , untuk pasukan kebangsaannya .
selepas tiga perlawanan jadual Kumpulan B telah diketuai oleh England dengan tujuh mata dan kemudian Sweden dengan lima mata dengan Paraguay dan Trinidad dan Tobago keluar dari perlawanan itu .
majlis Tempatan meminta pada hari Selasa supaya gambar yang ditemui di kawasan yang dipercayai ramai sebagai tapak hotel sebelum ini .
Elmwood Village Hotel yang dicadangkan akan diletakkan di persimpangan Elmwood dan Forest .
penduduk dan pemilik mengesyaki perniagaan di kawasan itu yang hotel itu pernah terletak di tempat sama .
Elmwood Village Hotel adalah pembangunan yang dicadangkan oleh Perbadanan Perkhidmatan Pembinaan Savarino .
selepas beberapa kajian , seorang wartawan bebas yang menulis untuk Wikinews menentukan tidak pernah ada sebuah hotel di tapak yang dikatakan Elmwood Village Hotel .
walau bagaimanapun ; terdapat sebuah hotel sementara di penjuru timur laut Elmwood dan Hutan .
Buffalo adalah tuan rumah Ekspo Pan-Amerika dari 1 Mei hingga November 2 , 1901 .
ia adalah satu pameran yang direka untuk mempamerkan teknologi terkini , termasuk elektrik .
terdapat pertengahan jalan , acara sukan , dan mempunyai kampung Afrika , Eskimo , dan Mexico .
walau bagaimanapun ; acara yang mungkin paling terkenal yang berlangsung di pameran itu ialah pembunuhan Presiden William McKinley pada masa itu pada 6 September 1901 .
dia ditembak oleh Leon Czolgosz di luar Temple of Music dan meninggal lapan hari kemudian ketika di rumah John Milburn di Delaware Avenue di Buffalo .
dalam masa yang singkat kemudian , Theodore Roosevelt dilantik pada September 14 , 1901 di Rumah Wilcox di Delaware Avenue di Buffalo .
pada masa itu beberapa hotel dan rumah sewa telah dibina di sekitar pameran itu termasuk The Elmwood di 717 Elmwood , Hotel Elmhurst di Forest dan Lincoln Parkway , Hotel Gibbs 1005-1021 Elmwood , R. Palmerton Merritt di 441 Forest dan The Norman di 422 Forest .
mungkin hotel yang paling terkenal yang dibina pada masa pameran itu adalah Hotel Statler Pan-American yang dibina oleh Ellsworth Milton Statler .
seorang wartawan bebas yang menulis untuk Wikinews telah mendapat satu-satunya salinan gambar hotel itu [ gambar di atas ] .
hotel ini terletak di penjuru timur laut Elmwood dan Forest Avenues di Buffalo , mempunyai 2,100 bilik tidur dan penginapan untuk 5,000 orang .
pada masa itu , Statler adalah hotel terbesar [ berdasarkan bilangan bilik ] yang pernah dibina .
ia mempunyai tiga tingkat , ditampal plaster di bahagian dalam , sebahagian besar diperbuat daripada kayu dan telah ditutup dengan tongkat hiasan di luar , yang menjadikannya separuh tahan api .
setiap bilik adalah bilik di luar dan terang-benderang dan mempunyai pengudaraan yang baik .
ia terletak di dalam satu lorong di pintu masuk utama pameran ini .
Statler dibina untuk hanya satu perkara , pameran itu .
kerja bermula pada tahun 1900 dan selesai hanya sebelum permulaan pameran itu .
apabila pameran itu berakhir pada bulan November , hotel itu diturunkan .
peta dari tahun 1894 menunjukkan tiada hotel , apatah lagi sebarangan bangunan atau rumah di persimpangan itu .
walau bagaimanapun ; kajian itu menunjukkan bahawa rumah 1119-1121 Elmwood , bangunan-bangunan yang akan dirobohkan untuk membina Elmwood Village Hotel , dibina pada masa sebelum 1915 tetapi tidak berada di persimpangan itu sebelum tahun 1902 .
berdasarkan kajian yang dilakukan di Persatuan Sejarah Buffalo , telah diputuskan bahawa antara tahun 1890 dan 1902 , tiada hotel utama lain wujud di kawasan itu .
malah , kajian telah menunjukkan bahawa hampir setiap hotel yang dibina di kawasan itu , hanya wujud pada zaman pameran itu .
penyelidikan juga menunjukkan sebuah hotel atau rumah rawa di 1089 Elmwood sekitar tahun 1901-1903 .
satu-satunya nama hotel itu yang diketahui adalah Hotel John C. Hill .
hotel itu pada masa itu terletak di dalam rumah yang kini dikenali sebagai Atwater House .
rumah ini adalah rumah pertama yang dibina di sebelah timur lorong itu .
The Atwater House kini kosong dan pemilik Pano Georgiadis mahu merobohkannya untuk memperkembangkan restorannya .
rumah ini dibina sebelum tahun 1894 dan pemilik asal dan pembina rumah kini tidak diketahui .
penghuni paling awal yang diketahui adalah Edward Atwater yang pada tahun 1862 mengasaskan syarikat penapisan minyak Atwater & Hawes di Buffalo .
tapak syarikat ini telah baru-baru ini ditemui di Daerah Canal semasa penggalian arkeologi dijalankan .
pada masa ini , penyelidikan semasa tidak menunjukkan apa-apa hubungan antara dua orang lelaki itu .
beberapa bandar di seluruh Texas , Amerika Syarikat telah mula meningkatkan usaha mereka untuk melawan populasi nyamuk , dalam usaha mengurangkan pennularan virus Wes Nile yang kadang-kadang membawa maut .
pegawai-pegawai di daerah Dallas telah mengisytiharkan darurat kesihatan awam .
pegawai di sana telah meminta penggunaan lima kapal terbang , ingin menyembur kebanyakan kawasan North Dallas , begitu juga bahagian-bahagian lain bandar .
Tim Whitley , seorang pegawai bandar di Malakoff , memberitahu Wikinews bandar itu telah mula menggunakan seorang pakar racun perosak untuk menyembur dua kali seminggu .
menurut Whitley , keadaan atmosfera tertentu , seperti kelajuan angin dan kelembapan , mesti berlaku sejurus sebelum semburan skala besar boleh berlaku .
dia menjelaskan dua semburan setiap minggu adalah lebih kerap dari biasa untuk bandar itu .
" tentang masalah di Dallas , kami mengambil perhatian serius , " tambah Whitley .
malahan dalam cuaca kering yang terdapat di Abilene , nyamuk itu yang diuji baru-baru ini membawa virus itu .
hasilnya , bandar itu telah meningkatkan semburan racun perosak .
sumber media menunjukkan lebih daripada 80 kes virus Wes Nile telah dilaporkan tahun ini di daerah Dallas sahaja .
seorang pegawai kanan daerah Dallas memberitahu media dia melihat masalah dengan mengambil perhatian yang serius .
terdapat sembilan kes virus Wes Nile di kawasan Houston , dengan salah satunya diakhiri dengan kematian .
seorang wanita New Jersey yang merupakan bekas pemastautin Lubbock memberitahu media awal bulan ini dia telah menjangkiti virus itu dan percaya dia digigit semasa melawat Austin .
kira-kira 60 peratus kes Wes Nile di Amerika Syarikat berlaku di Texas .
dari segi sejarah , terdapat beberapa bantahan atas semburan udara dan kemungkinan bahaya kesihatan disebabkan penyebaran bahan kimia itu .
satu kajian California , bagaimanapun , menunjukkan bukti di kawasan di mana semburan udara berlaku , jangkitan adalah enam kali kurang berkemungkinan berlaku .
kes-kes awal virus itu muncul di Amerika Syarikat pada lewat tahun 1990-an .
keputusan awal memberikan Presiden Afghanistan Hamid Karzai lebih daripada 50 % undi yang perlu untuk melantik beliau semula dalam pilihan raya presiden baru-baru ini di negara itu .
walau bagaimanapun , selepas spekulasi mengenai penipuan undi selama sebulan , pegawai-pegawai dari Suruhanjaya Aduan Pilihan Raya ( ECC ) yang disokong Pertubuhan Bangsa-Bangsa Bersatu tidak mempercayai undi daripada 210 pusat pengundian .
pemerhati Kesatuan Eropah telah mendakwa bahawa sebanyak satu dalam empat undi mungkin disyaki kesahihannya .
ECC Afghanistan telah menerbitkan sebuah laporan mengenai siasatan mereka terhadap dakwaan yang muncul selepas pilihan raya dua bulan lalu .
EEC telah menyatakan bahawa terdapat " bukti penipuan yang jelas dan menyakinkan " di tempat mengundi di seluruh negara .
semasa ECC melaporkan kepada Suruhanjaya Pilihan Raya Bebas ( IEC ) masih tiada pengumuman rasmi telah dibuat , walaupun berlandaskan undang-undang IEC bertanggungjawab untuk menerima dapatan EEC ; diplomat asing bagaimanapun telah mencadangkan bahawa IEC mungkin tidak akan menerima dapatan tersebut .
Presiden Karzai enggan menerima hasil siasatan itu , yang mengurangkan bahagian undinya daripada sekitar 55 % ke angka di bawah 50 % , yang membawa kepada penjelasan " kebuntuan , " apa yang digambarkan oleh Mohammad Moin Marastyal , salah satu ahli pasukan kempen .
Marastyal mendakwa bahawa EEC sengaja mengubah fakta itu untuk memaksa pilihan raya penentu .
" usaha telah dibuat untuk mengurangkan undi Karzai ke bawah 50 peratus , " katanya .
rancangan Permainan Taipei 2008 , yang dianjurkan oleh Persatuan Komputer Taipei ( TCA ) , berakhir pada hari Isnin , dan berbeza daripada rancangan tahun lalu .
ini dapat dilihat dalam pengaturan populasi permainan , industri , dan pameran .
wilayah Indonesia Aceh dilanda gempa bumi magnitud 7.5 pada 3 : 08 petang waktu tempatan ( 08 : 08 GMT ) .
pusat gempa ialah 319 km ( 198 batu ) di luar pantai Sumatera , berhampiran dengan Pulau Simeulue .
sekurang-kurangnya tiga orang terbunuh dan beberapa bangunan rosak .
rantau yang sama telah dilanda gempa bumi pada tahun 2004 , yang mencetuskan tsunami .
menurut penduduk tempatan gempa bumi itu berlangsung kira-kira satu minit dan dirasai di Banda Aceh , ibu kota wilayah itu , kira-kira 300 km ( 185 batu ) jauhnya , juga di Meulaboh dan Gunung Sitoli di pulau Nias .
kajian Geologi Amerika Syarikat , yang melaporkan gempa bumi itu , berkata bahawa tiada amaran tsunami pernah dikeluarkan .
beberapa minit selepas gempa bumi itu melanda , Pusat Amaran Tsunami Pasifik mengeluarkan amaran bahawa sebahagian pantai Sumatera mungkin berisiko mengalami tsunami tetapi kemudian amaran itudibatalkan .
agensi meteorologi Jepun berkata rantaian pulau Andaman dan Nicobar di India juga berisiko .
agensi meteorologi dan geofizik Indonesia mencatatkan sekurang-kurangnya dua gempa susulan kira-kira 20 minit selepas gegaran pertama , satu berukuran 5.5 dan 5.3 lain pada skala Richter .
budi Waluyo , seorang pegawai di Agensi Meteorologi dan Geofizik Kebangsaan berkata gempa bumi itu berlaku kira-kira 30 kilometer di bawah tanah .
kajian Geologi Amerika Syarikat mengukur gempa pada magnitud 7.6 dengan skala Richter .
" gempa bumi itu tidak berpotensi menyebabkan tsunami kerana ia berlaku di bawah tanah , bukan laut , " kata Waluyo .
nasib tidak menyebelahi mereka untuk kedua-dua pasukan besbol Straight di mana-mana pihak , kerana China Star dan Uni-President Lions kedua-duanya disingkirkan dalam laluan di Piala Konami 2007 .
perlawanan akhir Piala Konami akan mengambil tempat di antara SK Wyverns dan Chunichi Dragons .
keracunan plumbum telah mengambil nyawa sekurang-kurangnya 163 individu di negeri Zamfara di utara Nigeria beberapa minggu lalu .
kadang-kadang pada bulan Mac penduduk kampung-kampung terpencil mula melombong emas secara haram di kawasan yang mempunyai kepekatan plumbum yang tinggi .
terdapat sejumlah 355 kes dilaporkan , menetapkan kadar kematian pada 46 % .
menurut Henry Akpan , ketua epidemiologi yang berkhidmat di Kementerian Nigeria Kesihatan , 111 daripada 163 kematian direkodkan adalah kanak-kanak , kebanyakannya hanya berusia beberapa tahun .
Akpan juga berkata bahawa pegawai-pegawai pernah melihat anak kecil bermain di dalam air tercemar yang terletak berhampiran tapak perlombongan .
kerajaan telah mendapati melalui program imunisasi tahunan mereka hampir tiada kanak-kanak yang tinggal di kampung-kampung Zamfara .
orang dewasa dari kawasan itu melaporkan bahawa kanak-kanak telah meninggal dunia akibat malaria .
walau bagaimanapun , selepas siasatan , pegawai kesihatan membuat kesimpulan bahawa terdapat sejumlah plumbum yang yang luar biasa besarnya beredar di dalam mayat penduduk kampung .
kerajaan Nigeria telah meminta bantuan daripada pertubuhan-pertubuhan antarabangsa termasuk Pertubuhan Kesihatan Sedunia dan Pusat Kawalan dan Pencegahan Penyakit , dalam mencegah wabak daripada meluas .
Kementerian itu telah pula menganjurkan dua kem untuk penduduk kampung yang mengalami keracunan .
kerajaan Afrika Selatan telah melaporkan bahawa bekas Presiden Nelson Mandela dibenarkan keluar dari sebuah hospital di Pretoria , di mana beliau dimasukkan ke hospital pada 8 Disember .
Mandela menerima rawatan hospital untuk merawati penyakit batu karang dan jangkitan paru-paru .
jurucakap presiden Mac Maharaj berkata Mandela " akan menjalani rawatan rapi di rumahnya di Houghton sehingga dia pulih sepenuhnya . "
Mandela dimasukkan ke hospital selama lapan belas hari , kemasukan ke hospital yang paling lama sejak tahun 1990 , apabila beliau dibebaskan dari penjara selepas 27 tahun .
Presiden sekarang Jacob Zuma melawat Mandela di hospital hujung minggu yang lepas .
Zuma melawat Mandela sekali lagi pada hari Krismas , begitu juga Graca Machel , isteri Mandela .
Mandela telah dimasukkan ke hospital tiga kali sejak awal tahun lalu .
pada bulan Januari 2011 , Mandela menerima rawatan hospital untuk jangkitan pernafasan akut .
bekerja di sebuah kuari batu kapur Pulau Robben , di mana beliau dipenjarakan selama enam belas tahun semasa Aparteid di Afrika Selatan , merosakkan mata dan paru-parunya .
dalam tahun 1980-an , ketika beliau masih seorang tahanan di Pulau Robben , beliau medapat penyakit tersebut .
Maharaj , yang pernah merupakan tahanan politik bersama Mandela semasa Aparteid , menyatakan terima kasih atas sokongan orang ramai dan media dan memberi privasi kepada Mandela .
bagi pihak kerajaan , Maharaj juga meminta " lanjutan privasi bagi membolehkan keadaan terbaik untuk pemulihan penuh . "
menurut Biro Meteorologi , ( BOM ) 2005 adalah tahun yang paling panas sejak pemerhatian suhu boleh dipercayai , dan meluas tersedia pada tahun 1910 .
data yang dikumpul oleh Biro itu menunjukkan suhu purata tahunan Australia bagi tahun 2005 adalah 1.09º C lebih tinggi daripada purata piawaian 1961-1990 .
Biro Meteorologi berkata hasilnya adalah lebih banyak bukti tentang perubahan iklim .
Biro Blair Trewin berkata : " kami telah melihat perkara seperti pengunduran umum garisan salji musim sejuk . "
" kami telah melihat pengurangan ketara dalam kekerapan fros , terutamanya di pedalaman Queensland , " kata Dr Trewin .
" kami telah menyaksikan peningkatan bilangan hari panas yang melampau . "
" semua unjuran kami dapat dari model iklim kami akan menjangka untuk menyaksikan pemanasan berterusan sepanjang abad ke-21 , " katanya .
" angka seperti ini ... adalah satu lagi bukti bahawa perubahan iklim adalah benar dan ia adalah satu isu sebenar . "
meskipun terdapat cuaca sejuk bukan pada musimnya di Barat Selatan Australia Barat , 2005 merupakan tahun panas di kebanyakan kawasan negara itu , dengan Wilayah Utara ( NT ) menerima bahagian yang paling hebat .
suhu maksimum purata dari segi kawasan Wilayah Utara adalah 1.45ºC di atas purata jangka panjang , anomali terbesar mana-mana negeri atau wilayah .
Biro itu berkata sementara perbezaan suhu sebenar dan suhu normal mungkin kelihatan agak kecil , peningkatan suhu sebanyak 1º C dalam suhu purata bersamaan dengan peralihan ke arah utara di banyak bandar di selatan Australia sebanyak kira-kira 100km .
semua Negeri dan Wilayah , selain daripada Victoria dan Tasmania , menjadikan suhu purata tahun 2005 antara dua tahun paling panas dalam rekod .
satu-satunya kawasan yang merakamkan tahun yang lebih sejuk daripada biasa adalah satu jaluran pantai Australia Barat bermula dari Cape Leeuwin ke Carnarvon .
tahun paling panas sebelum ini bagi Australia dalam rekod dipengaruh oleh peristiwa-peristiwa El Nino yang ketara , kata Biro .
walau bagaimanapun , tiada kejadian seperti itu berlaku pada tahun 2005 , menjadikan rekod kehangatan itu lebih luar biasa .
sejak tahun 1979 , kesemua masa kecuali empat tahun telah lebih panas daripada suhu purata di Australia .
suhu Australia telah meningkat kira-kira 0.9º C sejak tahun 1910 - selaras dengan perkembangan pemanasan global .
kajian saintifik telah mengaitkan kenaikan suhu global dan Australia dengan kesan rumah hijau tertingkat .
bulan pada awal tahun 2005 juga sangat kering di kebanyakan kawasan Australia dengan tempoh Januari-Mei yang merupakan waktu kedua kering dalam rekod .
hujan purata dari segi kawasan Australia dikira dari rangkaian sekitar 5000 stesen hujan .
pemerhatian dari rangkaian ini mendedahkan bahawa , jika dibandingkan dengan catatan lepas , Tasmania merupakan negeri paling basah pada tahun 2005 , manakala Queensland dan Australia Barat adalah paling kering .
sejak kebakaran belukar Tahun Baru telah menyebabkan malapetaka di banyak tempat di Australia , dengan rumah-rumah , ternakan ladang musnah .
beribu-ribu hektar hutan belukar dan tanah ladang terbakar .
ahli alam sekitar berkata cuaca adalah pelopor benda akan datang : " tahun 2005 memberi kami sedikit rasa bagaimana hidup akan menjadi jika kami gagal menangani perubahan iklim , " kata Catherine Fitzpatrick dari Greenpeace .
" haba yang melampau dan kebakaran belukar pada Hari Tahun Baru 2006 menunjukkan bahawa ia tidak akan menyeronokkan . "
" jika tindakan tidak diambil tidak lama lagi untuk mengelakkan perubahan iklim bencana , Australia akan mempersalahkan John Howard kerana dia gagal bertindak apabila mempunyai peluang . "
Cik Fitzpatrick berkata kerajaan pusat terhutang budi kepada industri arang batu dan aluminium sama seperti kerajaan Jepun terhutang budi kepada syarikat penangkapan ikan paus , dan dengan kesan yang lebih dahsyat .
" angka hari Ini seharusnya merangsang Menteri Alam Sekitar kami ... untuk tindakan sebenar - mengesahkan Kyoto , menghentikan tenaga arang batu dan menuju ke arah tenaga bersih , boleh diperbaharui , " kata Cik Fitzpatrick .
Menteri Alam Sekitar Persekutuan Ian Campbell berkata dia mengakui perubahan iklim adalah satu cabaran alam sekitar moden yang terbesar .
" saya berpendapat perubahan iklim membimbangkan , " katanya di radio ABC .
" saya menganggap perubahan iklim sebagai cabaran alam sekitar nombor satu ... "
" angka-angka ini menambah kepada kepentingan bukti bahawa perubahan iklim adalah benar dan ia adalah satu masalah dunia perlu bekerjasama untuk berusaha menyelesaikannya . "
Australia dan Amerika Syarikat adalah satu-satunya negara maju yang enggan menandatangani Protokol Kyoto , yang menyeru semua negara supaya mengurangkan pengeluaran rumah hijau sebanyak 5.2 peratus di bawah tahap 1990 sebelum tahun 2012 .
kerajaan berpendapat protokol Kyoto tidak akan berjaya kerana ia tidak melibatkan negara-negara membangun untuk mengurangkan pelepasan .
" ia hanya melibatkan hanya lebih daripada satu pertiga negara-negara di dunia dan ... kita perlu sesuatu yang melibatkan semua negara di dunia , " kata Senator Campbell .
kebanyakan rantau di seluruh dunia juga melaporkan tahun yang amat sangat panas .
menurut anggaran awal yang dikeluarkan oleh Pertubuhan Kajicuaca Sedunia ( WMO ) , suhu purata global bagi tahun 2005 adalah kira-kira 0.48º C di atas paras normal , meletakkan 2005 antara empat tahun paling panas di seluruh dunia sejak catatan dimulakan pada tahun 1861 .
gempa susulan mencapai magnitud 5.9 dengan pusat gempa terletak sembilan belas kilometer barat Pichilemu , menurut Kajian Geologikal Universiti Chile ( UCGS ) .
walau bagaimanapun , Kajian Geologi Amerika Syarikat ( USGS ) melaporkan bahawa ia telah mencapai magnitud 5.8 ; mempunyai kedalaman 8.5 kilometer ; dan bahawa pusat gempa terletak 65 kilometer di barat daya San Antonio , Valparaiso ; 100 kilometer di barat Rancagua , O ' Higgins 105 kilometer di barat laut Curicó , Maule dan ; 135 kilometer di barat daya Santiago , Wilayah Metropolitan .
kumpulan metal terkenal dari Amerika Syarikat , Poison akan menyaman Capitol Records dan EMI Music Marketing atas pemungkiran kontrak .
Poison mendakwa kedua-dua syarikat itu telah membayar mereka kurang royalti untuk bertahun .
kumpulan ini mendakwa Capitol salah mengkategorikan pelbagai rekod jualan dan salah mengira setiap perbelanjaan sejak 1980-an .
mereka mengatakan apabila cuba untuk memeriksa rekod syarikat mereka tidak mendapat kerjasama dan kini meminta hakim untuk memerintahkan syarikat untuk mendedahkan rekod mereka supaya kumpulan ini boleh menentukan berapa banyak yang mereka terhutang .
pemain baru , Laurent Robert dan kembalinya Greg Sutton tidak cukup untuk Toronto F.C. kerana mereka jatuh 4-1 kepada D.C. United di Washington .
gol awal dari Luciano Emilio dan Santino Quaranta meninggalkan Toronto dalam perjuangan yang berat untuk sepanjang perlawanan .
bukit hanya menjadi lebih besar pada minit ke-22 apabila Kevin Harmse memberi cabaran keras pada Gonzalo Peralta dan seterusnya dibuang padang .
Marcelo Gallardo kemudian menjadikan kedudukan 3-0 untuk pasukan tuan rumah pada minit ke-52 .
Quaranta melintasi bola dan Gallardo adalah terbuka luas untuk merembat bola ke gawang yang terbuka .
Jaime Moreno menghabiskan jaringan untuk D.C. pada minit ke-78 sebelum Edu membuka akaun MLS Toronto dengan gol pertamanya musim ini .
kekalahan ini meninggalkan Toronto di 0-2-0 pada musim ini , manakala DC mengambil kemenangan pertama selepas tewas perlawanan pembukaan mereka .
DC kini akan berjalan untuk bermain Real Salt Lake , manakala Toronto akan melawat David Beckham dan L.A. Galaxy .
antara perdebatan dan pusingan pengundian pertama Bobošíková menarik balik pencalonan beliau , memetik kekurangan sokongan untuknya .
pusat Belia Thai-Jepun Bangkok , Bangkok - Wikinews menemuramah Georgia Inglis , dari pasukan bola keranjang kerusi roda wanita kebangsaan Australia , yang dikenali sebagai Gliders .
The Gliders berada di Bangkok , Thailand , bagi Kejohanan Bola Keranjang kerusi roda Asia-Oceania , yang sedang berlangsung di Pusat Belia Thai-Jepun Bangkok .
mereka berharap untuk layak ke Kejohanan Dunia , yang sedang diadakan di Toronto , Kanada , pada bulan Jun tahun depan .
Inglis adalah satu daripada dua pemain baru dalam pasukan .
Wikinews bertemu dengan beliau sebelum perlawanan Gliders menentang China .
defisit persekutuan 2008 Amerika Syarikat telah mencecah rekod , US $ 454.8 bilion - lebih daripada defisit dua tahun lepas .
pakar-pakar kewangan percaya bahawa tahun depan , defisit akan mencapai lebih $ 700 bilion , manakala Jam Hutang Negara baru-baru ini kehabisan digit mencatatkan lebih daripada $ 10 trilion dalam hutang negara .
defisit ini kini bersamaan dengan 3.2 % daripada Keluaran Dalam Negara Kasar ( GDP ) di Amerika Syarikat , dengan jumlah pendapatan kerajaan yang 17.8 % daripada GDP , dan jumlah perbelanjaan yang bersamaan dengan 21 % daripada GDP .
Setiausaha Perbendaharaan Henry Paulson menyalahkan defisit pada pasaran perumahan , pasaran yang berkaitan , dan pertumbuhan perlahan .
beliau berkata , berita itu akan " mengukuhkan keperluan untuk bukan sahaja menangani cabaran jangka pendek , tetapi meneruskan dasar-dasar yang menggalakkan pertumbuhan ekonomi dan tanggungjawab fiskal , dan alamat kelayakan reformasi . "
Demokrat seperti Senator Kent Conrad , bagaimanapun , meletakkan kesalahan ke atas " Dasar gagal Presiden Bush . "
" Realitinya adalah bahawa presiden akan datang akan mewarisi keadaan kucar-kacir fiskal dan ekonomi perkadaran bersejarah , " kata Conrad , sambil menambah bahawa " ia akan mengambil masa untuk menggali jalan keluar . "
satu lagi Demokrat , Pengerusi Jawatankuasa Belanjawan Dewan John Spratt , juga menyalahkan pentadbiran Bush .
" lapan tahun pentadbiran ini akan termasuk lima defisit bajet terbesar dalam sejarah , " katanya .
" hutang yang terhasil akan diserahkan kepada anak-anak dan cucu kita . "
Jim Nussle , Pengarah Pejabat Pengurusan dan Anggaran berkata beliau percaya bahawa defisit akan mula merosot .
" rang undang-undang rangsangan kedua-dua parti dan ekonomi yang perlahan adalah sebab-sebab utama bagi peningkatan dalam defisit seperti yang ditunjukkan dalam hasil bajet tahun ini . "
" peningkatan ini memperkukuhkan lagi keperluan untuk mengamalkan dan mengekalkan dasar-dasar yang menggalakkan pertumbuhan ekonomi dan tanggungjawab fiskal , termasuk pembaharuan kelayakan dan dasar cukai pro-pertumbuhan . "
" saya yakin ekonomi boleh kembali ke pertumbuhan yang lebih kukuh dengan penurunan defisit selepas bekerja melalui cabaran semasa jika Kongres menghadkan perbelanjaan membazir dan berlebihan . "
TADA khas mahkamah perbicaraan kes letupan di Mumbai pada tahun 1993 mula menyampaikan keputusan hari ini .
empat sekeluarga Memon , Yakub , Essa , Rubina dan Yusuf , didapati bersalah bersubahat dan bersubahat tindakan keganasan dan juga mempunyai hubungan dengan don kongsi gelap Dawood Ibrahim , dan kini menghadapi antara 5 tahun atau penjara seumur hidup .
hakim memutuskan untuk membebaskan tiga Memons lain , Suleiman , Hanifa dan Raheen , memberikan mereka manfaat keraguan .
Yakub , adik kepada tertuduh Ibrahim Mushtaq ' Tiger ' Memon , turut didapati bersalah memiliki senjata yang tidak dibenarkan .
selebihnya tertuduh , termasuk bintang Bollywood Sanjay Dutt , akan mendengar penghakiman dalam kes-kes mereka dalam tempoh empat minggu .
selepas mendengar keputusan mahkamah terhadapnya , Yakub hilang sabar , melemparkan hamun hakim dan menuduh beliau " membuat pengganas kepada yang tidak berdosa . "
selepas letupan yang mengorbankan lebih 250 orang di 13 letupan di seluruh bandar , keluarga Memon melarikan diri ke Dubai , dan kemudian Pakistan .
kecuali Tiger dan adiknyanya Ayub , bagaimanapun , yang lain daripada mereka kembali ke India pada tahun 1994 , dan telah ditangkap oleh CBI .
sejak itu , Yakub telah berada dalam tahanan dan telah , menurut peguamnya , Subhash Kanse , menjalani rawatan untuk kemurungan .
England telah mengalahkan West Indies dengan lima wickets dalam Twenty20 antarabangsa kedua pelancongan West Indies di England di The Oval , London , England .
kemenangan England mengikat dua siri perlawanan 1-1 selepas West Indies memenangi Twenty20 pertama semalam .
Chris Gayle mendapat West Indies dengan permulaan yang baik dengan 61 larian 37 bola , tetapi pemain England dan fielders terhad skor mereka untuk 169-7 selepas 20 overs walaupun beberapa pukulan besar dari Marlon Samuels .
di jawapannya , England gerun , kehilangan tiga wickets dalam 14 bola diikuti dengan pemecatan Kevin Pietersen untuk 19 .
walau bagaimanapun Owais Shah menjaringkan 55 untuk membantu England lepas sasaran .
lawatan ini kini bergerak ke satu siri tiga Satu Hari Antarabangsa perlawanan bermula pada 1 Julai .
terdahulu dalam lawatan itu , England memenangi Ujian siri empat perlawanan 3-0 .
London , England - Semalam Wikinews mempunyai peluang untuk melawat bengkel Ottobrock membaiki kerusi roda di Perkampungan Paralimpik di London .
ia adalah salah satu rangkaian bengkel di setiap tempat Paralimpik .
mereka dikendalikan oleh Ottobrock , yang telah membaiki kerusi roda di Paralimpik sejak 1988 .
bengkel ini dibuka pada 22 Ogos dan akan kekal sehingga 10 September .
mereka menyamakan diri mereka kepada anak-anak kapal lubang sukan bermotor - kecuali bahawa mereka tidak tahu apa jenis peralatan yang mereka perlu bekerja dengan .
stor mengandungi 15,000 alat ganti , dengan segala-galanya dari karbon lapang bilah gentian berjalan untuk ganti tayar - lebih 2,000 daripada mereka .
mereka menyimpan bahagian Ottobrock dan pesaing mereka juga , kerana mereka tidak tahu apa yang akan tiba di bengkel seterusnya .
atlet dari seluruh dunia membawa masuk segala macam peralatan .
juruteknik prostetik perlu berurusan dengan segala-galanya dari tayar rata untuk jejari patah untuk membina semula dalam skala penuh .
mereka sering bekerjasama dalam menentukan cara terbaik untuk melaksanakan pembaikan .
Objektifnya adalah untuk mendapatkan kerusi roda dibaiki dan kembali dalam perkhidmatan dengan seberapa segera yang mungkin .
kepada orang berkerusi roda bola keranjang dan ragbi telah ada melengkung roda supaya mereka boleh berputar di sekitar .
Ottobrock mempunyai bengkel kimpalan di mana bingkai dibaiki ; pengurus peralatan pasukan ' difahami tidak boleh membawa peralatan berat itu dengan mereka kepada permainan , jadi mereka bergantung kepada bengkel .
apabila kerja pembaikan diperlukan , ia sering diperlukan dalam tergesa-gesa .
di permainan Turki vs Amerika Syarikat , kerusi itu dibaiki semasa perlawanan .
selain kerusi roda , bengkel mengendalikan segala macam kerja dengan prostesis .
pasukan China Boccia membawa masuk kerusi kemampuannya supaya elektronik diselaraskan .
dalam sukan itu , mempunyai kawalan digunakan dengan sempurna adalah sangat penting .
hampir 6,500 orang awam telah terbunuh dan beribu-ribu lagi cedera dalam tempoh tiga bulan lalu semasa pertempuran sengit di Sri Lanka , menurut laporan Pertubuhan Bangsa-Bangsa Bersatu .
pada awal tahun ini , tentera melancarkan operasi terhadap Harimau Pembebasan Tamil Eelam ( Tamil Tigers ) untuk menggulingkan mereka daripada wilayah mereka di bahagian timur laut Sri Lanka , yang pemberontak telah menduduki selama beberapa tahun .
pemberontak kini telah dipaksa kembali ke jalur kecil pantai , di mana kira-kira lima puluh ribu orang telah terperangkap selepas kawasan itu pindahkan daripada 100,000 orang .
Thangamuttu Sathyamurthi , seorang pegawai kesihatan kerajaan di zon perang , melaporkan bahawa orang akan mati kerana kelaparan , dan terdapat defisit ubat-ubatan dan makanan yang banyak .
menurut kumpulan bantuan perubatan Médecins Sans Frontières ( doktor tanpa sempadan ) , banyak orang yang melarikan diri dari zon konflik mempunyai tembakan dan luka letupan .
kerajaan telah menuduh pemberontak Tamil Tiger menggunakan orang awam sebagai perisai manusia , tuntutan yang pemberontak menafikan .
pemberontak menuduh tentera Sri Lanka secara rawak serangan kawasan awam .
U.N. mengatakan bahawa kadar kematian orang awam di negara ini telah meningkat dengan ketara .
rata-rata , 33 orang awam terbunuh setiap hari pada akhir bulan Januari .
jumlah itu telah meningkat kepada purata 116 setiap hari .
quarterback Brett Favre daripada Green Bay Packers memecahkan rekod Dan Marino untuk hantaran pendaratan pada Ahad , membuang nombor 421 kepada penerima Greg Jennings dengan 4 : 56 kiri dalam suku pertama .
hantaran pemecah rekod itu adalah laluan condong 16 ela , dan Favre terpaksa membuang peluru untuk menyiapkannya .
walaupun permainan itu sedang bermain di Metrodome , walaupun Minnesota Vikings peminat berdiri dan bertepuk tangan sebagai Favre disambut dengan rakan sepasukan .
selepas pengumuman rekod itu dibuat , mesej dirakam dari Marino dimainkan pada Jumbotron .
" saya ingin mengambil sedikit masa untuk mengucapkan tahniah kepada anda untuk memecahkan satu rekod dalam sukan . "
" saya suka memegang rekod pendaratan untuk 13 tahun yang lalu , tetapi jika seseorang itu akan patah , saya gembira ia adalah orang seperti anda , yang sentiasa bersaing di peringkat tertinggi dan sentiasa dimainkan hanya untuk menang , " kata Marino .
" sejak 17 tahun yang lalu , anda telah menjadi pujian kepada Packers , dan untuk Liga Bola Sepak Kebangsaan dan sukan yang kita semua suka begitu banyak . "
peristiwa bersejarah datang hanya dua minggu selepas Favre memecahkan rekod John Elway untuk kerjaya menang dengan quarterback , mengalahkan New York Giants untuk menang nombor 149 .
ikon Green Bay juga memegang rekod untuk siap kerjaya dan perlawanan berturut-turut dimulakan oleh quarterback , yang terus pada hari Ahad di 241 .
kemudian pada suku kedua permainan hari ini , Favre melemparkan pas 8359 kerjayanya , melebihi satu lagi rekod Marino .
apabila ditanya mengenai rekod itu selepas permainan , Favre lemah berkata , " Ia hanya nombor . "
" saya lebih berbangga dengan hakikat bahawa kita memenangi permainan ini ... "
" saya gembira ia sudah berakhir , dan saya bangga . "
" untuk bermain masa yang panjang ini , saya fikir , adalah satu perkara yang istimewa dan untuk mencapai ini adalah , uh , sangat istimewa . "
tambah beliau , di dalam fikirannya , Dan Marino masih lagi quarterback terbaik sepanjang zaman .
ETA ( Euskadi Ta Askatasuna ) , sebuah kumpulan pemisah berpusat di rantau ini Basque di utara Sepanyol , mengumumkan dalam mesej yang direkodkan dan bertulis bahawa ia akan mengakhiri kempen bersenjata untuk kemerdekaan , dan bukannya memberi tumpuan kepada cara politik untuk mencapai matlamatnya .
dalam video yang dihantar kepada BBC , ETA menyatakan bahawa , manakala rangka kerja autonomi yang termaktub dalam perlembagaan Sepanyol adalah " bukan cara untuk memenuhi kehendak rakyat Basque , " organisasi itu telah dilakukan untuk mencari penyelesaian demokratik kepada konflik .
beberapa penganalisis telah mencadangkan bahawa gencatan senjata baru-baru ini adalah berdasarkan kepada taktik ETA ini menyebabkan sokongan mereka di rantau ini Basque menjunam .
pengarang Paddy Woodworth menjumpai di dalam perjalanan baru-baru ke rantau ini bahawa tindakan kumpulan itu telah membuat bekas penyokong gerakan percaya ETA telah selesai politik .
BBC Sarah Rainsford berkata ETA adalah pada ketika yang paling lemah dalam sejarah 51 tahun dan bahawa gencatan senjata itu hanya boleh menjadi satu helah untuk menyembunyikan kelemahan itu .
kumpulan itu , yang disenaraikan sebagai pertubuhan pengganas oleh Kesatuan Eropah dan Amerika Syarikat , telah mengisytiharkan gencatan senjata beberapa kali sebelum ini , yang mempunyai semua berakhir dengan semula keganasan .
gencatan senjata yang baru-baru ini , pada tahun 2006 , membawa kepada rundingan damai antara kumpulan dan kerajaan Sepanyol , tetapi mereka telah diganggu oleh pengeboman kereta di Lapangan Terbang Barajas di Madrid .
pengeboman itu dikecam oleh semua pihak yang terlibat dalam proses damai , termasuk pihak pemisah Basque lain di rantau ini .
pada hari Jumaat , semua enam rangkaian televisyen utama Amerika ; ABC , CBS , FOX , NBC , WB dan UPN , bersama-sama dengan stesen PBS besar , bersatu dalam pertunjukan perpaduan yang jarang berlaku untuk menyiarkan konsert amal sejam dipanggil Perlindungan daripada Ribut : satu Konsert untuk Teluk Pantai .
konsert itu disiarkan secara langsung pada jam 8 malam di zon masa yang Timur dan 7pm dalam zon waktu yang Tengah dan pada pita kelewatan di Gunung dan zon masa Pasifik .
ia juga ditunjukkan di Internet dan banyak rangkaian kabel seperti USA , Bravo dan G4 .
acara ini telah dihasilkan oleh Joel Gallen , orang yang sama di sebalik konsert penghormatan 11 September Amerika : A Tribute to Heroes .
acara ini tidak ditapis untuk kenyataan politik tetapi adalah untuk kata-kata kotor .
minggu lalu , penyanyi rap Kayne West membuat kenyataan pada amal NBC A Concert for Hurricane Relief , di mana Barat mendakwa bahawa " George Bush tidak mengambil berat tentang orang kulit hitam . " , yang menimbulkan kontroversi .
sepanjang konsert itu terdapat pertunjukkan yang ketara , U2 melaksanakan " One " dengan Mary .
masa lain adalah Garth Brooks , Trisha Yearwood dan band rumah daripada The Late Show dengan David Letterman melakukan sampul John Fogerty itu : " WHO ' ll Stop The Rain . "
derma sedang diminta untuk Palang Merah Amerika dan Salvation Army .
Telecom syarikat AT & T menyediakan panggilan bebas tol dan 10 pusat panggilan untuk acara tersebut dan MCI sediakan sukarelawan dari pusat-pusat panggilan mereka .
Bet turut mengadakan konsert amal dipanggil S.O.S ( Saving OurSelves ) , setengah jam sebelum memotong dengan yang utama .
MTV , MTV Overdrive , VH1 dan CMT akan disiarkan pertunjukan amal Sabtu dipanggil ReAct Now : Music & Relief .
Ian Alleyne , hos TV Trinidad rancangan Crime Watch , telah didakwa dengan jenayah di bawah Akta Kesalahan seksual selepas pita yang dikatakan menunjukkan seorang gadis remaja sakit mental dirogol didakwa disiarkan tahun lepas .
rakaman ini didakwa adalah ke udara tiga kali Oktober lalu dan mencetuskan pelbagai aduan kepada polis .
saluran Caribbean Communications Network ( CCN ) TV6 dituduh bersama di bawah akta yang sama seperti Alleyne , dan juga di bawah Akta Telekomunikasi .
Alleyne telah dimasukkan ke hospital berikutan penangkapannya , kerana sakit dada .
beliau harus pergi ke hadapan seorang majistret , dan tidak boleh menerima ikat jamin sehingga dia berbuat demikian .
polis telah melawat pejabat CCN di Port of Spain dua kali tahun lepas mencari pita .
Alleyne mengeluarkan mesej kepada The Trinidad Express mengkritik keputusan untuk tidak memberinya jaminan sehingga dia muncul di mahkamah .
beliau berkata , " ianya adalah benar-benar hal ehwal di pihak polis dalam keadaan yang sedih . "
" apa yang telah saya lakukan bahawa mereka telah patut melihat untuk memastikan bahawa saya hanya dibenarkan ikat jamin ke hadapan majistret ? "
mahkamah pilihan raya Mexico telah sebulat suara menolak dakwaan penipuan besar-besaran dalam pilihan raya presiden 2 Julai dan melaporkan bahawa sebahagian pengiraan semula diperintah di akhir bulan lalu tidak pernah berubah hasil asal kemenangan tipis untuk calon konservatif Felipe Calderon Parti Tindakan Kebangsaan ( PAN ) .
Andres Manuel Lopez Obrador daripada sayap kiri Demokratik Revolusi Party ( PRD ) , terus menegaskan bahawa pilihan raya itu dimanipulasi dan telah berikrar untuk terus berjuang hasilnya .
Lopez Obrador telah menolak keputusan itu dan mencadangkan membentuk kerajaan selari saingan .
tidak ada saluran undang-undang untuk merayu keputusan mahkamah itu , dalam kecuali artikel 39 Perlembagaan Mexico yang menyatakan : " kedaulatan negeri itu tinggal kepada rakyat . "
" warga sentiasa mempunyai hak untuk menukar atau mengubah suai kerajaannya , " artikel yang telah dituntut oleh Andres Manuel Lopez Obrador sebagai hak untuk memanggil suatu Konvensyen Demokratik Kebangsaan .
tujuh hakim mempunyai sehingga 31 Ogos untuk menyelesaikan semua aduan dan sehingga 6 September untuk mengisytiharkan secara rasmi presiden-pilihan umat atau membatalkan pilihan raya .
Lopez Obrador telah memimpin bantahan besar-besaran di Bandar Raya Mexico sejak beberapa bulan lepas menuntut pengiraan semula sepenuhnya .
" jangan sekali-kali lebih banyak kita terima hakikat bahawa sebuah kerajaan yang menyalahi undang-undang dan tidak sah dipasang di negara kita , " katanya kepada ribuan penyokong berikut pemerintah memanggil mereka untuk tidak menerima Calderon sebagai presiden dan untuk membuat keputusan jika ia membentuk kerajaan selari dan ( atau ) terus protes di seluruh negara .
Leonel Castillo , presiden tribunal itu , berkata tuntutan Lopez Obrador terhadap penipuan besar-besaran " ternyata benar-benar tidak berasas . "
pasukan pilihan raya Lopez Obrador telah memfailkan aduan di 50,000 pusat pengundian tetapi mahkamah mengarahkan pengiraan semula hanya 11,839 stesen atau 9 % daripada semua lokasi mengundi berikutan bantahan jalanan besar-besaran .
Calderon memenangi kiraan undi awal oleh perbezaan kurang daripada 0.6 %
Australia akan bergerak maju dengan rancangan untuk menarik balik tenteranya dari Iraq pada Jun tahun ini , walaupun janji-janji telah dibuat oleh menteri luar negeri bahawa hubungan dengan Amerika Syarikat tidak akan terjejas oleh langkah itu .
Menteri Luar Negeri Stephen Smith berkata penarikan balik itu akan dijalankan dalam cara yang teratur untuk meminimumkan kesulitan kepada negara-negara lain di Iraq .
bercakap di New York sebagai sebahagian daripada lawatan Amerika Syarikat yang pertama sejak pilihan raya beliau berkata , " Kami mahu berbuat demikian dengan cara yang melihat gangguan yang minimum , yang menyebabkan kesulitan-kurangnya kepada sekutu kami di sana , kedua-dua Amerika Syarikat dan United Kingdom . "
pada hari Isnin , Smith akan bertemu dengan Condoleezza Rice dan lain-lain untuk membincangkan Afghanistan , di mana Australia juga mempunyai tentera yang ditempatkan .
ia kini niat untuk ini mengekalkan kes itu .
Smith berkata kesan ke atas hubungan dengan Amerika Syarikat - yang telah kukuh sejak Perang Dunia II - " Ia bukan sesuatu yang saya percaya akan mengganggu apa setakat ini adalah hubungan kerja yang sangat baik antara kerajaan baru dan pentadbiran ( Amerika Syarikat ) . "
" ia adalah satu pakatan yang sangat kuat - satu pakatan yang melampaui perubahan dalam kerajaan . "
" pentadbiran datang dan pergi , kerajaan datang dan pergi , tetapi perikatan adalah jangka panjang , berkekalan hubungan asas antara kedua-dua negara . "
pengesahan itu penting kerana Australia menyaksikan kerajaan baru dipilih pada bulan November .
Perdana Menteri Kevin Rudd ( Buruh ) mengalahkan ketua Konservatif dan bekas PM John Howard .
Howard adalah penyokong Presiden Amerika Syarikat George W. Bush dan kerajaannya .
Jerman menewaskan Argentina 4-2 menerusi penentuan sepakan penalti untuk menempah tempat dalam Piala Dunia Fifa separuh akhir di Berlin , Jumaat .
perlawanan itu telah seri 1-1 tanpa banyak peluang jelas untuk mana-mana pihak kerana permainan pertahanan di kedua-dua belah pihak .
pertama , ia adalah Jerman yang tidak dapat menjadi positif kerana Argentina menguasai perlawanan dengan 65 peratus penguasaan bola .
empat minit selepas separuh masa Roberto Ayala memotong Miroslav Klose untuk bertemu Juan Riquelme di sudut yang dipunyai olehnya di antara Jens Lehmann dan pos kawalan berhampirannya , Philipp Lahm .
gol awal pada babak kedua membuat perlawanan yang lebih menarik yang selama ini kebanyakannya kurang memberangsangkan pada separuh masa pertama di mana tidak ada pihak boleh mengumpul lebih daripada satu tendangan .
Juergen Klinsmann boleh dikreditkan dengan perubahan penggantian yang sebahagiannya membantu Jerman mendapatkan gol penyamaan .
David Odonkor yang cepat adalah bermasalah untuk Juan Sorin dan sayap kiri Argentina dan membenarkan Jerman maju lebih dekat ke kawasan penalti pembangkang .
pengurus Argentina juga mungkin telah membuat satu kesilapan taktikal dan mengalami masa yang bernasib buruk .
dalam minit sebelum Jerman menyamakan kedudukan dari penyeberangan padang kiri Ballack yang hebat penjaga gol terpaksa diusung keluar akibat kecederaan otot .
Jose Pekerman diikuti penggantian penjaga gol itu dengan dua pertahanan ; pemain tengah perancang kreatif Riquelme dan ke hadapan Hernan Crespo berlepas .
Lionel Messi dan Javier Saviola yang tinggal di bangku simpanan manakala Julio Cruz , bola-pegangan yang panjang ke depan , telah dibawa ke rakan Carlos Tevez .
nasib buruk dan perubahan seolah-olah meletakkan Jerman yang bertanggungjawab bagi permainan taktikal buat kali pertama dalam perlawanan itu .
satu minit selepas Cruz tiba Pekerman mungkin telah menyesal keputusannya .
gol kelima Piala Dunia Klose sepuluh minit dari semasa meletakkan dia di atas papan pemimpin Fifa Kasut Emas sebagai penjaring gol tertinggi kejohanan .
dia menewaskan penanda untuk menanduk kepala di luar Leonardo Franco selepas Tim Borowski , penggantian 74 minit , telah menguis di atas tendangan seberang Ballack .
permainan selesai 1-1 dan kedua-dua bahagian masa tambahan mencerminkan perlawanan ; separuh pertama lancar , separuh kedua lebih menyerang .
Fabricio Coloccini hampir memecah kebuntuan apabila terkena palang gol dari 45 ela ketika cuba untuk menangkap Lehmann dari garisan gol .
baik Jerman atau Argentina tidak pernah tewas pada pertandingan penalti Piala Dunia ; kedua-dua pihak telah memenangi tiga .
semua tendangan penalti mencapai sasaran dan ditendang dengan baik , kecuali Ayala yang menendang dengan usaha lembut yang Lehmann selamatkan ke kirinya .
usaha Cambiasso ke kiri Lehmann telah melanda lebih baik tetapi penjaga gol telah meneka sebelah kanan untuk menyelam untuk memecahkan hati Argentina .
FIFA melancarkan siasatan ke dalam huru-hara di padang yang bermula selepas hukuman yang diputuskan memihak kepada Jerman .
pengganti Argentina yang tidak digunakan Leandro Cufre diserang Jerman Per Mertesacker dan telah dibentangkan kad merah oleh Lubos Michel .
menurut ketua pasukan Jerman , Michael Ballack konflik bermula apabila pemain Argentina menjerit kepada pasukan Jerman semasa penentuan .
apabila Tim Borowski mendapat penalti keempat Jerman dia membuat tanda kepada pemain Argentina untuk menjadi tenang .
selepas penalti tendangan pemain Argentina mendekati Borowski dan pergelutan kebanyakannya menolak mula dengan berpuluh-puluh pemain , pengadil , jurulatih dan pemain simpanan terlibat .
FIFA berkata gambar televisyen akan melihat dan denda atau sekatan akan dipertimbangkan sekiranya sesuai .
Mark Webber mendapat kemenangan sulung Formula 1 hari ini di Grand Prix Jerman , selepas 130 perlumbaan .
rakan Red Bull sepasukannya , Sebastian Vettel di tempat kedua , dengan Felipe Massa dari Ferrari di tempat ketiga .
Webber bermula di petak pertama , tetapi menyentuh Rubens Barrichello pada permulaan selepas permulaan yang perlahan .
beliau menerima penalti pandu-lalu bagi kesalahan ini , yang beliau membuat pada akhir pusingan keempat belas beliau .
ini membolehkan beliau menyertai semula ke perlumbaan di tempat pertama .
Jenson Button kekal pertama dalam kejohanan itu dengan 68 mata , dengan Vettel dan Webber memintas Barrichello , dengan mengambil kedua dan ketiga .
selepas kemenangan itu , Webber berkata " Saya kehilangan Rubens off permulaan , saya fikir dia telah pergi ke kiri tetapi dia pergi betul dan saya terbentur kepadanya . "
" saya telah mendapat pandu lalu dan jurutera saya membuat saya tenang . "
" ia adalah satu musim sejuk yang sukar , Sebastian menunjukkan pada ujian musim sejuk apa kereta boleh lakukan , jadi saya terus meningkatkan motivasi saya dan saya telah merasa agak kecewa . "
" pasukan itu bersabar dengan saya , semua orang di Australia dan beberapa orang yang ragu-ragu dengan saya juga jadi apa khabar kepada mereka juga . "
hari ini telah menyaksikan hari paling panas pada Julai mencatat Britain dengan suhu mencecah 36.5ºC ( 97.7ºF ) di Wisley di Surrey .
udara panas dari Arus Teluk menaikkan suhu , dan cuaca panas menyebabkan asfalt di beberapa jalan awam menjadi cair , yang memerlukan kersik .
sesetengah sekolah kekal tutup pada hari Rabu , manakala yang lain ditutup pada waktu makan tengahari .
orang ramai dinasihatkan untuk minum air yang banyak , tidak keluar di matahari tengah hari dan tirai gelap terus ditutup untuk menyejukkan bilik .
orang ramai juga telah diminta untuk memeriksa mereka yang paling lemah , termasuk warga tua , yang muda dan yang sakit .
RSPCA juga telah memberitahu pemilik haiwan kesayangan untuk mencuba dan memastikan haiwan kesayangan mereka merasa dingin .
gelombang haba juga telah melanda utara Perancis dan Belanda , dengan 4 orang dilaporkan mati akibat strok haba .
Lerwick di Kepulauan Shetland kini mendung dengan kabus , hanya 18ºC ( 64ºF )
peramal cuaca telah berkata ketika suhu tidak akan naik lagi , ia akan menjadi lebih lembap dengan jalur hujan tiba petang ini , dengan suhu pada waktu malam pada 19ºC di London dan Cardiff , 14ºC di Edinburgh dan 18ºC di Dublin .
apabila ia telah diumumkan bahawa William dan Kate telah bertunang , Prince Harry mengulas dengan mengatakan bahawa : " ia bermakna saya mendapat seorang kakak , yang saya telah sentiasa mahu , " dan bahawa dia " gembira . "
serta pengumuman pengapit pengantin lelaki dan ketua pengapit pengantin perempuan , rancangan-rancangan lain telah diumumkan juga .
empat pengapit telah diumumkan sebagai anak kepada Earl dan Countess of Wessex , Lady Louise Windsor , yang berusia tujuh tahun .
Margarita Armstrong-Jones berusia lapan tahun , anak perempuan Viscount dan Viscountess Linley , dan Grace van Cutsem berusia tiga tahun , anak perempuan Hugh van Cutsem , yang merupakan kawan rapat kepada kedua-dua William dan Kate .
cucu Duchess of Cornwall yang berusia tiga tahun akan menjadi pengapit keempat .
dua budak kundang telah diumumkan sebagai William Lowther-Pinkerton dan Tom Pettifer .
Lowther-Pinkerton adalah anak kepada Setiausaha Sulit William manakala Pettifer adalah anak kepada bekas pengasuh William dan Harry , Tiggy Legge-Bourke .
bagaimanapun , butir-butir pakaian pengapit pengantin perempuan dan pakaian seragam budak-budak kundang tidak akan didedahkan sehingga hari perkahwinan .
penyelidik Kanada dari Makmal C-crest telah menemui jumlah bakteria yang " sangat tinggi " dalam air botol .
penyelidik tidak menyalahkan jenama tertentu , tetapi air botol secara umum .
satu kajian rawak mendapati kadar bakteria heterotrofik yang sangat tinggi di dalam air botol , lebih daripada 500 cfu , had yang ditetapkan oleh undang-undang Farmakopeia Amerika Syarikat tentangberapa banyak bakteria perlu hadir dalam air minuman di Kanada .
jumlah bakteria yang sangat tinggi terdapat di dalam 70 % daripada sampel ujian di dalam beberapa jenama air botol .
" jumlah bakteria heterotrofik di dalam beberapa botol didapati dalam angka yang memeranjatkan iaitu ( 100 ) kali lebih daripada had yang dibenarkan , " kata Sonish Azam , seorang penyelidik Kanada terlibat dalam kajian ini , " Ini jumlah bakteria yang membimbangkan , seolah-olah kita meminum secawan kultur . "
" bercakap secara mikrobiologi , " katanya , " air paip adalah lebih tulen daripada air botol - kebanyakan air botol .
bakteria tidak begitu berbahaya kepada orang yang biasa , tetapi kepada banyak kumpulan yang sensitif , seperti golongan muda , sakit atau orang tua , boleh jatuh sakit disebabkannya .
" jumlah bakteria heterotrofik di dalam air minuman bukanlah masalah kesihatan kepada orang awam , " adalah analisis terakhir kajian baru-baru ini oleh Pertubuhan Kesihatan Sedunia .
Vladimir Putin telah dilepaskan daripada kuasa Laksamana Vladimir Kuroyedov , ketua tentera laut Rusia .
ini berlaku sebulan selepas satu kejadian di mana 7 pelayar Rusia terperangkap dalam kapal selam , dan terpaksa diselamatkan dengan bantuan dari luar negara .
tiada sebab diberikan bagi pemecatan Kuroyedov , walaupun Laksamana Eduard Baltin menspekulasikan di Radio Moscow bahawa ia mungkin kerana kesihatan ketua tentera laut itu terganggu .
Laksamana Kuroyedov bertanggungjawab ke atas tentera laut semasa bencana Kursk pada tahun 2000 , di mana 118 kelasi meninggal dunia ketika kapal selam mereka tenggelam .
Kuroyedov digantikan oleh Vladimir Masorin , yang sebelum ini berkhidmat sebagai Ketua Turus untuk Tentera Laut Rusia .
dalam ucapan Putin tentang perubahan kepimpinan tersebut dan merujuk kepada Masorin , beliau berkata " Latihan kebelakangan ini , termasuk yang saya telah menghadiri , menunjukkan bahawa tentera laut sedang membangun dan sebahagian besarnya adalah merit untuk anda . "
Putin juga menambah " pada masa yang sama , terdapat peristiwa-peristiwa yang sukar , tragedi , tetapi saya ingin menekankan sekali lagi bahawa semua masalah ini , semua peristiwa itu , perkara utama adalah bahawa Tentera Laut sedang di dalam proses pembangunan semula . "
Masorin menambah semasa di dalam dewan di Admiralty , " Satu perkara yang jelas - ia adalah tidak mungkin untuk terus berada dalam keadaan kita sekarang dalam dan tidak membuat apa-apa . "
" saya telah diberi tugas untuk menghentikan tentera laut dari menjejaskan pendapat orang ramai . "
" saya tidak mengalami keghairahan kerana dilantik sebagai ketua tentera laut . "
kerajaan telah mengumumkan 13 Jun sebagai tarikh untuk pilihan raya kecil Gunung Albert akan datang .
pilihan raya kecil telah disebabkan oleh pemergian bekas Perdana Menteri Helen Clark untuk mengetuai Program Pembangunan Pertubuhan Bangsa-Bangsa .
walaupun ia dianggap sebagai kerusi Buruh yang selamat , pilihan raya kecil dijangka akan banyak yang dipertandingkan .
setakat ini empat calon telah meletakkan nama mereka ke hadapan : ahli majlis bandar Auckland Glenda Fryer , bekas calon Hamish McCracken , pensyarah kajian politik Universiti Auckland Meg Bates dan peguam pekerjaan Helen White .
ahli Parlimen Phil Twyford , yang dijangka menggantikan Cik Clark , tidak meletakkan namanya ke hadapan .
parti Kebangsaan telah mengurangkan calon kepada dua orang : ahli Parlimen Melissa Lee atau calon yang tidak berjaya pada tahun 2008 Ravi Musuku .
keputusan akan dibuat dalam mesyuarat parti pada 4 Mei .
The Greens dan ACT New Zealand kedua-duanya akan bertanding dalam pilihan raya kecil , tetapi masih belum memilih calon .
konflik meletus antara sami Ortodoks Greek dan Kristian Arab di Jerusalem pada hari Good Friday , kerana orang-orang Kristian Arab membantah penjualan tanah gereja oleh sami-sami kepada penduduk Yahudi .
polis Israel memecahkan protes berhampiran dengan Gereja Holy Sepulchre .
Omar Harani , yang berusia 25 tahun mengetuai penunjuk perasaan , memberitahu Telegraph , " Kami telah memberikan tanah 2,000 tahun yang lalu kepada Gereja untuk menjaga , " dan lagi , " Jadi ia bukan tanah mereka untuk dijual . "
" selama beratus-ratus tahun kita orang Kristian , yang pernah menjadi 15 peratus daripada penduduk , telah dianiaya dan dihalau keluar dari Tanah Suci dan kini kita minoriti kecil . "
" tetapi kita akan membuat suara kita didengari untuk menghentikan penjualan ini . "
selepas mesyuarat di Bari , Itali , pada 13 Mac , Presiden Rusia , Vladimir Putin , dan Perdana Menteri Itali , Romano Prodi , memberikan persidangan akhbar , merumuskan hasil perbualan mereka .
perkara paling penting yang kedua-dua pemimpin bersetuju adalah bahawa hanya cara diplomatik boleh digunakan dalam menyelesaikan konflik antarabangsa seperti di Afghanistan , Iraq dan , terutamanya , Iran dengan isu program nuklearnya .
Encik Putin mengesahkan sekali lagi pandangan beliau mengenai apa-apa penggunaan angkatan tentera dalam menyelesaikan konflik antarabangsa itu .
Encik Prodi bersetuju dengan Presiden Rusia pada ketika ini dan juga menyatakan bahawa konflik itu perlu diselesaikan dengan menggunakan pendekatan pelbagai hala , di mana beberapa negara akan mengambil bahagian dalam perbincangan .
di samping itu potensi kuasa UN harus digunakan , tambah Encik Prodi .
Perdana Menteri berkata bahawa Itali tidak sabar untuk bekerjasama yang lebih rapat dengan Rusia dalam Majlis Keselamatan UN , dan juga dalam sektor tenaga .
semua ini dapat dicapai hanya melalui perjanjian perkongsian yang dibina dengan teliti , katanya .
diadakan pada hari Ahad , Hari Brampton tahunan pertama di Ontario Place memberi peluang kepada beratus-ratus penduduk Brampton bergembira di Toronto , sambil mengalami masyarakat mereka sendiri .
hiburan di atas pentas termasuk kumpulan rock tempatan Frayed , nyanyian Cuba oleh Alexis Martinez , blues dan rakyat dari Gayle Ackroyd , jazz lembut Carmen Spada , tarian bhangra oleh Koonja dan Punjabi Virsa Art & Culture Academy , dan persembahan Teater Brampton Manusia daripada La Mancha .
banyak kumpulan dan organisasi masyarakat berada di majlis itu , dari Pasar Peladang ke pasukan bola sepak Brampton Stallions .
seni Visual Brampton menawarkan kanak-kanak peluang untuk mencipta karya seni untuk Snail Mail World Postcard Art Show , manakala Majlis Seni Brampton memberikan baldi pasir jauh merah jambu dengan botol air Wilayah Peel .
pelawat muda telah nyata terpesona dengan Sassy tupai , maskot Bandar Raya .
orang yang membeli pas untuk acara Hari Brampton melalui Bandar digalakkan memakai band pergelangan tangan biru di sekeliling taman itu , bagi peluang untuk ditemui dan memenangi hadiah .
cabutan telah diadakan untuk hadiah termasuk yuran hijau untuk empat di Padang Golf Peel Village , tiket Panggung Warisan , dankupon restoran .
berdekatan Festival Square ke Lake Ontario menyebabkan sebahagian daripada masalah , terutamanya bagi kumpulan seni memaparkan di selatan .
khemah telah ditiup di sisinya , benar-benar menjadi layar angin .
Mujurlah tidak ada tetamu atau sukarelawan cedera oleh kejadian yang tidak diingini itu .
satu lukisan diselitkan dengan ukiran , dalam kemah Beaux-Arts Brampton , musnah pada awal hari selepas mendapat tiupan angin .
purata kelajuan angin untuk kawasan Lapangan Terbang Pulau Toronto adalah 12 km / j .
seorang wanita di Australia telah terbunuh dalam satu serangan jerung .
serangan itu berlaku pada pukul 5 petang ( Waktu Tempatan ) tidak jauh dari Amity Point , North Stradbroke Island , tenggara Brisbane .
wanita itu , digambarkan sebagai 21 tahun , telah kehilangan kedua-dua tangan sehingga ke siku dan mengalami luka teruk kepada tubuh dan kakinya .
beliau telah dibawa ke pantai oleh rakan-rakan dan kemudian diterbangkan dengan helikopter penyelamat ke Hospital Princess Alexandra di Brisbane .
wanita itu sedang bercuti dari Brisbane dengan kem gereja dan percubaan untuk menghubungi keluarganya telah dibuat .
pegawai krew helikopter Perkhidmatan Kecemasan Penyelamat Rod Morgan berkata , wanita itu telah mengalami kehilangan darah yang sangat banyak .
" dia sangat pucat " katanya , " Kami telah alihkan segera dan dapat berada di tempat kejadian dalam masa beberapa minit dan dapat menghantar pesakit ke hospital dalam masa sejam dari serangan itu . "
" kecederaannya mengancam nyawa kerana dia telah kehilangan sejumlah besar darah dan pesakit mempunyai apa yang kita akan memanggil tahap yang perubahan kesedaran di mana ia tidak dapat berkomunikasi secara langsung dengan pesakit " kata Queensland Ambulance paramedik Lachlan Parker .
terdapat banyak saksi di tempat kejadian dan mereka kini sedang ditemuramah oleh Polis di Amity Point .
seorang saksi , yang meminta untuk tidak dikenal pasti , terangkan bahawa mangsa sedang berenang di laut dengan Border Collie beliau .
apabila serangan itu berlaku , anjing itu berlari pulang untuk memberikan amaran .
" saya di seberang jalan dari mana dia tinggal dan saya melihat anjing itu datang menyerbu di atas jalan raya dalam keadaan yang basah dan menggigil dan merengek , " katanya , " Kemudian seorang budak lelaki datang berlari dan berkata wanita itu telah kehilangan kaki beliau dan lengannya dan semua orang berlari keluar dari rumah ke arah pantai . "
" ia hanya anjing hitam dan putih yang kecil tetapi dia gila jadi saya menguncinya di bawah rumah . "
laporan lain mendakwa bahawa wanita itu telah menyelam di dalam air cetek keruh kira-kira 15 meter dari pantai .
wanita itu dipercayai dari McDowall di Brisbane , tetapi namanya masih belum dikeluarkan .
seorang penduduk Amity Point selama 20 tahun , Brad Ross , berkata pelancong yang melawat kawasan ini telah diberi amaran tentang kemungkinan serangan ; " Pantai ini hanyalah sejauh dari 30m air dan terdapat banyak jerung jenis bull shark di luar sana . "
" orang ramai tahu apabila masuk air di sana mereka melangkah masuk ke dalam habitat jerung . "
pantai-pantai lain di pulau itu dilindungi oleh perangkap jerung .
Inspektor Polis negeri Queensland Peter Harding percaya dari teruknya keadaan kecederaan wanita itu bahawa dia telah diserang oleh sekumpulan jerung jenis bull shark , spesis yang terkenal dengan tingkah laku agresif pada masa ini .
polis marin akan mencari jerung hari ini dan akibatnya , pantai-pantai di sebelah timur dan barat Amity Point telah ditutup .
ini adalah serangan pertama di kawasan itu sejak Ogos 1972 .
kepercayaan tempatan memberi amaran tentang membenarkan anjing di dalam air di pantai berenang , kerana bimbang mereka akan menarik perhatian jerung , mungkin kerana sisa terkumpul daripada kutu yang hidup di dalam darah anjing .
pemain Snooker Alex Higgins , bergelar " Hurricane " , ditemui mati di apartmennya di Donegall Road , Belfast , Utara Ireland pada hari Sabtu .
beliau berumur 61 dan telah menderita kanser tekak sejak tahun 1997 .
dilahirkan di Belfast pada 18 Mac , 1949 , Higgins menjadi juara Snooker kejohanan dunia pada usia 23 pada tahun 1972 .
kemenangan terakhir Higgins ialah dalam Kejohanan Profesional Irish pada tahun 1989 .
dalam tahun 1986 , beliau menerima denda dan dilarang daripada lima kejohanan selepas menanduk seorang pengarah kejohanan .
beliau juga telah dilarang daripada bermain untuk satu tahun pada tahun 1990 selepas mengancam untuk memastikan Dennis Taylor , seorang lagi pemain snooker , ditembak .
kumpulan rock Rage Against The Machine menewaskan Joe McElderry untuk menjadi nombor satu carta Krismas rasmi di UK , berikutan salah satu pertempuran yang paling besar dalam sejarah Carta Rekod Single UK .
lagu mereka Killing in the Name menolak rekod single baru pemenang X Factor The Climb ke tempat kedua .
satu kempen Facebook yang menyokong kumpulan Amerika itu bertujuan untuk menghentikan seorang pemenang X Factor daripada mencapai tempat nombor satu carta Krismas sekali lagi .
artis dari rancangan bakat TV itu , yang dimiliki oleh Simon Cowell seorang yang berpengaruh di dalam bidang muzik , telah mengambil tempat teratas carta perayaan itu selama empat tahun berturut-turut .
kumpulan itu menarik lebih 900,000 ahli dan perhatian media yang meluas , selepas ia telah dimulakan oleh Jon dan Tracy Morter .
" Adakah anda berasa bosan tentang kemungkinan nombor 1 carta Krismas X-Factor SEKALI LAGI ? ... kami juga ... jadi kami akan melakukan sesuatu mengenainya ! , " kata mereka di laman Facebook kumpulan itu .
mereka memutuskan untuk menyokong " Killing In The Name " , pertama kali dikeluarkan pada tahun 1992 .
Cowell sebelum ini mengecap kempen ini " sinis " , tetapi pada hari Sabtu menghubungi Morters untuk mengucapkan tahniah kepada mereka kerana membuat satu " perlumbaan yang sangat menarik untuk nombor satu di carta Krismas . "
kempen ini juga telah mengumpulkan lebih dari £ 69,000 untuk kebajikan bagi mereka yang tidak mempunyai tempat tinggal , Shelter .
pemain gitar Rage Against The Machine Tom Morello telah menyokong kempen itu di Twitter .
beliau mengumumkan bahawa kumpulan ini akan membuat persembahan kemenangan percuma di UK jika mereka mencapai nombor satu .
keputusan itu diumumkan pada carta rancangan BBC Radio 1 petang ini oleh Scott Mills .
McElderry telah dijangka muncul di acara itu , tetapi tidak hadir .
iklan terkini untuk calon presiden Amerika Syarikat Republikan John McCain mempersoalkan manfaat ahli Demokrat Barack Obama untuk keluarga-keluarga .
minggu lepas BBC melaporkan bahawa kempen McCain telah mengeluarkan iklan membandingkan Obama dengan selebriti Amerika Britney Spears dan Paris Hilton , memanggilnya " selebriti terbesar di dunia . "
iklan terbaru McCain , yang dikeluarkan awal minggu ini , bersambung dengan ayat-ayat yang sama .
" apakah selebriti terbesar di dunia bersedia untuk membantu keluarga anda ? " seorang pengisah bertanya , menurut The Boston Globe dan video iklan yang dipaparkan di laman webnya .
dengan imej turbin angin di latar belakang , pengisah itu berkata , " Tenaga boleh diperbaharui untuk mengubah ekonomi negara , mewujudkan peluang pekerjaan dan kebebasan tenaga , itulah John McCain . "
The Boston Globe melaporkan bahawa iklan terkini McCain tidak mengakui bahawa dasar ekonomi Obama , terutama sekali cadangan pemotongan cukai keuntungan modal presiden semasa George W. Bush , sebahagian besarnya akan menjejaskan orang-orang terkaya of America , bukan kelas pertengahan .
Obama , BBC melaporkan , dipetik sebagai memanggil McCain " sinis , " " terdesak " dan " dalam poket Minyak Besar . "
video Obama terkini , ditunjukkan di laman web USA Today , menggambarkan McCain sebagai politik " hanya lebih yang sama " yang digunakan oleh George W. Bush .
iklan itu memetik 22 Mei 2003 Fox News Channel temu bual di mana McCain berkata " Presiden dan saya bersetuju tentang kebanyakan isu . "
" terdapat satu kajian baru-baru ini yang menunjukkan saya mengundi bersama Presiden lebih 90 peratus daripada masa . "
iklan itu kemudian mengkritik dasar McCain pada pemotongan cukai , wang untuk syarikat-syarikat minyak , dan " pengecualian cukai bagi syarikat-syarikat yang menghantar pekerjaan ke luar negara . "
McCain ditetapkan untuk muncul di sebuah kilang perabot Ohio pada hari Rabu untuk mengukuhkan mesej dalam iklan terbarunya .
" Amerika mempunyai kadar cukai perniagaan kedua tertinggi di seluruh dunia , " dia merancang untuk berkata sesuai dengan kenyataan bersedia dikeluarkan oleh kempennya , dan dikeluarkan oleh The Boston Globe .
" tidak hairanlah bahawa pekerjaan yang bergerak di luar negara apabila kita mengenakan cukai ke atas mereka keluar dari negara ini ? "
" malangnya rancangan Senator Obama akan menaikkan cukai ke atas perniagaan yang lebih banyak . "
" dia telah berjanji kenaikan cukai ke atas pendapatan , kenaikan cukai ke atas pelaburan , peningkatan cukai ke atas perniagaan kecil . "
" meningkatkan cukai dalam ekonomi yang tidak baik adalah perkara yang paling teruk anda boleh lakukan kerana ia akan menamatkan lebih banyak pekerjaan apabila apa yang kita perlu adalah dasar-dasar yang mewujudkan peluang pekerjaan . "
" Adakah penyokong terbesar George Bush letih , polisi gagal bersedia untuk membawa perubahan ? "
" satu lagi hari membawa satu lagi serangan yang tidak jujur dari John McCain . "
" walaupun Senator McCain tahu bahawa Senator Obama telah mencadangkan pemotongan cukai untuk 95 % keluarga-keluarga Amerika , apa yang dia tidak memberitahu kita ialah beliau mahu memberi $ 4 bilion dalam pengecualian cukai kepada syarikat-syarikat minyak , terus memberi pengecualian cukai kepada syarikat-syarikat yang membawa pekerjaan ke luar negara , dan tidak memberikan pelepasan cukai langsung untuk lebih 100 juta keluarga kelas pertengahan . "
" sudah sampai masanya untuk menyarakan dasar-dasar lama dan membawa tenaga baru ke Amerika . "
kegagalan dalam sistem bekalan kuasa terkumpul di Mosenergo yang berlaku pada 11 : 15 pagi waktu tempatan pada hari Rabu , membawa kepada gangguan bekalan elektrik di semua kawasan bandar .
beberapa laluan bawah tanah Moscow dihentikan selama empat jam .
trem dan bas troli , kereta api elektrik Moscow juga dihentikan .
selain masalah pencahayaan , pemilik rumah juga kehilangan bekalan air mereka , kerana stesen pam di Mosvodokanal juga kehilangan kuasa kerana kegagalan itu .
15 bandar-bandar besar dan lima kawasan pinggir bandar Moscow , beberapa kawasan di Tula dan Kaluga terbiar tanpa elektrik .
pada 12 : 00 tengah hari , kedai-kedai makanan di kawasan yang terlibat mula tutup .
untuk mengelakkan panik di stesen-stesen kereta api , pekerja dengan pembesar suara memaklumkan penumpang pergerakan kereta api .
menurut saksi , tidak ada lampu elektrik di banyak stesen dan di persinggahan antara mereka .
pada Khamis pagi bas troli dan trem masih tidak beroperasi di kawasan selatan Moscow .
walaupun kerja-kerja pembaikan dijalankan pada waktu malam , ia adalah mustahil untuk membekalkan kuasa semua talian bas troli dan trem .
dalam jumlah 8 trem dan 25 bus troli laluan tidak berfungsi .
selain itu , di selatan Moscow masih terdapat banyak rumah pangsapuri yang tidak mendapat bekalan kuasa .
pintu masuk ke Moscow untuk kenderaan besar akan dihadkan sehingga pukul 14 petang .
had ini telah dikuatkuasakan semalam kerana keadaan jalan raya yang sukar di dalam bandar selepas kegagalan kuasa .
Presiden Iraq Jalal Talabani dalam satu sidang media kepada pemberita pada hari Rabu telah disebutkan sebagai berkata : dia menjanjikan maklumat lanjut pada hari-hari akan datang .
persidangan akhbar presiden itu adalah sebagai balasan kepada peristiwaperistiwa yang berlaku dengan laporan daripada pegawai-pegawai Syiah .
mereka berkata pada hari Sabtu bahawa sebanyak 100 Syiah telah dijadikan tebusan oleh pejuang Sunni , dan diancam dengan kematian di bandar al-Madain , dekat Baghdad .
satu pasukan keselamatan Iraq pada hari Isnin menyerbu bandar kira-kira 1,000 keluarga , tetapi mendapati tiada bukti tentang orang tebusan .
pegawai-pegawai Syiah kemudian berkata , mayat - dipercayai tebusan - ditemui di Sungai Tigris .
dalam kejadian berasingan 200km utara dari Baghdad di Haditha , selepas mendengar tembakan wartawan dan penduduk menemui mayat 19 lelaki dibunuh di sebuah stadium bola sepak pada hari Rabu .
mereka yang telah ditembak adalah dipercayai tentera Iraq yang dilakukan oleh pejuang anti-kerajaan , menurut seorang pegawai Kementerian Dalam Negeri , walaupun mangsa-mangsa tidak memakai pakaian tentera .
mereka dianggap telah pulang untuk bercuti menandakan hari lahir Nabi Muhammad apabila diculik oleh pemberontak .
seorang pegawai polis telah dibunuh di County Armagh , Utara Ireland oleh pihak bersenjata Continuity IRA hanya 48 jam selepas dua askar terbunuh .
dalam apa yang dianggap sebagai satu percubaan oleh penentang Republikan untuk menggagalkan proses damai , Pc Stephen Carroll telah ditembak di kepala sebelum 10 : 00 malam pada 9 Mac .
pegawai tersebut , yang digambarkan sebagai veteran yang berpengalaman dengan 23 tahun perkhidmatan , berkata demikian ketika menjawab panggilan bantuan di estet Lismore Manor di Craigavon apabila beliau telah ditembak .
dalam apa yang digambarkan sebagai kejadian yang bukan dibuat-buat , seorang wanita dari orang ramai telah memanggil untuk bantuan mengatakan geng jalanan telah memecahkan tingkap .
dua kenderaan peronda telah dihantar ke tempat kejadian disebabkan masalah di kawasan itu sebelumnya .
selepas menunggu selama tempoh yang tertentu untuk memastikan bahawa tidak ada serangan hendap , ahli-ahli dari satu kenderaan keluar untuk menangani kejadian itu , manakala orang-orang di kenderaan kedua memberikan perlindungan , dan semasa memberikan perlindungan di dalam kenderaan kedua yang Pc Carrol telah diserang .
PSNI , percaya bahawa pegawai itu telah terkena salah satu daripada dua das tembakan yang dilepaskan oleh seorang lelaki bersenjata yang bersembunyi di dalam kawasan belukar di estet .
terdapat laporan yang tidak disahkan bahawa seorang pegawai kedua juga telah cedera .
tanggungjawab untuk tembakan itu telah dituntut bagi pihak Batalion Armagh Utara di Continuity IRA dalam mesej berkod ke media Belfast .
tembakan ini telah membawa kepada panggilan untuk perpaduan dan ketenangan dari seluruh masyarakat yang terdiri daripada jurucakap bagi Pasukan Sukarelawan Ulster , yang memanggil untuk lelaki bersenjata untuk diuruskan melalui mahkamah , bagi Sinn Féin adalah pantas untuk mengutuk lelaki bersenjata dan untuk mengucapkan takziah kepada keluarga pegawai yang mati .
itulah kematian yang pertama seorang pegawai polis kepada keganasan sektarian di dalam lebih satu dekad , dan datang selepas tempoh sembilan bulan di mana perisikan menunjukkan bahawa pihak penentang telah merancang untuk membunuh seorang anggota polis .
Presiden Amerika Syarikat , George W. Bush memulakan musim Tee Ball 2006 di South Lawn pada hari Jumaat , 23 Jun , 2006 .
ini merupakan tahun keenam Inisiatif Tee Ball Rumah Putih .
yang hadir untuk permainan itu ialah Jeneral Peter Pace , Pengerusi Ketua Turus Bersama , yang berkhidmat sebagai Pesuruhjaya permainan , Tim Brant dari ABC Sports dan WJLA-TV bertindak sebagai juruhebah yang memberi ulasan , dan Zane Ellingwood berusia tujuh tahun , yang mengasaskan " Wira Kecil Amerika " pada tahun lalu di kampung halamannya di Cumberland , Maryland .
dalam ucapan pembukaan , Bush mengalu-alukan ibu bapa dan datuk dan nenek kepada " padang bola bersejarah . "
pembaling Mike O ' Connor dari Washington Nationals juga berada di permainan itu .
Medha Patkar , aktivis Narmada Bachao Andolan pada hari yang kesembilan mogok lapar membantah Projek Sardar Sarovar , secara paksa dipindahkan ke hospital di New Delhi oleh polis .
pada hari kesembilan mogok lapar dia dan dua aktivis lain telah diambil untuk membantah keputusan kerajaan India untuk meningkatkan ketinggian empangan Sardar Sarovar seberang sungai Narmada dan kurangnya kemajuan dalam memulihkan orang pelarian oleh projek empangan .
Patkar dibawa ke Institut Sains Perubatan All India di mana dia telah diletakkan di bawah rawatan rapi .
doktor telah berkata bahawa dia sedar dan keadaannya stabil .
sumber polis mengatakan bahawa Patkar tidak ditahan pada masa ini , tetapi Laporan Maklumat Pertama telah dibuat terhadap beliau kerana cuba membunuh diri .
aktivis daripada Narmada Bachao Andolan cuba menghalang polis daripada menggerakkan Patkar dan ada yang ditangkap atas tuduhan merusuh .
lebih 100 Australia Yahudi , termasuk dua pengarang dan seorang menteri persekutuan , telah mengutuk pencerobohan Israel di Semenanjung Gaza .
113 penandatangan adalah ahli-ahli kumpulan yang dikenali sebagai Suara Bebas Yahudi Australia ( IAJV ) .
Antony Loewenstein , pengasas kumpulan itu , memberitahu The Age bahawa beliau menjangka kemarahan dari suara-suara Yahudi yang paling kuat .
tetapi IAJV telah menemui sebilangan besar daripada minoriti Australia Yahudi yang mementingkan perspektif bebas yang bertentangan dengan kedudukan pro-Israel yang membuta tuli .
" walau bagaimanapun , kerana rakyat Palestin tidak mempunyai cara untuk mempertahankan diri daripada kuasa yang paling berkuasa tentera di Timur Tengah . "
" kami amat menyeru Israel menghentikan serangan kejam terhadap rakyat Palestin terdedah Gaza dan menimbang semula penolakan panggilan Majlis Keselamatan Bangsa-Bangsa Bersatu untuk gencatan senjata , " kata kenyataan itu .
" sejarah telah menunjukkan bahawa hukuman tentera tidak pernah mematahkan semangat orang-orang atau menghasilkan keamanan , " kata kenyataan itu .
" ia hanya akan membakar kebencian terhadap Yahudi dan Israel , sambil tidak melakukan apa-apa untuk melindungi nyawa rakyat Israel . "
" paling penting , ia akan menjejaskan usaha untuk bekerjasama dengan rakyat Palestin yang mahukan keamanan untuk penyelesaian yang adil dan berkekalan . "
Colin Rubenstein , pengarah eksekutif Majlis Hal-ehwal Australia / Israel dan Yahudi , berkata kenyataan itu terpulang kepada " bentuk biasa Encik Loewenstein - salah sama sekali pada setiap fakta , sama sekali tidak seimbang , dan benar-benar tidak sensitif kepada penderitaan Israel . "
" mereka mencadangkan bahawa penduduk selatan Israel mesti terus hidup di bawah pengeboman roket berterusan , menentang segala usaha praktikal untuk benar-benar memohon hak untuk mempertahankan diri penandatangan yang mengatakan mereka mengiktiraf , " katanya .
sesetengah virus selesema di Amerika Syarikat dan Kanada telah menunjukkan peningkatan tahap ketahanan terhadap ubat antivirus Tamiflu ( oseltamivir ) , Pertubuhan Kesihatan Sedunia ( WHO ) berkata semalam .
Tamiflu kini adalah rawatan yang disyorkan untuk manusia dijangkiti selesema burung , dan kerajaan di seluruh dunia telah menyimpan stok simpanan ubat ini untuk kes wabak selesema .
ketahanan ubat itu nampaknya terhad kepada varian H1N1 yang menyebabkan selesema bermusim , manakala H3N2 atau strain influenza B dan strain H5N1 yang menyebabkan selesema burung tidak menunjukkan ketahanan meningkat .
walaupun kajian sebelum ini menunjukkan tahap ketahanan di bawah 1 % , sampel diuji oleh Pusat Kawalan dan Pencegahan Penyakit A.S. kini menunjukkan sekitar ketahanan 5 % , dan di dalam penyiasatan 81 spesimen di Kanada , 8 menunjukkan ketahanan .
pusat untuk Pencegahan dan Kawalan Penyakit Eropah mendapati 19 kes ketahanan antara 148 spesimen dari November lepas .
dalam satu kajian yang lebih luas 437 H1N1 diasingkan dari 19 negara , agensi Eropah mendapati 59 spesimen yang tahan dari 9 negara .
ketahanan tidak menunjukkan peningkatan di Jepun atau Hong Kong .
WHO kini menghubungi pihak berkuasa negara untuk mendapatkan lebih banyak data tentang ketahanan selesema .
Virus-virus ini telah memperoleh mutasi yang membuat mereka tahan , dan kenyataan WHO berkata strain yang tahan mungkin telah muncul secara spontan .
kenyataan itu menambah bahawa mutasi tersebut kemungkinan besar boleh menyebabkan Tamiflu tidak berkesan untuk pencegahan atau rawatan selesema yang disebabkan oleh virus H1N1 yang tahan .
WHO juga menyatakan bahawa fenomena ini tidak mempengaruhi keberkesanan imunisasi selesema .
jenis ketahanan telah menunjukkan tiada bukti menyebabkan penyakit yang lebih teruk atau yang lebih mudah berjangkit .
manifesto 2005 Parti Buruh menyatakan " Kami komited untuk mengekalkan penghalang nuklear bebas . "
walaupun terdapat laporan bahawa perancangan dan kerja reka bentuk pada kapal penggantian dan reka bentuk baru kepala perang nuklear ini telah berjalan selama beberapa tahun , mesyuarat Kabinet pertama yang perlu dipertimbangkan ikrar ini akan berlangsung esok .
tiada kertas Kabinet telah diedarkan sebelum mesyuarat di mana dikatakan akan ada " jangka pertama isu-isu . "
satu mesyuarat Kabinet lanjut akan diadakan sebelum penerbitan Kertas Putih sebelum Krismas .
prinsip mengekalkan penghalang nuklear akan mendapat undi di Dewan Rakyat tahun depan dan , walaupun ia mungkin memecahkan Parti Buruh , mungkin akan dilaksanakan dengan sokongan pembangkang Konservatif .
ia dilaporkan bahawa beberapa Menteri Kabinet mempunyai keraguan tentang kebijaksanaan untuk mengekalkan penghalang nuklear apabila ancaman jelas adalah dari pengkhianat dan pengebom berani mati .
mereka juga mempunyai keraguan tentang kesahihan menambah kepada stok muncung perang nuklear bertentangan dengan semangat Perjanjian Pengawalan Senjata Nuklear dan tentang cara yang keputusan diluluskan tanpa berunding dengan Parti Buruh .
antara mereka yang mempunyai keraguan adalah Setiausaha Luar Margaret Beckett , Hilary Benn , Menteri Negara bagi Pembangunan Antarabangsa , dan Peter Hain , Setiausaha Negara bagi Wales dan Ireland Utara .
satu-satunya negara Eropah yang lain dengan keupayaan nuklear ialah Perancis .
Perdana Menteri Blair dan Canselor Brown bersetuju mengenai keperluan untuk mengekalkan penghalang nuklear .
sebab mereka termasuk mengekalkan kerusi negara di meja atas politik antarabangsa .
sistem peluru berpandu Trident dijalankan dalam empat kapal selam kelas Vanguard berkuasa nuklear , di mana yang pertama telah ditugaskan pada bulan Ogos 1993 .
sistem Trident semasa berharga £ 12.6 Bn untuk diperkenalkan pada harga 1996 , dan memerlukan £ 280 juta setahun untuk menjaganya .
penggantian untuk kapal selam berkuasa nuklear serangan kecil sedang dalam pembinaan dan akan bersenjata dengan sistem peluru berpandu taktikal peluru berpandu Tomahawk .
Pertubuhan senjata-senjata atom di Aldermaston dilaporkan akan membangunkan senjata nuklear taktikal , yang lebih kecil dan julat pendek daripada Trident sesuai untuk menembak menggunakan jenis pelancar yang sama seperti Tomahawks .
Dewan Rakyat Amerika Syarikat telah meluluskan dwipartian dengan pakej rangsangan ekonomi sejumlah AS $ 152 bilion yang memberikan rebat satu kali kepada rakyat Amerika Syarikat , AS $ 600 untuk individu atau AS $ 1,200 untuk pasangan serta AS $ 300 untuk setiap anak .
cek AS $ 300 akan dihantar kepada orang-orang dengan pendapatan rendah termasuk pesara dengan Keselamatan Sosial yang tidak dimasukkan ke dalam rang undang-undang asal yang disokong oleh Presiden George W. Bush .
pelan ini akan mula mengurangkan rebat untuk rakyat dengan pendapatan boleh cukai sebanyak AS $ 75,000 bagi individu dan AS $ 150,000 untuk pasangan .
cek akan dikeluarkan untuk 130 juta rakyat Amerika mengikut Setiausaha Perbendaharaan Henry Paulson .
rumah Putih meluluskan rang undang-undang Senat yang diubah dengan lebih terbuka yang termasuk bahagian berpendapatan rendah yang tersebut di atas bersama-sama dengan peruntukan-peruntukan yang akan menjaga pendatang haram daripada menerima cek rebat .
walaupun terdapat beberapa bantahan daripada beberapa ahli Kongres , seperti John B.T. Campbell III dari daerah kongres ke-48 California , pelan itu lulus dengan keputusan yang menggalakkan , 380-34 .
Campbell memanggil pelan itu " pengagihan semula kekayaan " dan menyatakan ia tidak mempunyai perlindungan untuk mencegah pendatang tanpa izin daripada menerima rebat ini dan juga mendakwa pelan rangsangan akan meningkatkan defisit yang lebih dan menyatakan punca kemelesetan yang membimbangkan adalah kerana " masalah kredit . "
Senat Amerika Syarikat mengundi beberapa jam sebelum itu pada rang undang-undang yang diluluskan di Senat , 81-16 , selepas terpaksa mengurangkan beberapa insentif termasuk oleh Senat Demokrat yang menyebabkan rang undang-undang itu gagal .
antara insentif yang telah ketinggalan dari rancangan itu di dalam kompromi untuk mendapatkan sokongan Republikan adalah permintaan untuk pampasan kepada pekerja yang menganggur jangka panjang dan ketetapan yang akan membolehkan rakyat berpendapatan rendah membayar bil pemanasan dan membenarkan pembina rumah membayar kerugian kira tahun semasa berbanding tahun cukai sebelumnya .
Presiden Bush meluluskan pakej , menyatakan dalam satu kenyataan , " Pelan ini adalah kukuh , berasas luas , tepat pada masanya , dan ia akan menjadi efektif , rang undang-undang ini akan membantu untuk merangsang perbelanjaan pengguna dan mempercepatkan pelaburan perniagaan yang diperlukan . "
sabitan terhadapnya termasuk menyerang isteri keempatnya pada tahun 2006 , dan dia menjalani hukuman empat bulan walaupun meminta khidmat masyarakat ; serangan tikaman dari belakang dengan pisau lima inci kepada seorang rakan menyebabkannya mendapat hukuman tergantung dua tahun dan memasukkan lelaki itu ke hospital .
dia juga pernah menjalankan hukuman tiga belas bulan kerana menikam sorang rakan sambil minum dan telah didakwa kerana menyerang seorang lelaki dengan pisau di sebuah restoran , sebuah kes yang dijatuhkan disebabkan kekurangan bukti .
menurut jurucakap NATO , cubaan rampasan sebuah kapal tangki Norway di Teluk Aden oleh lanun Somalia telah digagalkan oleh tentera NATO .
MV Front Ardennes diserang oleh lanun dalam perahu kecil pada kira-kira pukul 6 : 00 petang pada hari Sabtu .
helikopter dan kapal perang telah dihantar untuk menyelamatkan kapal tersebut , dan lanun-lanun telahs ditahan selama tujuh jam selepas rampasan awal .
pegawai berkata bahawa lanun cuba melarikan diri dalam gelap , tetapi telah ditangkap oleh sebuah kapal Kanada .
tujuh daripada lelaki bersenjata lanun ditahan buat sementara waktu , tetapi kemudiannya dibebaskan .
jurucakap NATO Leftenan Komander Alexandre Santos Fernandes menyatakan bahawa kerana tidak ada undang-undang Kanada yang boleh mendakwa lanun tersebut , mereka terpaksa dibebaskan .
kegiatan melanun merebak di luar pantai timur Afrika ; pada hari Sabtu , lanun Somalia merampas Pompei , sebuah kapal Belgium , dengan sepuluh ahli-ahli anak kapal , semasa ia menuju ke selatan untuk pulau-pulau Seychelles .
berjumlah lebih daripada enam puluh kapal , telah dirampas oleh lanun sejak awal tahun lepas .
pada masa ini , lanun dianggap sedang menahan kira-kira tiga ratus anak kapal dari tujuh belas kapal .
seorang penguasa yang bertugas di Pasukan Polis New South Wales telah ditangkap memandu sebuah kereta polis yang tidak bertanda melebihi had laju pada kejaluan 176km / j dalam zon 100km / j di Lebuhraya Olimpik berhampiran Junee , New South Wales pada 13 Oktober .
penguasa Frank Goodyer , yang telah ditangkap oleh pegawai-pegawai sendiri di Wagga Wagga Local Area Command , didakwa memandu lebih daripada 45km / j melebihi had laju , menyebabkan lesennya digantung secara automatik selama enam bulan dan didenda A $ 1674 .
dilaporkan oleh radio stesen Sydney 2GB bahawa Penguasa Frank Goodyer adalah pegawai yang telah ditangkap memandu laju oleh pegawai sendiri selepas Polis New South Wales mengeluarkan satu kenyataan media yang tidak menamakan pegawai yang telah ditangkap .
penguasa Frank Goodyer memberitahu ABC Radio , " Saya menerima hukuman itu . "
" saya menerima bahawa saya telah melakukan perkara yang salah dan , seperti yang saya katakan , ia masih tugas saya sebagai seorang pegawai kanan polis untuk menggalakkan pemanduan yang selamat dan saya akan terus berbuat demikian tanpa mengira tindakan saya . "
Suruhanjaya Eropah ( EC ) telah meluluskan semalam satu pengambilalihan yang merugikan bmi syarikat penerbangan UK dari Lufthansa oleh Kumpulan Airlines Antarabangsa ( IAG ) , pemilik British Airways ( BA ) .
IAG perlu membuat konsesi selepas diberitahu EC perjanjian itu akan menjadi anti-persaingan .
perjanjian itu dijangka menelan belanja IAG , yang juga memiliki Iberia , £ 172.5 million .
nilai yang boleh jatuh sebagai subsidiari bajet boleh disimpan oleh Lufthansa atau dijual di tempat lain , dan IAG dilaporkan berminat dengan perniagaan bmi utama .
IAG bercadang untuk menggunakan slot diperolehi di tempat yang sibuk , yang berfungsi di London , untuk mengembangkan laluan mereka sendiri ke Asia .
EC memerlukan IAG untuk menyerahkan beberapa slot penerbangan di lapangan terbang .
slot diserahkan atau disediakan untuk pajakan adalah untuk kegunaan ke destinasi di Scotland , Perancis , Mesir , Arab Saudi , dan Rusia .
EC juga menegaskan bahawa gabungan jalan BA / bmi disediakan bagi pesaing untuk membeli tempat duduk pindah .
Lufthansa bertujuan untuk menutup bmi jika tawaran itu gagal .
bos IAG memanggil penjualan itu " berita baik untuk Britain " dengan keputusan yang " baik untuk perniagaan UK dan pengguna UK . "
bos Virgin sebelum ini berkata langkah itu akan memberi BA dominasi berlebihan terhadap penerbangan Scotland .
lebih banyak slot Heathrow diperuntukkan untuk Scotland telah diputuskan daripada mana-mana destinasi lain .
Ryanair mengambil peluang untuk membuat tuntutan terhadap hanya tawaran pengambilalihan mereka sendiri untuk Aer Lingus telah menjadi mangsa utama EC .
" pembelian bmi BA yang memberi kelulusan tanpa memberi pertimbangan yang cukup kebelakangan ini menunjukkan sekali lagi bahawa EC mempunyai satu peraturan untuk pembawa-bendera Eropah , tetapi peraturan yang berbeza untuk Ryanair " , kata Ketua Ryanair .
sembilan orang terbunuh dalam kebakaran belukar di kawasan Semenanjung Eyre di Australia Selatan .
kebakaran itu telah merebak lebih 40,000 hektar belukar , hutan belukar dan tanah ladang setakat ini dan masih membakar di luar kawalan .
beratus-ratus anggota bomba sedang memadamkan api tersebut , tetapi keadaan menjadi sukar kerana angin kencang dan suhu yang melambung tinggi lebih daripada 40 darjah Celsius .
daripada sembilan yang telah meninggal dunia , lapan telah cuba untuk melarikan diri dengan kereta dari api yang merebak .
penduduk tempatan beberapa bandar-bandar luar bandar melarikan diri ke laut untuk melarikan diri dari kebakaran .
beribu ekor biri-biri dan lembu juga telah terbunuh dalam kebakaran .
kebakaran berasingan juga berlaku di sekitar Mount Osmond dan Taman Negara Cleland di bukit Adelaide .
kebakaran belukar adalah kejadian tahunan di Australia , tetapi kebakaran ini adalah yang paling teruk dari segi kematian sejak kebakaran Ash Wednesday yang mengorbankan 28 orang di Australia Selatan .
dua tahun lalu , lebih 400 buah rumah telah terbakar di dalam kebakaran belukar di ibu negara Australia , Canberra .
hari ini , Nintendo mendedahkan bahawa nama sebenar untuk konsol yang sebelum ini dikenali dengan nama kod " Revolution " , adalah Wii .
nama ini telah didedahkan di dalam mesej yang dipaparkan di laman rasmi Nintendo Amerika , yang ditunjukkan di bawah .
sejurus selepas pengumuman itu , nama yang menerima banyak kritikan kerana sebutannya yang terlalu mirip dengan " wee " , perkataan slanga Bahasa Inggeris yang bermaksud air kencing .
nama ini juga berbunyi serupa dengan " ya " dalam bahasa Perancis dan " baik " dalam bahasa Jepun .
Perdana Menteri Australia , John Howard telah menyerang calon presiden Amerika Syarikat , Barack Obama tentang janjinya untuk memperkenalkan rang undang-undang yang akan menarik balik tentera Amerika dari Iraq pada Mac 2008 .
pada hari Ahad , Perdana Menteri Howard berkata langkah itu akan menyerahkan kemenangan kepada pemberontak di Iraq .
" saya rasa ia hanya akan menggalakkan mereka yang ingin benar-benar untuk menjejaskan kestabilan dan memusnahkan Iraq , dan mewujudkan huru-hara dan kemenangan bagi pengganas untuk bertahan dan mengharapkan ( satu ) kemenangan Obama , " kata Howard .
" jika saya kendalikan al-Qaeda di Iraq , saya akan meletakkan satu bulatan sekitar Mac 2008 , dan berdoa , sebanyak yang mungkin , untuk kemenangan bukan sahaja untuk Obama , tetapi juga untuk Demokrat . "
Encik Obama menolak komen Howard sebagai " retorik kosong " , melainkan dia menghantar 20,000 warga Australia untuk berperang di Iraq .
" oleh itu , jika dia ( tidak dapat didengar ) untuk memperjuangkan perjuangan yang baik di Iraq , saya akan mencadangkan dia memanggil 20,000 warga Australia lagi dan menghantar mereka ke Iraq . "
" saya juga ingin ambil perhatian bahawa kami mempunyai hampir 140,000 tentera di darat sekarang , dan pemahaman saya adalah bahawa Encik Howard telah mengatur kedudukan untuk 1,400 " , kata Encik Obama .
kerajaan Australia berkata sumbangannya kepada perang di Iraq adalah sesuai memandangkan penduduk Australia dan saiz tentera dan sambutan Obama gagal menangani " isi isu " itu .
Menteri Luar Alexander Downer berkata 20,000 askar akan menjadi " separuh daripada tentera kita . "
Mr Howard , dianggap sekutu rapat kerajaan Amerika Syarikat , telah menghadapi serangan dan sokongan daripada ahli-ahli politik Amerika Syarikat .
ahli Demokrat Terry McAuliffe berkata " Pertama , Perdana Menteri telah menjadi kawan yang hebat dengan George Bush . "
" beliau telah berkhidmat dengan dia dan mengunci langkah dari hari pertama tentang perang ini di Iraq . "
calon presiden Republikan Duncan Hunter berkata Howard telah memperoleh hak untuk mengulas mengenai polisi Obama " Saya rasa orang Australia telah memperoleh hak untuk berkomen di pentas dunia tentang pasangan mereka dalam usaha ini , kerana mereka telah berjuang sebelah-menyebelah dengan kita di Iraq , " kata Hunter .
" oleh itu , saya berfikir bahawa John Howard , manakala ia bukan satu kenyataan yang ikhlas , dia pada dasarnya menyatakan kebenaran dan itu adalah bahawa apa yang kita katakan di Dewan Senat atau pihak Dewan pergi ke khalayak dunia . "
" dan ia mempunyai kesan ke atas bukan sahaja sekutu kami , tetapi juga musuh kita . "
Roy Ryden , satu lagi Demokrat US berkata komen Encik Howard adalah " pelik " dan menuduh Perdana Menteri itu mengganggu politik AS " Perkara yang paling amal anda boleh mengatakan mengenai komen Mr Howard adalah pelik . "
" anda tahu , kami akan membuat pertimbangan kita sendiri di negara ini berkenaan pilihan raya dan Barack Obama adalah seorang penjawat awam yang hebat . "
Mr Howard telah menarik kritikan dari beberapa ahli Republikan konservatif dengan John Cornyn berkata Howard perlu keluar daripada politik domestik AS .
Perdana Menteri Australia mempertahankan lagi satu kenyataan hari ini , mendakwa rancangan Obama mengancam keselamatan negara Australia .
" jika Amerika Syarikat tmenarik balik unit tempur beliau dari Iraq pada awal tahun depan , ia hanya boleh diwakili sebagai satu kekalahan bagi Amerika Syarikat di Iraq , " katanya .
" saya mempunyai pandangan yang paling kuat bahawa ia adalah bertentangan dengan kepentingan keselamatan negara ini bagi Amerika untuk dikalahkan di Iraq . "
hubungan yang kukuh Australia dengan Amerika Syarikat dan sokongan untuk perang Amerika Syarikat ke atas Iraq adalah isu-isu utama bagi kemenangan keempat pilihan raya berterusan Howard pada akhir tahun 2004 .
pembangkang Australia itu telah menggunakan komen itu sebagai satu peluang untuk menyerang kerajaan .
ketua pembangkang , Kevin Rudd berkata Howard diperlukan untuk mengelakkan berat sebelah dalam politik Amerika kerana ia penting bagi perikatan Australia-Amerika Syarikat yang pemimpin boleh berurusan antara satu sama lain tidak mengira penggabungan politik mereka .
dianggarkan lebih 100,000 orang membantah di Dataran Tahrir kelmarin menentang perintah perlembagaan yang dibuat oleh Presiden Mesir Mohamed Morsi .
polis rusuhan menyuraikan orang ramai dengan gas pemedih mata dan pertempuran bermula .
perintah perlembagaan dibuat pada 22 November oleh Morsi melindungi badan perlembagaan Mesir dari pembubaran dan juga melindungi keputusan eksekutif daripada dikembalikan .
perintah itu mencetuskan bantahan dan mogok yang menyerupai protes yang akhirnya menggulingkan presiden Hosni Mubarak .
pada awal tahun ini pada bulan September mahkamah Mesir memutuskan untuk membubarkan parlimen Mesir .
Morsi menentang pemerintah , mengancam tindakan akan diambil , tetapi kemudian menghormati keputusan yang telah dibuat .
Mohamed ElBaradei berkata Morsi bertindak seperti seorang yang " baru . "
ElBaradei juga telah berkata bahawa disebabkan perintah baru-baru ini " perang saudara mengancam untuk meletus di Mesir . "
demonstrasi balas yang dirancang oleh Ikhwan Muslimin dan Parti Nour telah dibatalkan untuk mengelakkan kemungkinan keganasan berlaku .
penurunan penghasilan madu lebah telah berlaku di Amerika Utara di luar penurunan ketara sejak 25 tahun lalu menurut saintis dan petani .
satu istilah yang agak baru - " Gangguan Kejatuhan Koloni " digunakan untuk menerangkan fenomena ini kurang difahami .
gangguan Keruntuhan Koloni ( atau CCD ) adalah satu sindrom yang dibuktikan oleh kematian besar-besaran menjejaskan populasi serangga keseluruhan .
punca sindrom itu belum difahami dengan baik .
CCD mungkin disebabkan oleh hama atau penyakit yang berkaitan atau patogen yang tidak diketahui .
CCD mungkin dikaitkan dengan penggunaan racun perosak walaupun beberapa kajian telah mendapati tiada faktor-faktor setara alam sekitar di antara kajian wabak yang tidak berkaitan .
menurut Dennis vanEngelsdorp , seorang pakar lebah dengan Jabatan Pertanian Negara Pennsylvania , " Kami cukup yakin , tetapi tidak pasti , bahawa ia adalah penyakit berjangkit . "
madu lebah bertanggungjawab untuk kira-kira satu pertiga daripada pendebungaan tanaman Amerika Syarikat termasuk spesies seperti : pic , kacang soya , epal , pear , labu , timun , ceri , raspberi , beri hitam dan strawberi .
dari tahun 1971 hingga tahun 2006 , kira-kira setengah daripada U.S. koloni lebah madu hilang .
kadar kejatuhan mencapai kadar baru pada tahun 2006 , yang membimbangkan kepada ramai petani dan saintis madu lebah .
sekurang-kurangnya sebelas negeri yang berbeza dan juga sebahagian Kanada diketahui telah terjejas oleh gangguan keruntuhan koloni .
gangguan ini telah dikenal pasti secara geografi di pelbagai negeri termasuk Georgia , Oklahoma , Pennsylvania , Wisconsin dan California .
di beberapa negara kehilangan koloni lebah madu dianggarkan setinggi 75 peratus daripada jumlah populasi .
fenomena ini adalah penting untuk tanaman seperti badam yang ditanam di California , di mana madu lebah adalah pendebunga yang utama dan nilai tanaman adalah $ AS 1.5 bilion .
jumlah tanaman A.S. yang bergantung sepenuhnya kepada madu lebah diketahui melebihi $ AS 15 bilion .
dalam perkembangan yang berkaitan pada 17 Januari 2007 , Agensi Perlindungan Alam Sekitar Amerika Syarikat telah secara drastik mengetatkan peraturan digunakan dalam beberapa ketua racun perosak yang digunakan pada epal , beri biru , anggur , pic , pear dan buah-buahan lain yang didebungakan oleh madu lebah .
memetik kata perlindungan alam sekitar dan keselamatan umum farmworker , EPA mengumumkan baru-baru ini untuk memperketatkan penggunaan atau tidak menggunakan racun perosak fosmet yang sangat bertoksik dan Azinfos metil .
di bawah pemerintahan ini perubahan penggunaan racun perosak organofosfat akan dibenarkan penggunaannya selama lima tahun tetapi mempunyai dos yang agak sedikit .
Azinfos metil adalah neurotoksin berbahaya yang diperolehi daripada agen saraf yang digunakan semasa Perang Dunia II .
Korea Selatan telah terputus hubungan dengan roket Naro-1 , hanya 137 saat selepas berlepas .
Institut Aeroangkasa Penyelidikan Korea ( KARI ) dan Penyelidikan Negeri Khrunichev dan Pengeluaran Space Center berharap untuk menggunakan Naro-1 , roket pembawa pertama Korea Selatan , untuk melancarkan satelit STSAT-2B .
Korea Selatan menangguhkan pelancaran pada hari Rabu kerana masalah dengan sistem pemadam api roket .
jurucakap Kementerian Sains Pyun Kyung-bum berkata , " Kami menjangkakan bahawa ia akan menjadi sukar untuk dilancarkan hari ini . "
roket itu diangkat dari dari Pusat Angkasa Naro Goheung pada pukul 1701 ( 0801 GMT ) hari ini .
roket itu nampak meletup 137 saat selepas pelancarannya , ketika ia dilihat dari kamera atas kapal dan komunikasi telah hilang .
kehilangan komunikasi berlaku apabila roket telah mencapai ketinggian kira-kira 70 kilometer ( 43 batu ) .
kamera televisyen menangkap satu titik putih , berkemungkinan sebahagian daripada roket , jatuh ke laut .
penganalisis berkata kegagalan itu merupakan satu halangan untuk Korea Selatan .
jika ianya berjaya , ia akan menjadi pelancaran pertama Naro-1 untuk mencapai orbit .
pelancaran itu memakan kos Korea Selatan kira-kira AS $ 400 juta , dan jika berjaya , akan melancarkan satelit yang dikenali sebagai STSAT-2B ke orbit .
satelit ini telah direka untuk mengkaji perubahan iklim dan kesan-kesannya .
kejadian itu dilihat sebagai halangan utama bagi program angkasa Korea Selatan , yang telah meletakkan sasaran untuk menjadi negara ke-10 untuk mencapai keupayaan untuk melancarkan satelit , dan negara Asia keempat , selepas China , Jepun dan India .
pelancaran yang berjaya akan membantu Korea Selatan untuk menjadi kuasa baru di pelancaran ruang komersial , industri bernilai kira-kira AS $ 250 bilion .
sejak tahun 1992 , Korea Selatan telah melancarkan 11 satelit dari laman web luar negara dengan roket buatan asing .
gempa bumi kuat melanda di luar hujung selatan Taiwan pada pukul 12 : 26 UTC , mencetuskan amaran dari Agensi Meteorologi Jepun bahawa tsunami 3.3 kaki berkemungkinan menuju ke arah Basco , di Filipina .
namun , ketua agensi pemantauan gempa bumi di Filipina mempertikaikan amaran agensi Jepun .
laporan yang bercanggah telah meletakkan magnitud gempa bumi di antara 6.7 dan 7.2 pada skala Richter , dengan Biro Cuaca Taiwan Tengah menandakannya pada 6.7 , Geologi Amerika Syarikat menganggarkannya pada 7.1 , dan Agensi Meteorologi Jepun meletakkan ianya bermagnitud 7.2 .
walaupun amaran Agensi Meteorologi Jepun mengeluarkan ancaman tsunami kepada Filipina , Renato Solidum , pengarah Institut Gunung Berapi dan Seismologi Filipina , menafikan bahawa tsunami menuju ke Filipina , dengan mengatakan bahawa Pusat Amaran Tsunami Pasifik di Hawaii tidak mengumumkan apa-apa amaran tsunami .
walau bagaimanapun , Solidum berkata penduduk di kawasan-kawasan rendah di Filipina harus , sebagai langkah berjaga-jaga , bergerak ke kawasan yang lebih tinggi .
selepas kejadian gempa bumi itu , agensi berita telah menyiarkan laporan rumah runtuh , tetamu hotel terperangkap dalam lif , dan gangguan telefon kerana talian terputus di seluruh Taiwan .
gempa bumi itu telah merosakkan enam kabel komunikasi gentian optik dasar laut , menyekat akses internet untuk berjuta-juta pengguna di Asia dan Australia .
pengguna di rumah mengalami isu berkaitan sambungan talian , dan selalunya berlaku timeout .
Internet Storm Center melaporkan 100 % kehilangan paket pada penghala tertentu .
ujian sampel ping dari Singapura ke Wikinews datang dengan purata 380 milisaat pergi balik pada 50 % kehilangan paket .
pasaran kewangan menghadapi keadaan yang lebih membimbangkan , dengan perkembangan kewangan dan harga saham dari Amerika Syarikat dan Eropah tidak dapat mencapai pasaran Asia .
membaiki talian " akan memakan masa yang lama , " kata Hong Seoung-Yong , seorang pegawai kementerian dari Korea Selatan yang mengendalikan masalah ini .
kapasiti internet Taiwan telah menurun kepada 40 % , dan seterusnya terdapat rangkaian yang tersekat .
pembekal perkhidmatan boleh memilih untuk memintas talian yang memihak kepada Eropah , kata jurucakap firma telekom Jepun KDDI Corp , Satoru Ito .
gempa bumi itu berlaku tepat dua tahun dari hari raya 2004 Gempa Bumi Lautan India melanda , memusnahkan Asia Tenggara .
gempa bumi 2004 itu didaftarkan sebagai magnitud 9.1 , dan menyebabkan tsunami dengan ombak mencapai setinggi 33 kaki .
orang Peru yang tinggal berhampiran tapak pelepasan merkuri bersedia untuk menyaman sebuah syarikat perlombongan Amerika Syarikat , mereka umumkan Sabtu lepas bahawa mereka akan membawa kes mereka di hadapan hakim Denver .
pada 2 Jun 2000 , kemalangan serius di wilayah Cajamarca , di Peru , meracuni ramai penduduk dengan merkuri , logam berat yang sangat toksik .
sebuah trak dari Newmont Mining Company membuang dua kanister logam merkuri di sepanjang lebuh raya Andean , dalam komuniti San Juan , Choropampa , dan Magdalena .
penduduk bandar yang ingin tahu ( kebanyakannya kanak-kanak ) mengambil titisan berwarna perak , dan ada juga yang meminumnya .
sebahagian daripada mereka yang terlibat dalam sentuhan dengan merkuri mengalami kebutaan , dan ada juga mempunyai ruam ungu di badannya .
lebih 300 orang secara langsung mengalami kesan keracunan merkuri .
sebagai pemilik lombong Yanacocha yang menghasilkan merkuri , Newmont Mining menawarkan sehingga AS $ 6,000 kepada lebih 700 penduduk tempatan , tetapi lebih 1,100 orang lain masih terlibat dalam pertempuran undang-undang dengan Newmont di dalam kes itu .
dalam ekonomi global hari ini , banyak perniagaan antarabangsa telah mengintai peluang di luar negara untuk mengekalkan keuntungan mereka , tetapi profesor undang-undang alam sekitar James Otto bertanya tentang kesan terhadap alam sekitar dan kesihatan awam .
" mana-mana syarikat yang mahu melombong di peringkat antarabangsa kini bukan sahaja harus mempunyai hak yang sah untuk melombong tetapi juga ' lesen sosial ' untuk beroperasi , " katanya .
sementara penduduk Peru bersiap sedia untuk tuntutan mahkamah terhadap Newmont Mining yang berpangkalan di Denver , firma perlombongan emas terbesar di dunia , beberapa soalan-soalan penting akhirnya boleh dijawab .
selepas pemecahan rundingan penyelesaian dengan Newmont pada 20 Januari , penduduk dan peguam mereka mengambil keputusan untuk berhenti berunding secara tertutup dan membawa kes mereka kepada orang ramai .
Sabtu lepas , 5 Mac , 2005 , mereka mengumumkan bahawa mereka akan membawa saman mereka kepada Hakim Daerah Denver Robert Hyatt .
ini bukanlah kali pertama Newmont Mining telah mempunyai masalah dengan Dunia Ketiga yang baru muncul dengan gerakan alam sekitar .
